### ISSUE TITLE
Videos de cátedras

### ISSUE THREAD

**Issue by manarea** [IIC2343/Syllabus-2020-2#1]
Hola!

Una consulta, los vídeos de las clases donde los puedo encontrar? Estuve buscando la de hoy y no pillé nada unu

**Comment by jmwielandt** [comment]
Hola,

Se subirán a youtube (lo comentó el profesor en la clase).
Eventualmente publicará el link en el readme.

Saludos!

**Comment by manarea** [comment]
Gracias por la info!
