### ISSUE TITLE
T1 | Pregunta 1.d) Tipo de output

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#10]
Hola me confundí un poco con esta pregunta, el formato de output de la lista que se pide es en forma de una lista de doubles? es decir, para un numero Xi, el numero que se pide como output sería en formato de 1's y 0's ?

Esto lo pregunto porque para 50 por ejemplo, float de 50 es 50.0, y quizás existe algo similar para el tipo double.
Gracias!

**Comment by aaguilarg** [comment]
Hola @andresplass!
La idea es que el output S sea una lista de doubles, pero fijate en  la nota que:
>Nota: se define como sucesor de un número x en representación double, como el número entero mayor más cercano
a x, que puede ser representado como double.

En principio da lo mismo, ya que el sucesor es el número **entero** mayo más cercano, que puede ser representado en double.  Entonces el output S fue pensada para ser de doubles, pero puedes entregar otro tipo de dato siempre y cuando se cumpla lo pedido.

**Comment by rihanuch** [comment]
Hola! A mi me entró la duda ya que en Python todos los `floats` son `double` y como sabemos que solo se entregarán números enteros en la lista, mi duda es ¿sería solo realizar la potencia de 2^E_i y entregar el resultado?

Digo solo entregar el resultado debido a que sabemos que serán enteros por lo que no habría que redondear (según entiendo)

Gracias! 😄

**Comment by andresplass** [comment]
@aaguilarg yaa muchas gracias, y para cerrar, el tema del sucesor no lo entiendo bien, sí lei la nota pero no me calza. Es el sucesor del numero en formato double??  Es decir, luego de hacer la conversión que se pide en el ejercicio, a cada uno le sumo 1 en el debido lugar para obtener el sucesor del numero en el formato double?

**Comment by inmadariaga** [comment]
Hola a ambos
@rihanuch 
- efectivamente son doubles y esperamos que investiguen el formato interno del tipo de dato y cómo manipularlo
- fíjate en que el enunciado pide encontrar el sucesor de 2**E_i, no el 2**E_i directamente.
- los datos de entrada serán doubles.

@andresplass 
- no te puedo responder eso, pero te recomiendo revisar el formato double con más detalle

**Comment by rihanuch** [comment]
Me sigue quedando la duda con esto:
> - fíjate en que el enunciado pide encontrar el sucesor de 2**E_i, no el 2**E_i directamente.
> - los datos de entrada serán doubles.

1. Los datos de entrada según el enunciado son **numeros naturales** entre el 0 y 100. Por lo que mencionas cambia un poco el enunciado
2. El numero que hay que entregar en que formato es? Binario? Float? Int?

No me queda claro que hay qué hay que hacer? Primero pasar el número que esta en la lista a binario? Usar 2^numero y luego eso pasarlo a double?

Tampoco me queda claro si el sucesor es simplemente el ultimo numero del formato double de los 52 bits y sumarle 1

Muchas gracias desde ya!

**Comment by akrebs2** [comment]
Hola!

Otra pregunta chica: ¿hay que solo entregar la función/algoritmo, o además una explicación?

Gracias

**Comment by jmwielandt** [comment]
> Hola!
> 
> Otra pregunta chica: ¿hay que solo entregar la función/algoritmo, o además una explicación?
> 
> Gracias

Siempre es recomendable que documentes tu código para que te puedan corregir de mejor manera. Si lo harás, hazlo en el propio código. Te recomiendo mirar [esto](https://www.python.org/dev/peps/pep-0257/).

Saludos y disculpa la demora :c

**Comment by jmwielandt** [comment]
@rihanuch 

> Me sigue quedando la duda con esto:
> 
> > * fíjate en que el enunciado pide encontrar el sucesor de 2**E_i, no el 2**E_i directamente.
> > * los datos de entrada serán doubles.
> 
> 1. Los datos de entrada según el enunciado son **numeros naturales** entre el 0 y 100. Por lo que mencionas cambia un poco el enunciado
> 2. El numero que hay que entregar en que formato es? Binario? Float? Int?

Ya actualizamos el enunciado agregando la firma de la función pedida. Los números que entran son ints y los que salen son floats (doubles según la ieee754).


> No me queda claro que hay qué hay que hacer la verdad. Primero pasar el número que esta en la lista a binario? O usar 2^(Ei) y luego eso pasarlo a double? En general no me queda claro el orden de operación de lo que se pide.
> 
> Pregunto el orden de operaciones porque lo que se pide es la implementación y no la parte de operación, por lo que finalmente seria bueno si se puede detallar qué es lo que hay que hacer (orden de operación y tipos de datos)

Nosotros te describimos el resultado esperado y te entregamos las herramientas en la materia. No hay una única forma de hacerlo y tampoco una "pedida". El "cómo" llegas al resultado esperado va por cuenta tuya.

> Tampoco me queda claro si el sucesor es simplemente el ultimo numero del formato double de los 52 bits y sumarle 1
> 
> Muchas gracias desde ya! 😬

En el enunciado se define el sucesor como el siguiente entero representable por el tipo double. No te puedo dar más información :c  

Saludos y mucho ánimo
y perdón por la demora :c
