### ISSUE TITLE
T2 | P1 b explicación enunciado

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#100]
Hola, no entiendo bien a que se refiere con K argumentos. Deberías ser Capaz de hacer MOV A, B, C, ... k veces, cosas de ese estilo (lo cual no se si tiene mucho sentido)? No se si podrían dar un ejemplo de una instrucción con K argumentos, que la verdad no me quedó claro el enunciado.

**Comment by Arcoirisky** [comment]
Pues si, así es. 

Tienes instrucciones del tipo ADD A,B,C,D,E,...,K
Donde A te dice donde guardas tu resultado y el resto B,...,K son los operados

¿Un poco mejor?

**Comment by Arcoirisky** [comment]
Ojo que la instrucción que comente es solo un ejemplo que se me ocurrió  xD 

El K es definido por ustedes, dependiendo de su elección hacen las modificaciones que estimen convenientes

**Comment by VicenteMerino** [comment]
Pero por ejemplo puedo asumir que la cantidad de registros se mantiene fija? Al final si tengo k=4 debería dar soporte para ADD A, A, B, B o no?

**Comment by felipearellanom** [comment]
No estás obligado a hacer ningún cambio siempre que todas las instrucciones originales esten implementadas, respetes que K sea fijo para todas las instrucciones, todas las instrucciones sean una palabra y solo utilizen un ciclo del clock

**Comment by VicenteMerino** [comment]
En esta pregunta, cuando piden que demoren 1 ciclo del clock, debe ser así también para push y pop que en el computador básico que tenemos hasta el momento toma dos ciclos?

**Comment by rihanuch** [comment]
Si digo K=1 sería ADD A,B,B, por ejemplo? 

Pregunto porque no me quedó claro si lo que decia @VicenteMerino es efectivamente como debe ser

Gracias!

**Comment by jmwielandt** [comment]
Hola @rihanuch,
El número K es la cantidad de parámetros que recibe cada instrucción y eso lo decides tú, es 100% libre.
Si te fijas en la isa del computador básico, la instrucción `RET` tiene 0 parámetros, la instrucción `INC B` tiene 1 parámetro y la instrucción `NOT A,A` tiene 2 parámetros. Lo mismo con `ADD A,B` que también tiene 2 parámetros.

En la pregunta tienes que transformar tanto la ISA como la microarquitectura para que:

1. Todas las instrucciones tienen que ser de 1 palabra (en la ROM, como opcode + 1 literal).
2. Todas las instrucciones tienen que tardar 1 solo ciclo.
3. Todas las instrucciones tienen que tener el mismo número de parámetros (al que llamamos K).

Te mostré un subconjunto de la ISA del computador básico que no cumple el punto 3. Te dejo para ti pensar qué instrucciones no cumplen los puntos 1 y 2.

Dime si respondí tu pregunta, saludos!

**Comment by movalle4** [comment]
Hola

Es parte del ejercicio modificar la microarquitectura y la ISA para que todas las instrucciones (incluidas RET y POP) tomen un ciclo en ejecutarse. Se te tiene que ocurrir qué hay que cambiar o agregar para que tomen un ciclo.

Suerte

**Comment by Brocoleta** [comment]
Una pregunta cada instruccion debe aplicarse a todos lo parametros, es decir por ejemplo INC B,A,C deberia aumentar los 3 en 1, o solo B y deberia manejar los otros parametros?

**Comment by movalle4** [comment]
Hola

La idea de esta pregunta es transformar la ISA del computador para pueda hacer lo mismo que el original pero con instrucciones de formato homogéneo. En el caso de  ejemplo de INC B,A,C, solamente se tiene que incrementar B porque esto es lo que hace la instrucción original.

Saludos

**Comment by akrebs2** [comment]
Hola!

Si defino K=2, puedo simplemente decir que en las instrucciones de 1 argumento puedo poner lo que sea en el segundo argumento? Me entra la duda dado que esto no se vería reflejado en los opcodes/señales de control (dado que el omitir esa "argumento de relleno" es trabajo del assembler), entonces no se como se explicita el hecho de que ese segundo argumento nunca se toma en cuenta al pasar desde el código assembly a las señales de control.

Gracias!

**Comment by Arcoirisky** [comment]
@akrebs2 no puedes hacer eso. La pregunta se basa en transformar una arquitectura, el decir que el assembly se hará cargo de argumentos "extra" no es suficiente.

**Comment by akrebs2** [comment]
@Arcoirisky sí estoy modificando la arquitectura para lograr otras condiciones del problema, solo que me pasa que en algunas instrucciones me sobran argumentos, entonces pregunto cómo hacer explícito el hecho de que en el "mapeo" desde las líneas del assembly a las instrucciones, esos argumentos no se toman en cuenta. Este "mapeo" lo hace el _assembler_ por lo que está fuera del scope de la pregunta (Arquitectura, ISA, Assembly).

Gracias!

**Comment by jmwielandt** [comment]
> Solo que me pasa que en algunas instrucciones me sobran argumentos. Por eso pregunto cómo hacer explícito el hecho de que en el "mapeo" desde las líneas del assembly a las instrucciones (tabla de señales de control), esos argumentos no se toman en cuenta.
\- @akrebs2 

No tienes forma de hacerlo porque no se puede hacer (Jessica te lo dijo más arriba). Va en contra de lo que busca la pregunta.

Te recomiendo buscar otra solución o como adaptar la que tienes para que cumpla la restricción del enunciado (yo hice mi propia solución hace tiempo de hecho, te aseguro que se puede hacer "bien"). Argumentos de relleno no son válidos.

Saludos~

**Comment by akrebs2** [comment]
@jmwielandt oka, le voy a dar una vuelta entonces.
Gracias!

**Comment by sgutgar** [comment]
@jmwielandt, argumentos de relleno se puede considerar distinto a simplemente tomar argumentos como 0 supongo en muchas de mis instrucciones o no ?

**Comment by jmwielandt** [comment]
@sgutgar hola, el profe habló en profundidad de eso en la clase del martes
dime si no te queda claro con la explicación del video pls
el link está en el readme
