### ISSUE TITLE
T2 | Diagrama computador básico

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#101]
Hola, no se si es posible si nos pueden subir algún template del computador básico para realizar las modificaciones correspondientes

**Comment by felipearellanom** [comment]
Se va a subir uno dentro de poco

**Comment by felipearellanom** [comment]
Ya está arriba en Material Complementario bajo el nombre de diagrama_pc_basico.drawio
[Diagrama](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Material%20Complementario/diagrama_pc_basico.drawio)

**Comment by Clemente24** [comment]
Hola, me sale este error al abrir el diagrama en draw.io: 
![image](https://user-images.githubusercontent.com/19276556/95492905-98c4cc80-0950-11eb-9711-9062b0a8a3c5.png)

Qué podrá ser?
