### ISSUE TITLE
T2 | P2 b transparencia de stdcall

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#103]
Hola!

No me queda claro a que se refiere cuando se dice
> ...incorpora de manera transparente el uso de la convención _stdcall_, de modo que no es necesario incluir sus requerimientos antes de llamar a la subrutina, como en el cuerpo de esta.

Se refiere a que ya esta implementado por debajo en el "traductor" que tenemos que hacer y no hay que preocuparnos de eso?

Por otro lado, se podría entregar un ejemplo de cómo sería el output de este código y cuál es su extensión? Si código también tiene que traducir el código que estaría entre `DEF` y `RET`, que hay que soportar, etc.

Gracias!

**Comment by CristobalHV** [comment]
Hola!

Lo que intenta explicar el enunciado es que x86++ tiene una sintaxis diferente a x86 para llamar a subrutinas, pero al igual que x86, este sigue la convención _stdcall_. En base a eso, debes escribir código de python que traduzca el código x86++ a x86

Respecto al código, basta con que lo entregues como una función ```def convertir_a_x86_tradicional(args*)``` que reciba una lista de strings (el código x86++) y retorne una lista de strings (código traducido a x86)

Éxito en la tarea!

**Comment by VicenteMerino** [comment]
Debe soportar comentarios el código?

**Comment by rihanuch** [comment]
@CristobalHV 

1.Podrias dar un ejemplo? De esta manera se entendería si por ejemplo solo hay que agregar el overhead de pasar de x86++ a x86.
2. La verdad me sigue sin quedar claro si hay que agregar el procedimiento de stdcall o podemos asumir que ya viene el el x86 (y solo habria que agregar para lo parametros)

Gracias!

**Comment by CristobalHV** [comment]
> Debe soportar comentarios el código?

Sí, su programa debe soportar comentarios. Estos son parte de la sintaxis tanto de _x86++_ como _x86_.

> 1.Podrias dar un ejemplo? De esta manera se entendería si por ejemplo solo hay que agregar el overhead de pasar de x86++ a x86.
> 2. La verdad me sigue sin quedar claro si hay que agregar el procedimiento de stdcall o podemos asumir que ya viene el el x86 (y solo habria que agregar para lo parametros)
> 
> Gracias!

Hola! cometí un pequeño error en mi respuesta anterior: para _x86_ existen muchas convenciones de llamada para subrutinas, entre ellas _stdcall_ que es la que se busca que se familiaricen con este ejercicio de la tarea.

El enunciado indica que _x86++_ incorpora _stdcall_ de "manera transparente", es decir, su sintaxis no muestra explícitamente como usa la convención _stdcall_ , sin embargo la utiliza de todas formas.

Entonces, si ustedes pasan el código de _x86++_ a _x86_ exitosamente, deberían ver en el código x86 explícitamente como se recurre a la convención _stdcall_ al llamar a una subrutina.

Espero haber sido más claro esta vez, no duden en preguntar si tiene otras dudas y éxito en la tarea :)

**Comment by VicenteMerino** [comment]
> Hola!
> 
> Lo que intenta explicar el enunciado es que x86++ tiene una sintaxis diferente a x86 para llamar a subrutinas, pero al igual que x86, este sigue la convención _stdcall_. En base a eso, debes escribir código de python que traduzca el código x86++ a x86
> 
> Respecto al código, basta con que lo entregues como una función `def convertir_a_x86_tradicional(args*)` que reciba una lista de strings (el código x86++) y retorne una lista de strings (código traducido a x86)
> 
> Éxito en la tarea!

Hola @CristobalHV  ese * en args* significa algo en particular, porque estuve buscando y lo que típicamente se usa es *args para recibir una cantidad indefinida de argumentos.

**Comment by aaguilarg** [comment]
Hola @VicenteMerino 
El asterisco en args indica justamente que se puede recibir una cantidad indefinida de argumentos, y debes manejarlos con stdcall. 

(te respondo brevemente lo de respecto al input de ejemplo)

**Comment by CristobalHV** [comment]
Hola @VicenteMerino! utilicé "args*" en la definición de la función para generalizar el input de esta, no significa algo particular.

En principio la función ´´´convertir_a_x86_tradicional(args*)´´´ debe recibir una lista de strings con el código a trasformar, pero si consideras que necesita recibir más argumentos, puedes incluirlos y esa es la gracia del uso de "args*"

Respecto a si se subirá un input de ejemplo, te respondo apenas me informen al respecto

Lamento la confusión, saludos!
