### ISSUE TITLE
T2 | P1 Que escribir como ISA y assembly

### ISSUE THREAD

**Issue by franciscobalmaceda** [IIC2343/Syllabus-2020-2#104]
Para la pregunta 1, la ISA a modificar debe ser la que esta en la slide de clase "11- Arquitectura de Computadores"? y se tiene que escribir las nuevas instrucciones (o modificadas) en ese mismo formato?
De tal ser el caso anterior,, se podría subir, tal como lo hicieron con el diagrama del computador básico, un .tex de la tabla de la ISA con el propósito de hacer menos tedioso la escritura de las nuevas instrucciones?

**Comment by aaguilarg** [comment]
Hola!,
Debes hacer las modificaciones que te encuentres necesarias, ya sea modificar las existentes o agregar nuevas. Haces las modificaciones que consideres necesarias para lograr el objetivo, justificando cada decisión del diseño.

Respecto a lo del ```.tex```, no facilitaremos archivos para la tabla, esto ya que no tenemos. De igual manera, te recomiendo buscar herramientas, en internet por ejemplo, para facilitar esta escritura.

**Comment by gnacrur** [comment]
Hola, no me queda tan claro con la respuesta si buscan que pongamos todo lo de la tabla mencionada. Mi solución al menos llega a 23 señales de control por lo tanto, sería un poco tedioso ponerlas todas y no se si es lo que esperan tampoco. Los opcodes tampoco se si suman mucho ya que simplemente van a ser números. No obstante si dejo eso afuera no se si podría hablar de assembly. Agradecería mucho si pueden especificar un poco más lo que se espera de nosotros para ser más eficientes en lo que hagamos.
Muchas gracias!

**Comment by movalle4** [comment]
En la respuesta de la pregunta 1 se espera que los alumnos hagan un dibujo con las modificaciones que hicieron a la microarquitectura,  la ISA , que debe contener los opcodes y señales nuevos/modificados, y el assembly, con los nombres y operandos de las instrucciones nuevas/modificadas.

Con respecto a tu pregunta en específico, debes escribir una tabla con las 23 instrucciones nuevas/modificadas. Esta tabla debe contener el assembly (nombres y operandos de las instrucciones), opcodes y señales de control.

**Comment by gnacrur** [comment]
Hola @movalle4, se preguntó este tema en clases hoy y el profesor dijo que se podían describir los cambios mencionando como se usarían las señales nuevas, y explicando las cosas que no sean triviales. Por lo que entendí que no necesitaría hacer una tabla con 23 señales de control. Si me dijo que pusiera los opcodes. No se si asumir lo que dijo el profe como lo oficial. Quedo atento.

**Comment by movalle4** [comment]
Hola

Perdón por responder incorrectamente, no sabía que el profesor había respondido esto en la clase. Lo que dice el profesor siempre es lo oficial.

Para los alumnos que lean esta issue en el futuro: el profesor explica  en la clase del martes 13 lo que se espera en la pregunta 1. Deben describir los cambios mencionados y explicar las cosas no triviales.

Gracias por avisarme

**Comment by rakarachon** [comment]
Hola! Para esta misma pregunta (P1.a): podemos basarnos en las tablas de las diapositivas 16 y 17 de la clase 11 como la "ISA oficial" del computador básico que debemos modificar, verdad? y así ir haciendo los nuevos opcodes en base a estos? de manera que no se repitan.

Y una segunda duda: En las tablas de esas mismas diapositivas, hay 2 opcodes repetidos, 0010010 en la diapo 16 (para SUB B, A y SUB A, Lit), y 1000101 en la diapo 17 (para JOV Dir y CALL Dir). Eso es incorrecto, verdad? Entiendo que los opcode no se pueden repetir, pero ahora me entró la duda.

Muchas gracias de antemano!

**Comment by movalle4** [comment]
Hola

La tabla que se encuentra en las diapositivas 16 y 17 de la clase 11 tiene algunos errores (como los que tu mencionas). En el siguiente [link](https://github.com/IIC2343/Syllabus-anteriores/blob/main/Apuntes%20(viejos)/5.5%20-%20Arquitectura%20del%20Computador%20B%C3%A1sico.pdf) se encuentran los apuntes que contienen una tabla sin errores. Pueden usar esa tabla como la "ISA oficial" que deben modificar

Suerte

**Comment by movalle4** [comment]
Hola

Respondiendo a tu primera pregunta, sí quieres puedes usar las diapositivas 16 y 17 de la clase [11](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Clases/11%20-%20Arquitecturas%20de%20Computadores.pdf) como una guia de la ISA  por modificar. Pueden modificarla todo lo que quieran, incluso pueden dejarla completamente distinta. Por eso el profesor puso "transforme" y no "modifique" en el enunciado de la tarea.

Respondiendo la segunda pregunta, la tabla de la clase 11 tiene algunos errores (como que los opcodes no son únicos).  Existen apuntes de semestre [pasados](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Clases/11%20-%20Arquitecturas%20de%20Computadores.pdf) que no contienen estos errores y les pueden ser útiles, pero no pueden considerarse como "oficiales" porque el profesor no los ha revisado y porque es posible que estos apuntes de semestre pasado tengan algunas instrucciones diferentes

**Comment by rakarachon** [comment]
Perfecto, muchas gracias!
