### ISSUE TITLE
Duda señales de control Sa0, Sa1, Sb0 y Sb1

### ISSUE THREAD

**Issue by rakarachon** [IIC2343/Syllabus-2020-2#105]
Hola! Revisando la arquitectura y opcodes del computador básico, me di cuenta que no tengo muy claro para que son las señales Sa0, Sa1, Sb0 y Sb1.

![diagrama_pc_basico-Diagram](https://user-images.githubusercontent.com/30667811/95510315-18bc5800-098c-11eb-80d7-44974424fc6a.png)

Entiendo que Sa0 y Sb0 son para indicar si entra un 0 al mux A o B respectivamente, y Sb1 para indicar si entra un literal al mux B. ¿Es correcto esto?

En cuanto a Sa1, no entiendo cual es su objetivo específico. En las slides de la clase de programabilidad parte 2, la señal Sa1 aparece entre las diapositivas 13 y 14 (13 no la tiene, 14 si), al igual que un 1 que entra al mux A, cuando se presenta el direccionamiento directo. Pero luego en la diapo 16, cuando se muestra nuevamente la tabla de señales y opcodes, no aparece la nueva señal Sa1, y más adelante en las slides tampoco logré encontrar la señal Sa1 en la tabla. Si la encontré acá:

![image](https://user-images.githubusercontent.com/30667811/95511239-92087a80-098d-11eb-838d-bd61f45d2c51.png)

pero no logré entender el objetivo de la señal.

Revisé también los apuntes, y al igual que en las slides, la señal Sa1 y el 1 que entra al mux A aparecen entre un diagrama y otro cuando se habla de direccionamiento directo, pero tampoco logre entender porque aparece en esa parte.

Les agradecería un montón si pudieran aclararme estas dudas porfa.

De antemano muchas gracias!

**Comment by rakarachon** [comment]
Revisando los videos de las clases, ya caché para que que es Sa1 y ese 1 que entra al mux A 😅: Sa1 se utilizaría en la instrucción INC para aumentar un contador que va recorriendo un arreglo, verdad?

P.D.: sigo con las dudas para las otras señales 😁 

De nuevo, muchas gracias de antemano!

**Comment by lothardp** [comment]
Hola!
Mira te explico para ver si te queda más claro. Lon multiplexores son componentes que reciben de entrada **n** inputs, de los cuales solo 1 es elegido para salir. En el caso de los MUX A y MUX B del computador básico, cada input es un bus de 8 bits. Para elegir que input es el que pasa como output, el multiplexor (ó MUX) recibe además señales de control. Con solo una señal de control puedes elegir solo entre dos inputs, por lo que el MUX solo puede tener hasta dos inputs (ya que la señal puede ser 0 o 1).  Con dos señales de control, puedes tener hasta 4 inputs en el MUX, ya que ambas señales pueden tener los valores 00, 01, 10, 11. Con 3 señales de control podrías tener hasta 8 inputs, y así...

Ahora aplicado en el computador básico:
>Entiendo que Sa0 y Sb0 son para indicar si entra un 0 al mux A o B respectivamente, y Sb1 para indicar si entra un literal al mux B. ¿Es correcto esto?

Esto no es del todo correcto. Sb0 y Sb1 son señales que funcionan juntas, ambas conforman las señales de control del mux B, y según el valor de **ambas** es que se decide que tira de output el MUX B. No es que Sb0 por si sola indica si entra un 0 o Sb1 por si sola indica si entra un literal. Si te fijas en la tabla de opcodes, Sb0 y Sb1 están juntas, y en vez de salir valores (0,1) para ellas, sale B, LIT, DATAOUT o ZERO, los cuales cada una representa uno de los 4 valores distintos (00,01,10,11) que Sb0 y Sb1 pueden formar juntas. Entonces no siempre que Sb1 sea 1 significa que pasa un literal, depende también de Sb0. Por ejemplo podríamos definir que Sb0 = 0 y Sb1 = 0 significa que el output de MUX B es el 0. Pero Sb = 0 y Sb = 1 significa que pasa el valor del Reg B, por lo que Sb0 sola no indica que pasa el 0. 

> En cuanto a Sa1, no entiendo cual es su objetivo específico. En las slides de la clase de programabilidad parte 2, la señal Sa1 aparece entre las diapositivas 13 y 14 (13 no la tiene, 14 si), al igual que un 1 que entra al mux A, cuando se presenta el direccionamiento directo. Pero luego en la diapo 16, cuando se muestra nuevamente la tabla de señales y opcodes, no aparece la nueva señal Sa1, y más adelante en las slides tampoco logré encontrar la señal Sa1 en la tabla. Si la encontré acá:

Es por la misma razón. Sa0 y Sa1 son las señales de control del MUX A y definen que input es el que pasa. MUX A originalmente solo recibía dos inputs (el valor de RegA y el 0), por lo que con solo una señal (Sa0) basta para decidir que input pasa, cada input "mapeado" a un valor de la señal (0, 1).  Al agregar al MUX A la opción que reciba un input con el valor 1, ahora tenemos 3 inputs, por lo que para decidir entre ellos nos "falta" un bit de señal. Por lo tanto agregamos la señal Sa1, la cual ahora **en conjunto con** Sa0 son las señales de control del MUX A. Ojo, ahora con 2 señales de control (Sa0 y Sa1), podemos elegir entre 4 inputs (ya que entre ambas pueden generar 4 valores distintos: 00,01,10,11), pero el MUX A solo recibe 3 inputs. Esto significa que un valor de los posibles que pueden formar Sa0 y Sa1 juntas esta siendo "desperdiciado".  En teoría entonces podríamos agregar un 4to input al MUX A, por ejemplo un 2, para poder hacer incrementos de dos más eficientemente (es solo un ejemplo), sin tener que agregar otra señal de control. Si agregáramos un quinto input, ya no nos bastaría con dos señales de control y tendríamos que agregar una más para poder elegir entre ellos. 

>Revisé también los apuntes, y al igual que en las slides, la señal Sa1 y el 1 que entra al mux A aparecen entre un diagrama y otro cuando se habla de direccionamiento directo, pero tampoco logre entender porque aparece en esa parte.

La verdad es que es cierto que aparece un poco de la nada en las slides, pero es lo que expliqué más arriba. Ahora con el 1, MUX A tiene 3 inputs, por lo que necesita 2 señales de control (o al menos 2) para poder elegir entre ellas. Por eso aparece Sa1. 

>Revisando los videos de las clases, ya caché para que que es Sa1 y ese 1 que entra al mux A 😅: Sa1 se utilizaría en la instrucción INC para aumentar un contador que va recorriendo un arreglo, verdad?

Algo así. Sumar 1 a un valor es una instrucción que se usa mucho, por lo que es útil poder implementarla directamente en hardware. Para hacer esto, elegimos agregar el input con el bus 1 (b0000 0001) como input al MUX A, para poder utilizarlo sin tener que pasar 1 como literal. Sin embargo al hacer esto, el MUX A queda con 3 inputs pero solo 1 señal de control (Sa0) por lo que necesitamos agregar una nueva señal de control (Sa1) para poder elegir entre los 3 inputs distintos que tiene el MUX A. Quiero recalcar que no es que Sa1 esté ligada directamente a que pase el 1 por el MUX, sino que es un nuevo bit de control, que en conjunto con Sa0 pueden representar 4 valores distintos, de los cuales 3 de ellos están mapeados cada uno a uno de los inputs, de los cuales uno de ellos es el 1. 

Espero haber aclarado tus dudas, si no es así responde a esta Issue. 
Saludos!

**Comment by rakarachon** [comment]
Me quedó clarísimo, te pasaste. Muchas gracias!
