### ISSUE TITLE
T2 | P2 B VARIABLES LOCALES

### ISSUE THREAD

**Issue by Brocoleta** [IIC2343/Syllabus-2020-2#106]
Hola, en la pregunta 2 b) nos dicen que nos pasaran las subrutinas x86++ como DEF subroutine(arg1, arg2, ..., arg n), mi pregunta es como sabemos cual de estos argumentos es un parametro y cual es una variable local?, ya que deberian ser tratados de diferente manera al pasarlos a x86,
Gracias

**Comment by inmadariaga** [comment]
Hola! los argumentos pueden ser variables, registros o literales. Un ejemplo de llamado sería:
CALL subrutina(BX, largo, [BP - 4])
Bueno, tu programa debe ser capaz de identificar los argumentos para traspasarlos a x86

**Comment by jfuentesg26** [comment]
Hola! Me confundí un poco con el ejemplo que dieron, si pasan como argumento [BP - 4] te estas refiriendo a que esa será una variable local dentro de la subrutina que vas a llamar? (y así poder identificar cuantas variables locales tiene) o es una variable que viene de una subrutina anterior? es un poco raro que pasen como argumentos variables locales.
Gracias
