### ISSUE TITLE
T2 | P2 b Manejo de strings

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#107]
Hola, en la P2-b podemos (y dado que el manejo de strings no es el objetivo de la tarea) podemos asumir que no habrán espacios antes de la instrucción, por ejemplo los strings serán de la forma "DEF soubroutine..." Y no " DEF soubroutine..."

**Comment by VicenteMerino** [comment]
Podemos asumir que los argumentos serán lo suficientemente descriptivos y que por ejemplo si arg1 es un argumento, arg12 no lo será? Esto con el fin de simplificar los reemplazos.

**Comment by aaguilarg** [comment]
No, no se puede asumir eso, es algo que esperamos que puedan manejar.

**Comment by sjkinast** [comment]
Hola! cuando la subrutina recibe más de un argumento, estos como serán separados ? por una coma y un espacio o por solo una coma, es decir:
caso1:  'DEF funcion(arg1, arg2):'
caso2: 'DEF funcion(arg1,arg2):'
