### ISSUE TITLE
T2 | P1 Diagrama de PC básico

### ISSUE THREAD

**Issue by niguzman** [IIC2343/Syllabus-2020-2#108]
Hola,
podrían subir el diagrama del computador básico que se usó en la ayudantía 5 (el archivo de draw.io)
Esto lo preguntaron en la ayudantía y la ayudante dijo que creía que no habría problema en subirlo pero revisé los archivos dl Syllabus y no lo encontré 😢
Gracias!

**Comment by conikuschel** [comment]
Esta en la carpeta material complementario
