### ISSUE TITLE
Posible error en señales de control en la ISA expuesta en la clase 0xb

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2343/Syllabus-2020-2#109]
En el material de la [Clase](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Clases/11%20-%20Arquitecturas%20de%20Computadores.pdf) noté (mientras hacía la tarea 2) que hay una señal de control errónea. Los valores de ```La``` y ```Lb``` están intercambiados en la última fila de la foto adjuntada.

![image](https://user-images.githubusercontent.com/48391930/95795802-a916d780-0cc1-11eb-8763-36b1ff120c1d.png)

**Comment by movalle4** [comment]
Hola

Tienes razón, hay un error en esa última fila. Se debería modificar el registro A y no el B.

Gracias
