### ISSUE TITLE
T1 | Duda al abordar pregunta 1b

### ISSUE THREAD

**Issue by ibaeza1** [IIC2343/Syllabus-2020-2#11]
Hola!
Estoy un poco confundida con la pregunta (1a). La verdad es que no entendi mucho como abordar la pregunta en general. 
No entendi como como saber cual es el endianness original ni como afecta eso al numero en si. Tampoco entendi que tiene que ver el 0x36.
Muchas gracias :)

**Comment by aaguilarg** [comment]
Hola @ibaeza1!
La verdad el endianness original no lo necesitas saber, por lo que puedes asumir uno y luego cambias ese que asumiste. Lo de la dirección, no es importante la dirección específica 0x36 , sino que lo que viene unas palabras antes. Fijate en la cantidad de palabras que lee. Esos son los datos que te interesan.

Espero haberte ayudado :smile:  y quedo por si no quedó algo claro

**Comment by aaguilarg** [comment]
Además, respondiendo a en que afecta el endiannes, pensemos en el ejemplo de números en base decimal. Comunmente, nosotros usamos little endian para numeros decimales, entonces el número 10 en little endian, es diez. Pero si cambiamos a big endian, 10 sería uno (porque los digitos mas significativos están al final)

**Comment by VicenteMerino** [comment]
@aaguilarg Me quedó una duda en cuanto a lo que dijiste sobre "unas palabras antes", ahí te estás refiriendo a lo que leería en 0x36,0x35,0x34,0x33. Pero cómo sabemos en que orden lee las palabras y por qué no 0x36,0x37,0x38,0x39. No se si tenga que ver, pero eso sería si asumimos que estamos en el Stack de memoria? Tal vez no influya mucho con la respuesta ese orden, pero me surgió la duda.

**Comment by VicenteMerino** [comment]
@aaguilarg y respecto a tu segunda respuesta, no se seguiría interpretando como un 10, ya que lo que cambia el endianess son los bytes y no los bits?

**Comment by aaguilarg** [comment]
Si, toda la razon, pido disculpas.

Respecto al 10 o 01 efectivamente es como dices pero este era un ejemplo para explicar lo que busca el ejercicio, sería mas correcto pensar que si tienes un numero que se leyó aaaaaaaa bbbbbbbb al cambiar su endiannes se leería bbbbbbbb aaaaaaaa
