### ISSUE TITLE
T2 | 2.b formato del codigo x86++ de entrada

### ISSUE THREAD

**Issue by franciscobalmaceda** [IIC2343/Syllabus-2020-2#110]
Como va a ser el formato de entrada del codigo x86++? debo considerar, en el codigo python, abrirlo desde un .txt? si es el caso, se podría subir un código x86++ ejemplo para que podamos probar el funcionamiento? o se espera de nosotros que vayamos creando codigo x86++ para ir probando nuestro traductor?

**Comment by movalle4** [comment]
No debes preocuparte la manera en que se va a recibir el input. Solo debes preocuparte de crear una función en python de la forma: `def convertir_a_x86_tradicional(args*)` que haga lo pedido.

**Comment by JJJGGGG** [comment]
Hola, no entiendo. ```def convertir_a_x86_tradicional(args*)``` debería recibir como input una ruta de input y de output, o debería recibir un texto de salida y de entrada, o debería recibir un array de líneas de entrada y de salida?
