### ISSUE TITLE
T2 | P2 Interpretación enunciado

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#111]
Hola! Me sigue sin quedar claro esta parte del enunciado:

"Además de esta modificación, la nueva sintáxis incorpora de manera transparente el uso de la convención stdcall, de modo que no es necesario incluir sus requerimientos antes de llamar a la subrutina, como en el cuerpo de esta."

Al leer esto me surgen tres posibles interpretaciones:

1. Sea lo que sea que hay que hacer antes de llamar a la subrutina (para cumplir con stdcall) ahora se hace en el cuerpo de la subrutina? 
2.  Sea lo que sea que hay que hacer antes de llamar a la subrutina (para cumplir con stdcall) ahora no se hace ni antes ni en el cuerpo de la subrutina (o sea nunca)?
3. Sea lo que sea que hay que hacer antes de llamar a la subrutina y en el cuerpo de esta (para cumplir con stdcall) ahora no se hace?

Básicamente lo que me parece un poco ambiguo es el uso del conector "como". 
Muchas gracias!!!

**Comment by movalle4** [comment]
Hola

Significa que en el cuerpo de la subrutina, al igual que antes de la subrutina, no es necesario incluir los requerimientos de stdcall.

En la issue #103 se explica con mayor detalle lo que hay que hacer en esta pregunta en caso de que sigas con dudas.

Éxito
