### ISSUE TITLE
Stack Frame en emulador assembly

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#112]
Hola. Estuve leyendo sobre compilación de código C a assembly, y hay algo que me parece muy interesante: al llamar una función, se guardan los estados de todas las variables en el scope de la función dada, y luego se agregan al stack nuevos espacios para las nuevas variables, dejando las anteriores intactas. No vi esto en el emulador, y siento que es esencial para poder hacer subrutinas y no estar malabareando con los pocos registros existentes. Vamos a agregar esto en algun momento a nuestro computador (teoricamente)?

**Comment by jmwielandt** [comment]
Hola, no se agregará.
El emulador se ciñe a la arquitectura del computador básico y en esta no existe dejar espacio en el stack para el paso de parámetros o variables locales como parte de la "convención de llamada". Lo que sí puedes hacer es usar Push y Pop para tener algunas variables locales.

Entiendo que es una lata tener tan pocos registros y demás limitantes, pero está hecho así (desde hace milenios) a propósito como parte de la experiencia.
Saludos~
