### ISSUE TITLE
[Duda Clase 14 - Arquitectura x86: Elementos Básicos] Registros de uso general divididos en 2

### ISSUE THREAD

**Issue by fbarrientosj** [IIC2343/Syllabus-2020-2#113]
**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**

En la Clase 14, se menciona que la micro-arquitectura de la arquitectura x86, contiene 4 registros de propósito general (16 bits), los cuales están divididos en altos y bajos. Según el profesor, esto se hace para que los programas nativos de 8 bits puedan funcionar sin problemas, utilizando solamente los registros altos (o bajos dependiendo de la micro-arquitectura). 

Mi pregunta es: ¿por qué es necesario hacer esta separación? Por lo que entiendo, un programa que trabaja con 8 bits está contenido en un computador que corre con 16 bits, por lo que hacer operaciones con 8 bits no sería problema.

**Comment by aaguilarg** [comment]
Hola @fbarrientosj . Esta separación, como dijo el profesor en clases, se hace para que los programas nativos de 8 bits puedan funcionar sin problemas. Como tu dices, "un programa que trabaja con 8 bits está contenido en un computador que corre con 16 bits", pero esta separacion se hace principalmente para reducir el largo de las instrucciones. Ya que si tu solo necesitas guardar un valor de 8-bits, tener que traspasar esto a una instruccion de 16 bits, esto resulta costoso, entonces la operación con 8 bits si seria un poco de problema si no se hace esta separación.

**Comment by aaguilarg** [comment]
Hola @fbarrientosj 
Como tu dices "un programa que trabaja con 8 bits está contenido en un computador que corre con 16 bits", pero la diferencia de registros se hace principalmente para disminuir el tamaño de las instrucciones. Ya que si tu quisieras guardar un valor de 8 bits en un registro, tendrías que transformar la instruccion a una de 16 bits para poder operar. Lo que sería mas costoso, ese es el problema.

**Comment by aaguilarg** [comment]
Agregando a lo anterior, cito algo que les comentó el profesor en clases:

>To leverage its existing customer base, Intel made 8086 software-compatible down to 8008. A simple translator program would translate from 8008 assembly to 8086 assembly. For that to work well, 8086 instruction set architecture had to map well to 8008, inheriting many design decisions.

Que basicamente indica que tomaron estas decisiones de diseño para poder tener compatibilidad con sus versiones anteriores. [Aquí](https://keleshev.com/eax-x86-register-meaning-and-history/) te dejo una página para que puedas ahondar mas en el tema si te interesa.

**Comment by andrescf** [comment]
Hola! Anclandome a la pregunta, como lo vimos en un computador basico el input de los registros vienen todos de un mismo bus de datos, para este caso en que el registro A esta dividido en 2 de 8 bits A recibe un bus de 16 bits pero ¿como se divide en 2 de 8 para que se guarden los primeros 8 en AL y los ultimos 8 en AH?
Y lo mismo para la memoria, ¿si quiero guardar un dato de 16 bits el bus de datos que llega debe ser de 16 o llegan 2 señales de 8?

**Comment by Arcoirisky** [comment]
No estoy segura de entender tu primera pregunta @andrescf. Cuando decimos bus de 16 bits pensamos en 16 cables de 1 bit que entran en AX, este registro se forma por AH, AL los cuales reciben 8 bits cada uno. Dependiendo de si tu arquitectura es big-endian o Little-endian se almacenan de una u otra forma dentro de AX pero todo lo que conocen del computador básico se sigue cumpliendo en este. Sólo que tienes más registros y formas diferentes de interactuar con ellos.

Para la segunda pregunta, todo depende de la ISA. Pero si revisas las [Slides de clases](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Clases/12%20-%20Arquitectura%20x86%20-%20Elementos%20B%C3%A1sicos.pdf) la memoria del x86 es de 16 bits, por lo tanto el bus de datos que llega debe ser de 16 bits.

**Comment by andrescf** [comment]
@Arcoirisky Okaa gracias!
