### ISSUE TITLE
T2 | P1.a Uso de literales

### ISSUE THREAD

**Issue by cchauriye** [IIC2343/Syllabus-2020-2#114]
Hola!

Me queda la duda de si al decir que el computador opera nativamente con datos de 8 bits y 16 bits también significa que los literales con los que se opera pueden ser de esos tamaños.

Gracias!

**Comment by CristobalHV** [comment]
Hola @cchauriye !

Efectivamente cuando decimos que el computador opera nativamente con datos de 8 bits y 16 bits, significa que debe soportar literales de esos tamaños.

Saludos :)
