### ISSUE TITLE
T2 | P2.b Operaciones con argumentos soubroutine

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#115]
Hola tengo una duda, en x86++ si tengo una subrutina escrita como DEF suma(arg1, arg2)

es posible que en el cuerpo hay operaciones como

MOV BX, arg1
MOV CX, arg2
ADD BX, CX

Es decir, que opere directamente con los valores de los argumentos?

**Comment by VicenteMerino** [comment]
Buenísimo muchas gracias, y una última cosa, en este mismo aspecto, el cuerpo de nuestro código en x86++ puede tratar estos argumentos por valor y por referencia o solo por valor?

**Comment by aaguilarg** [comment]
Como x86 puede tratar por valor y referencia, x86++ también puede
