### ISSUE TITLE
T2 | P2b Variables locales

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#116]
Hola, me parece que la forma en que se utilizan las variables locales con la sintaxis x86++ no es muy clara y no queda muy especificada con lo que dice el enunciado, por lo que agradecería si pudieran decir cual es el formato con el cual se manejan en esta sintaxis.

**Comment by aaguilarg** [comment]
Hola,
No entiendo muy bien a lo que te refieres con la forma en que se utilizan las variables locales en la sintaxis x86++. Si con esto te refieres a como se definen en esta sintaxis, estas se definen como variables locales normales en tu codigo de assembly, y en tu codigo que transforma x86++ a x86 tradicional, debes manejar estas definiciones con stdcall, ya que x86++ incorpora esto de manera transparente.

**Comment by VicenteMerino** [comment]
En x86 típicamente tenemos que para acceder a una variable local, usamos el [BP - múltiplo de 2] y gracias a esta sintaxis sabemos que en dicha posición hay variables locales, pero se trabaja "por detrás" y no es obligación usarlas, pero con x86++ no hay claridad de qué es una variable local o como está definida, a menos que haya un label del tipo var y haga MOV var, 1 o var = 1 (lo cual no tiene sentido, ya que rompe la sintaxis de assembly). No se si podrías dar un ejemplo de una variable local en la sintaxis x86++?

**Comment by aaguilarg** [comment]
Las variables locales se definen de igual manera que en x86 tradicional, es decir, guardas espacio en el stack, y luego te refieres a ellas como  [BP-x]

Espero esto te sea de ayuda, éxito!

**Comment by VicenteMerino** [comment]
@aaguilarg Por lo que me comentó una compañera que hacia el final de la clase de hoy el profe dijo que no nos preocupáramos de las variables locales, no se si podrían confirmar que esto es así?

**Comment by felipearellanom** [comment]
Efectivamente es así, si quieres la explicación del profesor está [aquí](https://youtu.be/MxLBow1J3QQ?t=4706).
