### ISSUE TITLE
Duda apuntes

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#117]
Hola, me surgió una duda respecto a los apuntes de stdcall, donde se muestra un ejemplo con paso por referencia y paso por valor.

Valor:
![Screenshot from 2020-10-15 22-06-08](https://user-images.githubusercontent.com/47841749/96201324-ab339d00-0f32-11eb-8af5-b6d29c6dea5a.png)

Referencia:
![Screenshot from 2020-10-15 22-06-32](https://user-images.githubusercontent.com/47841749/96201350-b686c880-0f32-11eb-87aa-ab967568ddbf.png)

El hecho de que el paso por referencia se haga con registros distintos al recuperarlos obedece a alguna razón en particular o es meramente coincidencia y este paso pudeo haber ocurrido con los mismos registros usados en el ejemplo 1?

**Comment by andrescf** [comment]
Respecto al mismo ejemplo, ¿el BP es como el SP y esta definido siempre o tengo que definirlo al inicio? Ya que en ninguno de los dos ejemplo esta definido al comienzo, solo se le hace PUSH y luego se cambia su valor a SP.

**Comment by inmadariaga** [comment]
@VicenteMerino 
Cuando pasas por referencia almacenas las direcciones en los registros SI y BX, pero cuando se pasa por valor almacenas los parametros en los registros CL y BL, esto pasa porque los distintos registros ademas de servir para cualquier cosa, los registros tambien tienen un proposito alternativo.
@andrescf 
El BP apunta a la base del stack anterior a la llamada de la subrutina y sirve para saber donde esta la dirección de retorno de esta, mientras que el SP apunta a la parte superior del stack

Si quieren mas detalle lo pueden revisar acá:
https://riptutorial.com/es/assembly/example/18064/x86-registros

**Comment by andrescf** [comment]
@inmadariaga Oka muchas gracias!

**Comment by VicenteMerino** [comment]
@inmadariaga En ese mismo sentido podemos asumir que alguno de esos registros puede ser usado para pasar las variables, ya que encuentro muy raro como hacer el paso por referencia?. El paso por valor, según el ejemplo es solo llegar y hacer PUSH (aunque a veces se hace con un registro, pero al parecer se puede implementar así), pero el paso por referencia es mucho más complejo, ya que debo tener cuidado que el registro no ha sido usado anteriormente para no pisar el valor del registro.
