### ISSUE TITLE
T2 | P2b Duda sintaxis Assemblyx86

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#119]
Hola, cuando hacemos direccionamiento puede ser solo de la forma [AX], o también soporta espacios entremedio: [ AX ]? Puedo asumir que será solo de la primera manera? De manera similar es válido algo como [ BX + SI ] o podemos asumir que siempre será [BX+SI]? Esto con el fin de simplificar el manejo de espacios en blancos.

**Comment by felipearellanom** [comment]
Debería poder funcionar con o sin espacios.
