### ISSUE TITLE
T1 | 1.d Doubles

### ISSUE THREAD

**Issue by sgutgar** [IIC2343/Syllabus-2020-2#12]
Quería saber si tengo que pasar a binario para los doubles. En caso de que no, que tengo que hacer si se da que ningun numero en S llega a más de 52 bits (máximo del significante).

Muchas gracias!

**Comment by inmadariaga** [comment]
Hola @sgutgar :
- no te puedo responder eso, pero te recomiendo revisar el formato double con más detalle

**Comment by inmadariaga** [comment]
Hola @sgutgar no, lo esperado es que trabajen con la estructura de doubles
