### ISSUE TITLE
T2 | P2b Valor de retorno

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#120]
Podemos asumir que en el código, como el valor de retorno se almacena en AX, si quiero recuperar ese valor después del CALL, eso vendrá en el código que me entreguen? Por ejemplo con una instrucción MOV res, AX, pero que es algo que vendrá en el input.

**Comment by inmadariaga** [comment]
hola! te invito a revisar el enunciado actualizado, ahi se agrego un ejemplo que puede resolver tu duda, saludos!
cualquier cosa escribenos

**Comment by VicenteMerino** [comment]
Si por lo mismo la cerré ajaj. Gracias de todas formas.

**Comment by inmadariaga** [comment]
De nada, dejaré la issue abierta por si alguien más le entra la duda!
