### ISSUE TITLE
RET fuera de subrutina

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#122]
Hola, tiene sentido usar un RET fuera de una subrutina? Que en el siguiente código del compilado se usa dentro del main, lo cual no se si me hace mucho sentido o con que fin se usa?

![Screenshot from 2020-10-16 14-11-30](https://user-images.githubusercontent.com/47841749/96288286-8a625a80-0fb9-11eb-8a4f-ec45bd2fd50c.png)

**Comment by inmadariaga** [comment]
hola! la instruccion RET carga el valor de memoria apuntado por el SP en el PC y piensa que main puede ser considerado una subrutina que puede ser llamada usando CALL main
