### ISSUE TITLE
T2 | Push con parámetro

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#123]
Hola quiero confirmar que efectivamente la arquitectura x86 soporta la instrucción PUSH var? Porque la que vimos el computador básico solo soportaba como operando un registro, entonces como en el ejemplo se usó supongo que es válido hacer push directamente del parámetro sin pasarlo previamente a un registro?

**Comment by inmadariaga** [comment]
hola! efectivamente puedes PUSH var, para mas detalle revisa:
https://jbwyatt.com/253/emu/8086_instruction_set.html
el link esta en los apuntes (apunte 8/pagina 9)
