### ISSUE TITLE
T2 | EMU Release 2.0.4

### ISSUE THREAD

**Issue by tocococa** [IIC2343/Syllabus-2020-2#124]
Hola!

Estaba actualizando el emulador del curso a la versión del último release, pero en el changelog no está el archivo `emu.zip`, ¿tenemos que usar el de una versión anterior o estoy muy perdido?

![image](https://user-images.githubusercontent.com/22779371/96310990-e12e5b00-0fde-11eb-825f-2857995db744.png)

**Comment by jmwielandt** [comment]
Hola, mira la [guía de uso](https://github.com/IIC2343/Syllabus-2020-2/wiki/Gu%C3%ADa-de-uso) que aparece en la wiki. Esta versión no tiene interfaz gráfica pero a cambio pueden configurar más la ejecución ;D

Saludos!

**Comment by tocococa** [comment]
Ahh, oka, gracias!
