### ISSUE TITLE
T2 | P2.b Formato de escritura

### ISSUE THREAD

**Issue by niguzman** [IIC2343/Syllabus-2020-2#125]
Hola, una consulta
Quería saber cómo será el código con el que lo probarán con respecto a los espacios, por ejemplo:

- DEF factorial (arg1) :  **o**  DEF factorial(arg1):  **o**  DEF factorial ( arg1 ) :
- MOV BX , arg1  **o**  MOV BX, arg1  **o**  MOV BX,arg1

Gracias

**Comment by Arcoirisky** [comment]
Me dicen por interno que funciona con todo tipo de espacios @jmwielandt
