### ISSUE TITLE
T2 | Pregunta 3a 

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#126]
Hola! En la pregunta 3a) para hacer las operaciones (suma, resta, multiplicacion y división) se supone que al I/O le llegaran los datos de los dos números que quiere operar y su respectivo operador y el I/O debe devolver el resultado? Gracias!

**Comment by felipearellanom** [comment]
Es decisión tuya como lo modeles. Debe ser capaz de hacer todo lo que un coprocesador matemático puede hacer interactuando con I/O y con el computador básico.
