### ISSUE TITLE
Señales de control de SHL(dir), SHR(dir), NOT(dir)

### ISSUE THREAD

**Issue by akrebs2** [IIC2343/Syllabus-2020-2#127]
Hola!

Me entra una duda con estas tres operaciones:

SHL(dir) --> Mem[Dir]=shift left A
SHR(dir) --> Mem[Dir]=shift right A
NOT(dir) --> Mem[Dir]=not A

Por qué es necesario que la señales de control Sb,0,1 tengan que elegir a lo proveniente del MUX B en estas tres operaciones, siendo que en las otras operaciones que involucran un solo operando con A, el valor de Sb,0,1 puede ser cualquier cosa. Es un error en la tabla de opcodes?

Gracias!

**Comment by felipearellanom** [comment]
Es tal y como dices, las señales de control Sb0 y Sb1 pueden tomar cualquier valor en esa instrucción pues no se utiliza la salida del Mux B.
