### ISSUE TITLE
T2 | P3 formato de datos

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#128]
Hola!

Quería saber el formato en que se entregarán los datos de cada una de las preguntas y en el cual deben ser retornados:
1. Los _half-floats_ se etregarán en binario? Si no es así, en cuál formato?
2. Se entregarán los datos en bytes/bits?

Gracias!

**Comment by jmwielandt** [comment]
Hola, el emulador entrega y recibe números enteros sin signo de 8 bits, que como estamos en un computador, ya están en binario.
Saludos!
