### ISSUE TITLE
T2 | Emulador

### ISSUE THREAD

**Issue by franciscobalmaceda** [IIC2343/Syllabus-2020-2#129]
Hola!
Al tratar de correr el código del ejemplo del rng, este me arroja error al buscar el path de la ISA, intente poner el ISA.ron en la misma carpeta que el código y colocando el PATH relativo y absoluto, aun así persistía el error. 
Aquí mi duda.  ¿Dónde debo colocar el archivo "ISA.ron" para que no me genere ese error, ejecutando tal cual viene el ejemplo de rng?

**Comment by jmwielandt** [comment]
Hola (respondiendo excepcionalmente un domingo)!

Si abres el .py, verás esto:

![image](https://user-images.githubusercontent.com/37153467/96368915-147f0000-112d-11eb-8772-cbac822f3fd2.png)

Ahí puedes cambiar el path de la ISA y te debería funcionar.

Saludos!

**Comment by franciscobalmaceda** [comment]
Gracias! mi error era que estaba usando mal el path relativo en vsc, ya que estaba abierto desde otro directorio
