### ISSUE TITLE
T1 | 1.c Considerar bit de signo para la "igualdad"

### ISSUE THREAD

**Issue by akrebs2** [IIC2343/Syllabus-2020-2#13]
Hola!

¿La igualdad de un número con su complemento considera el bit de signo de ambos? O se refiere a que sean iguales en todos los bits no-de-signo? El análisis cambia mucho con ese detalle.

Gracias!

**Comment by lothardp** [comment]
La igualdad de un número con su complemento considera la representación en binario completa. Recuerda que en la representación posicional de enteros con complemento a la base no hay bit de signo (piensa en un N > 2, no tiene sentido el concepto de "bit de signo").

**Comment by akrebs2** [comment]
Toda la razón, muchas gracias!!
