### ISSUE TITLE
Bug Emulador | Discrepancia de resultado al cambiar parámetro HIDE_PRINTS

### ISSUE THREAD

**Issue by vndiaz1** [IIC2343/Syllabus-2020-2#130]
**Descripción del bug**
No estoy seguro si es un bug del emulador o del ejemplo `main_rng.py`, pero cuando tengo el parámetro **HIDE_PRINTS=False**, el código utiliza aprox 10.000 ticks para llegar al resultado. Sin embargo, cuando **HIDE_PRINTS=True**, se necesitan más de 600.000 ticks para realizar el mismo código, o si no arroja que el límite de ticks se ha alcanzado.

**¿Cómo reproducirlo?**
Con el código de ejemplo subido al repo del curso y cambiando el parámetro `HIDE_PRINT` en la línea 144.
```
if __name__ == "__main__":
    # hay que tener buenos modales
    # y no correr código random cuando nos importan
    HIDE_PRINTS = True
    g = Config(limit_of_ticks=20000, auto_mode=True, hide_prints=HIDE_PRINTS)
    rng = Rng()
    c = AppCB()
    c.load_config(g)
    c.load_isa_from_file(PATH_A_LA_ISA)
    c.load_code("rng.asm")
    c.load_io_from_file("rng.ron", rng)
    c.print_program()
    c.run()
    if HIDE_PRINTS:
        # como ocultamos los prints, el estado final de la memoria 
        # no se mostrará al final de la ejecución
        c.print_memory()
    c.print_logs()
```

**Comportamiento esperado**
Me imagino que al ser solo un cambio gráfico de prints, no debería cambiar la lógica del código y debería tener la misma cantidad de ticks (o una cantidad similar).
**Sistema operativo, versión del emulador y otros**
- Windows 10
- EMU CB 2.0.4

**Comment by jmwielandt** [comment]
Hola (contestando excepcionalmente un domingo),

> cuando tengo el parámetro HIDE_PRINTS=False, el código utiliza aprox 10.000 ticks para llegar al resultado. Sin embargo, cuando HIDE_PRINTS=True, se necesitan más de 600.000 ticks para realizar el mismo código

Eso es normal, los prints toman bastante tiempo porque son llamados que tiene que hacer el programa al sistema operativo, pasarle los datos, etc. Un print a consola es una cadena bastante grande de llamados que involucra dispositivos I/O (pantalla), lo que penaliza el rendimiento.

Metí en mi backlog agregarle una configuración para que en el run haya una cierta espera entre cada instrucción y así los prints no pesan tanto.

Saludos!

**Comment by vndiaz1** [comment]
Gracias por la respuesta, pero me sigue quedando la duda de por qué cuando hay prints funciona con menos ticks y cuando los desactivo necesito más, ya que según lo que tu dices, se debería demorar más cuando hay prints, pero pasa lo contrario.

**Comment by jmwielandt** [comment]
Lo que se demora más es la ejecución de cada instrucción, y como hay un tiempo de espera hasta que el resultado esté "listo" en el emulador, alcanzas a ejecutar menos instrucciones cuando tienes los prints.

Pongo dibujito porque no es muy fácil de explicar en palabras:

![image](https://user-images.githubusercontent.com/37153467/96454861-d5b37d80-11f2-11eb-9cf0-19dc88ae9eb1.png)

**Comment by vndiaz1** [comment]
Ya perfecto, ahora entiendo! Muchas gracias por explicación!
