### ISSUE TITLE
T2 | P2.b hay cruza de funciones en x86?

### ISSUE THREAD

**Issue by StroveLight** [IIC2343/Syllabus-2020-2#131]
Hola, es posible que las declaraciones de las funciones estén entrecruzadas como el del siguiente ejemplo?
```
DEF f(a)
JMP later
DEF f(b)
JMP later2
later:
RET
later2:
RET
```
Además, puedo asumir que las funciones estarán "encaplsuladas" por un espacio antes y después de la funcion? (como en el ejemplo del enunciado)

**Comment by Arcoirisky** [comment]
¿a que te refieres con funciones entrecruzadas? 
Veo que defines f(a) y luego f(b) que llevan a dos labels RET distintos (incluso creo que deberías solo dejar uno y funcionará igual pero con menos codigo)

¿puedes explayarte sobre que las funciones estarán "encapsuladas"?

**Comment by StroveLight** [comment]
con entrecruzadas me refiero a si nos darán funciones de esa forma en el x86++ para convertir (es decir, que una función puede terminar despues de donde es declarada otra función).

Con encapsuladas, me refiero a que si cada funcion presente es declarada y finaliza y que no haya nada relacionada a otra funcion entre medio, y que haya a lo menos una linea sin código antes y después del código de la función

**Comment by movalle4** [comment]
Hola

En clases el profesor dijo que no van a haber funciones "entrecruzadas". Sin embargo, pueden haber subrutinas con varios "defs".

**Comment by DiegoEmilio01** [comment]
Hola! ¿A qué te refieres con varios defs? Los labels declarados en el cógido deben ser únicos. Saludos!

**Comment by jmwielandt** [comment]
@DiegoEmilio01 varios RET, no "defs"
Fue typo
Saludso
