### ISSUE TITLE
T2 | 3c ¿qué hacer?

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#132]
Hola!

No entiendo que se pide exactamente en esta pregunta. Entiendo qué es lo que hace un`Adress decoder`, pero no entiendo cuál es la diferencia con lo que ya se debe implementar en la 3a y 3b en el cual ya se debe hacer uno.

Gracias!

**Comment by jmwielandt** [comment]
Hola, en las preguntas 3a y 3b no se pide que haya un address decoder.
En ellas debes tener clases que simulen el comportamiento de los I/O en sí + la interfaz pedida para la comunicación por puertos en el caso del coprocesador matemático.

Luego en la pregunta 3c tienes que hacer el address decoder que tenga una referencia al coprocesador y a la cinta. El address decoder va a recibir la instrucción de leer o escribir en una dirección (+ el valor si es escribir) y ahí verá a qué dispositivo corresponde, si no corresponde a ninguno, etc. Luego en la 3d haces el código en assembly que maneje todo.

El tema del delay depende de ti, puede estar en el address decoder o en los componentes, pero recuerda que por puerto también tiene que existir.

En el ejemplo del material complementario está la interfaz del address decoder con comentarios.

Saludos!
