### ISSUE TITLE
T2 | 3d Formato input

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#133]
Hola!

Podrían dar un formato del input de la pregunta para así poder entender cuáles serán las limitaciones de esta? O explicitar cómo será el formato de este junto a un ejemplo?

Gracias!

**Comment by jmwielandt** [comment]
Hola,
No existe un formato de input. **Se espera que ustedes tomen las decisiones de diseño que necesiten y las especifiquen en su readme.** Mientras que cumplan con los requerimientos que se especifican en el enunciado (no son muchos) todo irá bien. Se revisará con lo que entreguen.

Tienes un ejemplo en la carpeta del material complementario. Lo hice yo y es de un I/O que genera números aleatorios cuando se lo piden, con posibilidad de setear una semilla inicial para la secuencia. Ojo que ahí está todo en un solo archivo .py y el enunciado pide que sean distintos.

Te recomiendo también mirar la wiki, en el apartado "Guía de uso" para ver cómo hacer el .ron con la descripción del dispositivo, etc.

Saludos!

**Comment by rihanuch** [comment]
Perfecto!

Sólo me queda una duda, cómo es que se entregarán datos de 16 bits dado que el computador básico soporta solo 8 bits?

Gracias!

**Comment by jmwielandt** [comment]
Lo más sencillo es agarrar tu número* de 16 bits y pasarle los 8 bits más y menos significativos en dos accesos distintos.
