### ISSUE TITLE
T2 | Pregunta 2.b Uso de args para off-set

### ISSUE THREAD

**Issue by fbarrientosj** [IIC2343/Syllabus-2020-2#134]
Hola! Tengo dos preguntas sobre la utilización de args. 

1. Es posible utilizar args para hacer direccionamiento por off-set? Algo así como MOV AX, [arg1 + 2]
2. Es posible utilizar args para hacer saltos en el código? Algo así como JMP arg1

Muchas gracias!

**Comment by felipearellanom** [comment]
Hola!

1. Este tipo de direccionamiento no existe en x86 tradicional así que tampoco exite en x86++
2. Esto tampoco existe en x86 por lo que no será posible en x86++

**Comment by jfpena1** [comment]
Hola respecto a esto mismo:
Es posible que en X86++ haya una instrucción del tipo:
MOV A, (arg1)  ?

gracias!

**Comment by movalle4** [comment]
Hola

No van a haber instrucciones de ese tipo (direccionamiento indirecto con los parámetros) en x86++

Suerte
