### ISSUE TITLE
T2 | 2.b Colisión de nombres de argumentos entre dos subrutinas

### ISSUE THREAD

**Issue by nhbravo** [IIC2343/Syllabus-2020-2#136]
Hola! Puede existir colisión entre los nombres de los argumentos de dos subrutinas en x86++?
Ejemplo:
`DEF funcion_1(arg1)`
`DEF funcion_2(arg1)`

**Comment by Arcoirisky** [comment]
puedes hacer eso y serían 2 arg1 "distintos"
