### ISSUE TITLE
Emulador | Problemas con el emulador

### ISSUE THREAD

**Issue by josejimenezp** [IIC2343/Syllabus-2020-2#137]
Hola, al actualizar a la versión 2.0.4 se me echó el emulador y me sale este error :( no es que esté usando una versión de python distinta (que no sea 3.7.x) ni tampoco que no haya instalado el nuevo whl. Gracias!

![image](https://user-images.githubusercontent.com/48298035/96522105-15a54f80-1249-11eb-8686-4a33a22b9457.png)

**Comment by jmwielandt** [comment]
Hola, esa interfaz ya no corre.
Mira la guía de uso que está en la wiki.
Saludos!

**Comment by josejimenezp** [comment]
> Hola, esa interfaz ya no corre.
> Mira la guía de uso que está en la wiki.
> Saludos!

Buena! La leí eso sí y sigo teniendo el problema de import emu_lib. Si me puedes ayudar con eso sería bacan :)

**Comment by jmwielandt** [comment]
Prueba el siguiente código:
```py
from emu_lib import AppCB, Config

print("Todo funcionando")
```

Sólo eso, dime qué te tira pls

**Comment by josejimenezp** [comment]
> Prueba el siguiente código:
> 
> ```python
> from emu_lib import AppCB, Config
> 
> print("Todo funcionando")
> ```
> 
> Sólo eso, dime qué te tira pls

Me funcionó perfect, y ahí caché que se me cambió solo la versión de python 🙄 pero ya lo logré! Lo último, el ejemplo del 'main_rng' me printea 

> Prueba el siguiente código:
> 
> ```python
> from emu_lib import AppCB, Config
> 
> print("Todo funcionando")
> ```
> 
> Sólo eso, dime qué te tira pls

Funcionó perfect y me di cuenta que entre tanta cosa ahora último se me había cambiado la versión de Python 🙄 pero ya lo logré! Lo último, el archivo de ejemplo de 'main_rng' me imprime las instrucciones y al final una especie de tabla, ¿eso debería hacer cierto? Muchas gracias!

**Comment by jmwielandt** [comment]
Sí, esa tabla te muestra el estado del computador en cada ciclo.
Saludos!
