### ISSUE TITLE
T2 | 3c Adress decoder: memoria reservada

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#138]
En el Adress Decoder se utilizara memoria reservada del computador básico, esta se toma en cuenta en el código asssembly, por ejemplo, si tengo reservada la dirección 0, no puede existir un label en la sección DATA ("var 12") con dirección 0 y se le asignara una dirección libre a esta label?

**Comment by jmwielandt** [comment]
No está restringido eso. Puedes tener:
```asm
DATA:
var1 5
var2 10
CODE:
; stuff
```
y en el archivo de alguno de tus dispositivos tener:
```ron
(
    name: "stuff",
    memory_mapped: [0, 1],
)
```
Con eso, el emulador mandará a tu I/O todos los accesos que quieras hacer a var1 y var2 y ambas direcciones de memoria serían inalcanzables en la práctica.
Saludos~

**Comment by mc-cari** [comment]
ok, gracias

**Comment by mc-cari** [comment]
Entonces no hay que retornar nada en el adress decoder cuando se accede a una dirección no mapeada en read_from() ?

**Comment by jmwielandt** [comment]
> Entonces no hay que retornar nada en el adress decoder cuando se accede a una dirección no mapeada en read_from() ?

El emulador sólo llamará al address decoder cuando intentes acceder a direcciones mapeadas en los archivos ron, así que no.

**Comment by mc-cari** [comment]
vale

**Comment by rakarachon** [comment]
> El emulador sólo llamará al address decoder cuando intentes acceder a direcciones mapeadas en los archivos ron, así que no.

O sea que las direcciones mapeadas en los archivos ron son direcciones del computador y no del dispositivo I/O? Sorry si es media tonta la pregunta, pero estoy un poco confundida con todo el tema de memory mapped I/O 😅

Gracias de antemano!

**Comment by movalle4** [comment]
Hola

Sí. Las direcciones mapeadas son direcciones del computador y no del dispositivo I/O.
