### ISSUE TITLE
T1 | 1b Bits de una palabra

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#14]
Hola! Esta bien considerar que cada palabra es de 2 bits?

**Comment by gnacrur** [comment]
Si no me equivoco, el profe dijo en clases que serían de 8 bits.

**Comment by fbarrientosj** [comment]
> Si no me equivoco, el profe dijo en clases que serían de 8 bits.

Eso está confirmado?

**Comment by Arcoirisky** [comment]
Confirmo lo que dice @gnacrur, son 8 bits a menos que se diga lo contrario
