### ISSUE TITLE
T2 | P3b Comportamiento cinta magnética

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#141]
Hola, no entiendo muy bien como es el comportamiento de la cinta magnética? Sería read-only o también debería ser capaz de escribir en el?

**Comment by movalle4** [comment]
Hola

No sería read-only. También es necesario poder escribir en la cinta. En la pregunta 3.d es necesario almacenar el resultado del cálculo despúes del último número almacenado cinta.

**Comment by Brocoleta** [comment]
Hola, es necesario poder acceder a un byte en especifico de la cinta?, me refiero a que segun el enunciado la cinta nos entregara un lista de numeros y despues tenemos que calcular el promedio, por lo que simplemente podriamos ir leyendo el byte siguiente todo el rato, nose si se entiende muy bien

**Comment by Brocoleta** [comment]
Tambien como se nos entregaran los numeros de la cinta? Como un array de assembly o como un atributo de la cinta?
