### ISSUE TITLE
Señales de control y bits de entrada

### ISSUE THREAD

**Issue by maxfreymo** [IIC2343/Syllabus-2020-2#142]
Revisando los apuntes me percaté que al control unit le entran solo 11 bits, pero tiene como salida 18 bits ¿Esto está mal y deberían entrar 18 bits o está bien? Si es que está bien, no entiendo el por qué. 

![imagen](https://user-images.githubusercontent.com/26142637/96608359-ab83bd80-12cf-11eb-941d-30fc4aaa56dd.png)

**Comment by movalle4** [comment]
Está bien en diagrama. La tarea que realiza la control unit es convertir los opcodes y señales de status que recibe a las señales de control que controlan el computador. Por ejemplo, la instrucción ADD A,B tiene el opcode 0000000 y la control unit tiene que mandarle la señal a la ALU de que debe sumar, mandarle la señal al registro A de que debe guardar el valor que sale de la alu, etc

**Comment by maxfreymo** [comment]
Oka, eso lo entiendo. Mi duda es por qué cuando se incorporó la señal de bit del direccionamiento (Sadd0) los bits que entraban al control unit pasaron de 6 (de los opcodes) a 7 (opcodes + Sadd0), pero no hubo cambios cuando se añadieron las demás señales de control (W, Lpc, Sdin, etc) ¿estás salen debido a las instrucciones?

**Comment by movalle4** [comment]
Fue necesario que los opcodes pasara de 6 a 7 bits porque aumentó demasiado el número de instrucciones. Con 6 bits, se puede tener hasta un máximo de 64 instrucciones. Con las nuevas instrucciones agregadas, ya no cabían más y por eso fue necesario agregar un nuevo bit a los opcodes. Con 7 bits se puede tener hasta 128 instrucciones. 

No sé si esto aclara tu duda

**Comment by maxfreymo** [comment]
Ah ya! Si eso aclaró una parte importante jaja gracias. Eso si aún me queda la duda de ¿desde dónde se ingresan estas señales? ¿son parte de las instrucciones? En las tablas de instrucciones que he visto siempre se colocan La, Lb, Sa0, Sb0, Sop2, Sop1, Sop0 ¿se deberían añadir estas otras señales de control  (W, Lpc, Sdin, etc)  a estas tablas? o ¿provienen de otro lado?

**Comment by movalle4** [comment]
En las tablas deberían estar esas señales de control (W, Lpc, Sdin, etc). En unos [apuntes](https://github.com/IIC2343/Syllabus-anteriores/blob/main/Apuntes%20(viejos)/5.5%20-%20Arquitectura%20del%20Computador%20B%C3%A1sico.pdf) de semestres anteriores se puede ver que sí están.

**Comment by maxfreymo** [comment]
Genial! Ahora si todo mucho más claro! Gracias
