### ISSUE TITLE
T2 | P2b Orden Saltos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#143]
Hola, puedo asumir que al hacer un salto, el label al que hace referencia se encuentra más abajo?

**Comment by VicenteMerino** [comment]
Este supuesto se fundamenta en lo siguiente: en la clase de hoy el profesor explicó que puede haber más de un RET en una subrutina y lo que al final nos diría si es un RET de la subrutina o no, son los labels. Ahora, bien esto funcionaría si primero encuentro un salto y después veo que el label efectivamente corresponde a ese salto (y si no, es porque estoy fuera de la SR), pero si se hace al revés no tengo una forma de saber si ese label pertenece a algo dentro o fuera de la subrutina y  ahí ya se debería tener que ver la estructura interna del código para determinarlo. No se si se entiende?

**Comment by movalle4** [comment]
Hola

No se puede asumir que el label al que saltas está más abajo. ¿Qué pasaría si quieres hacer un loop dentro de una subritina? Algo de este estilo:

```
subrutina:
[...]
loop:
[...]
JMP loop
[...]
```
