### ISSUE TITLE
T2 | 3. Memoria mapeada dispositivos I/O

### ISSUE THREAD

**Issue by rakarachon** [IIC2343/Syllabus-2020-2#144]
Hola! No me queda muy claro aún como definir que direcciones de un dispositivo de I/O estarán mapeadas en memoria, y a que direcciones de memoria del computador estarán mapeadas. Me refiero a si definir el mapeo es responsabilidad del Address Decoder o del dispositivo mismo? Pensaba que era el Address Decoder el encargado de "distribuir" la memoria del computador disponible para mapeo entre los dispositivos de I/O, pero viendo el formato RON de descripción de los dispositivos [acá](https://github.com/IIC2343/Syllabus-2020-2/wiki/Comunicaci%C3%B3n-con-I-O) me entró la duda, ya que se muestra un atributo memory_maped (definido como "Las direcciones de memoria mapeadas en una lista").

Muchas gracias de antemano!

**Comment by movalle4** [comment]
Hola

El mapeo a memoria es responsabilidad del Address Decoder.

En la documentación del emulador sale lo siguiente:

"**Comunicación mediante mapeo de memoria:**
Para el caso del mapeo de memoria, deben hacer una clase que sea un Address Decoder y esta tener las referencias a sus dispositivos y tener las interfaces que uds. definan convenientes internamente. El Address Decoder debe tener un método def read_from(self, direccion) -> int, que retorna un entero de 8 bits, y un método def write_into(self, direccion, valor). Internamente, ustedes tienen que definir cómo identificarán a qué dispositivo se corresponde cada dirección."

Espero que esto haya respondido tu pregunta

**Comment by rakarachon** [comment]
Perfect, muchas gracias!

**Comment by rakarachon** [comment]
Me entró otra duda ahora: las direcciones de memoria definidas en la descripción RON de un dispositivo I/O ¿a qué direcciones se refieren? ¿del computador o del dispositivo?

**Comment by movalle4** [comment]
Se refieren a las direcciones del computador. El address decoder debe tener los métodos read_from y write_into que lea y escriba en las direcciones del computador.

**Comment by rakarachon** [comment]
En ese caso, ¿puede ser que 2 dispositivos mapeen a una misma dirección? y si es así, ¿eso sería un problema? ¿o el address decoder debe ser capaz de manejar este caso, diferenciando cuando el valor almacenaso en dicha direccion pertenezca a uno u otro dispositivo?

**Comment by movalle4** [comment]
En teoría sí puedes mapear distintos dispositivos a la misma dirección de memoria usando el address decoder. Pero lo que generalmente se hace es que para cada dispositivo, se reservan direcciones de memoria en que solo ese dispositivo puede escribir. El adress decoder está encargado de estar vigilando estas direcciones de memoria mapeadas a los dispositivos, observando cuando se hagan cambios a estas direcciones para "avisarle" al dispositivo correspondiente.

**Comment by rakarachon** [comment]
Perfecto, ¿puedo asumir entonces que los dispositivos sabrán de antemano que direcciones están reservadas para ellos, y por lo tanto solo pondrán estas direcciones en sus descripciones RON?

**Comment by movalle4** [comment]
Al crear al archivo RON, tú debes decidir cuáles son las direcciones que serán mapeadas a cada dispositivo. Por ejemplo

´´´
(
    name: "dispositivo1",
    memory_mapped: [0, 1],
)
´´´

En este caso,  el dispositivo1 tiene mapeadas las direcciones de memoria 0 y 1. A cada dispositivo tienes que asignarle las direcciones de memoria que va a usar.

**Comment by rakarachon** [comment]
Perfecto, me quedó claro, muchas gracias!

**Comment by VicenteMerino** [comment]
@movalle4 Hola, algo que no me queda muy claro es como se usan esos valores desde la clase? Por ejemplo con los ports para pasar/obtener un valor por port, en la clase debía definir un metodo con el mismo nombre. Pero con el memory mapped no está muy claro, por ejemplo como puedo acceder a uno de estos valores desde la clase por ejemplo, o como se utiliza finalmente esta lista memory mapped?

**Comment by sehe4** [comment]
@movalle4 Hola, en el código base para el address decoder, uno de los metodos a implmentar es agregar_io:

def agregar_io(self, io, info):

Aquí que es info?

**Comment by VicenteMerino** [comment]
Tengo la misma duda que @sehe4

**Comment by jmwielandt** [comment]
> Aquí que es info?

@sehe4 @movalle4 cualquier información adicional que creas que necesitas para poder hacer la transformación entre direcciones de memoria y los dispositivos.
