### ISSUE TITLE
T2 | P3a 16 bits desde 8 bits desde el CB

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#145]
Hola, la forma en que pase un número de 16 bits al dispositivo queda a mi criterio verdad? Ya que los números que soporta el computador básico son de 8 bits.

**Comment by VicenteMerino** [comment]
Y respecto a este mismo punto, el paso de convertir desde uint a float lo debemos hacer nosotros?

**Comment by movalle4** [comment]
Hola

En la pregunta 3.a, debes pasarle al componente desde tu computador básico un entero de 8 bits. Este uint de 8 bits va a ser un número binario, y tu componente se debe encargar de convertirlo en un float de 16 bits y de hacer las operaciones matemáticas

Suerte.

**Comment by VicenteMerino** [comment]
Cuando se nos pide dividir dos binarios, vendría siendo solo la "parte entera" de la división? No es necesario considerar el resto?

**Comment by movalle4** [comment]
Los números que pasas al componente tienes que convertirlos a floats de 16 bits. Luego los tienes que dividir o multiplicar o sumar o restar. Tienes que hacer las operaciones con floats, no con enteros.

No se si eso aclara tu pregunta

**Comment by VicenteMerino** [comment]
Aun me quedan un par de dudas: si por ejemplo me pasan un numero n = 32, eso en binario es 00100000, entonces lo que tengo es reinterpretar ese número como 16 bits en formato float? Por ejemplo mi número ahora sería 0000000000100000, pero al hacer las operaciones de suma/resta/division/multiplicacion de este numero las debo hacer como si fuera un float en vez de un entero?

**Comment by movalle4** [comment]
Así es. Tienes que hacer las operaciones como si el número fuera un float. Vas a tener que sumar/restar/dividir/multiplicar un float de 16 bits con otro float de 16 bits.

**Comment by mc-cari** [comment]
Entonces no hay que pasar 2 bytes desde el computador para formar 16 bits en el coprocesador? creo que el profe lo había dicho hoy que era así, en 2 partes. Entonces al devolver el resultado hay que reinterpretar como un entero de 8 bits?

**Comment by movalle4** [comment]
Tienes razón. Respondí mal las preguntas anteriores.

Hay que pasar 2 bytes (16 bits) desde el computador al coprocesador. Estos 16 bits se tienen que interpretar como un float (de 16 bits). La idea es que puedan pasar los números desde la cinta magnetica (floats de 16 bits) al coprocesador para hacer los cálculos.

Perdón por las molestias causadas.

**Comment by mc-cari** [comment]
Dale, gracias por aclarar

**Comment by nhbravo** [comment]
Entonces, para el armado de mi componente, puedo _asumir_ que los valores que recibo en mis puertos vienen ya como 16 bits? Dado que vienen de la cinta magnética van de 16 bits

O me van a llegar 16 bits por cada uno de los números que me van a llegar?

Sigo muy perdido con el flujo de los números

**Comment by VicenteMerino** [comment]
@nhbravo Según yo no puedes asumir eso, porque también deber ser soportado por el computador básico y ahí los numeros son uint8

**Comment by jmwielandt** [comment]
@nhbravo mira la issue #151 ahí hice dibujitos y todo.
Buenas noches

**Comment by VicenteMerino** [comment]
@movalle4 Al final hay que pasar 2 bytes desde el computador básico o como? Que según lo que me respondió @jmwielandt en la issue #151 se dio a entender que se pasan solo 8 bits desde el computador básico y esas son reinterpretados como uno de 16 y no recomponer cada número desde 2 palabras de 8 bits que lleguen desde el computador básico? Además mirando la parte d del enunciado que dice:

> Escriba un programa en el assembly del computador básico, que lea el contenido de la cinta magnética, interprete
el contenido como números de punto flotante de 16 bits, calcule el promedio de estos y finalmente lo almacene a
continuación del último número almacenado

Me da a entender que no debo "ir juntando" de a dos palabras para cada operando del coprocesador, sino que simplemente leo un byte de la cinta magnética, se lo paso al coprocesador y ese byte en el coprocesador se reinterpreta como float-16, no se si estoy mal? Sigo un poco perdido con este punto, espero me lo podrías aclarar un poco.

Saludos,

**Comment by VicenteMerino** [comment]
Creo que me respondí un poco solo, pero quiero que si pueden me confirmen: Desde la cinta magnética voy a tener almacenado en una lista floats16, luego debo pasarlos al computador básico (de alguna forma, por partes por ejemplo de a 8 en 8 bits), luego esos los paso del computador básico al coprocesador  (por partes, nuevamente y los recompongo en el coprocesador), luego hago lo mismo hacia el otro lado (para guardar), pero en definitiva siempre debo seguir esa lógica de ir recomponiendo/dividiendo los números entre el Computador Básico - Componente?

**Comment by jmwielandt** [comment]
> Creo que me respondí un poco solo, pero me gustaría que si pueden me confirmen: Desde la cinta magnética voy a tener almacenado en una lista floats16, luego debo pasarlos al computador básico (de alguna forma, por partes por ejemplo de a 8 en 8 bits), luego esos los paso del computador básico al coprocesador (por partes, nuevamente y los recompongo en el coprocesador), luego hago lo mismo hacia el otro lado (para guardar), pero en definitiva siempre debo seguir esa lógica de ir recomponiendo/dividiendo los números entre el Computador Básico - Componente?

Exacto
