### ISSUE TITLE
Instrucciones de 2 ciclos

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#147]
Hola. Me preguntaba como era que el computador básico maneja instrucciones de 2 ciclos. Esto porque al aumentar el PC se pasa a la siguiente instrucción, y cada instruccion dura un ciclo. Esto entonces lo maneja el software, o el hardware? Es decir, la instrucción se traduce en 2 instrucciones, o el hardware hace un ciclo extra sin cambiar el program counter?

**Comment by movalle4** [comment]
Hola

La manera en que el computador trata con instrucciones de dos ciclos es convertirla a dos instrucciones (una después de la otra). Por ejemplo, la instrucción POP A de 2 ciclos tiene 2 opcodes, 0111111 y 1000000. La primera instrucción aumenta el Stack Counter y la segunda instrucción manda la señal de Load A. 

Saludos
