### ISSUE TITLE
T2 | P 2b label main

### ISSUE THREAD

**Issue by imunoz3** [IIC2343/Syllabus-2020-2#148]
Hola! Vi en una issue que preguntaron sobre el RET del label main. Podemos asumir que los códigos de entrada siempre vendrán con un label main y que no será definido de la forma DEF main?

**Comment by movalle4** [comment]
Hola

El label podría no llamarse "main". Se llega a ese label porque al principio de todo hay un JMP main, pero podría llamarse de otro modo.

**Comment by imunoz3** [comment]
Entonces ese JMP de al principio siempre va a estar?

**Comment by movalle4** [comment]
No puedes asumir que siempre va a haber un JMP al principio.

Lo lamento

**Comment by DiegoEmilio01** [comment]
¿Pero puede empezar el código definiendo una función? Creo que eso no tiene mucho sentido, ahí se perdería toda capacidad de decidir lo que continúa a ese ```DEF``` es parte de la función debido a los loops.
