### ISSUE TITLE
T1 | 2.a Alcance de pregunta

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#15]
Hola!

En la pregunta 2 a) cuando indican
> ...que simule el funcionamiento de una máquina de Turing.

Hasta qué grado hay que hacerlo? Pregunto esto porque con una máquina de Turing uno puede definir operaciones arbitrarias (digamos, sumar símbolos y que eso entregue una integral (es por poner un ejemplo extremo nomás))

En base a lo anterior me entra la duda de si finalmente nos piden eso o replicar una máquina de Turing en que, por ejemplo, como lo hace una verdadera, mueva su lector hacia la derecha/izquierda. En general mi duda apunta a qué es lo que se espera que nuestra máquina análoga sea capaz de hacer en **específico**.

Gracias desde ya! 😬

**Comment by Arcoirisky** [comment]
Hola~

Te estás complicando más de la cuenta, lo que se busca es la "maquina de turing" que se da en la definición, es pocas palabras, que sea capaz de leer un símbolo y hacer algo. Como dices, que sea capaz de mover el lector hacia la derecha/izquierda, actualizar el estado con una palabra, etc. 

No debes preocuparte del programa que podría llegar a tener la máquina, eso es pega del programador. 

¿Se entiende un poco mejor?

**Comment by DiegoEmilio01** [comment]
¿Debe poder permanecer en el mismo lugar? En la descripción informal dice que alguna máquinas incluyen esta instrucción. Gracias de antemano.

**Comment by frvalenzuela** [comment]
Hola @DiegoEmilio01 !

Perdón la tardanza en la respuesta, pero sí ! Permanecer en el mismo lugar o solo moverse a la izquierda y derecha son máquinas de Turing equivalentes, así que lo que asumes estará correcto.

Saludos!
