### ISSUE TITLE
T2 | Librerías externas

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#151]
Hola, podemos usar librerías externas para facilitar las operaciones con números binarios? Que aun no se que es lo que se espera, que cuando leamos los números, los pasemos a binarios y los operemos entre ellos? Por ejemplo sumar 11110000... con 11001100...? No creo que esta sea la solución la verdad, siento que me estoy yendo muy "en volá" en ese sentido (además que cosas como división de binarios ni siquiera las vimos) Así que no se si se puede usar cosas externas para facilitar el manejo de bits, ya que por ejemplo si reinterpretamos un numero de 16bits, python a fin de cuentas lo reinterpretará como uno de 64 y tendremos problemas en ese sentido. No se si me pueden guiar un poco? He estado todo el día en esta pregunta :(

**Comment by jmwielandt** [comment]
Hola, mira el siguiente diagrama, abajo está la explicación
![diagrama p3](https://user-images.githubusercontent.com/37153467/96671077-66937180-1337-11eb-9e1e-3ebd20f7adfa.png)
De izquierda a derecha están: la cinta magnética, el computador básico y el coprocesador matemático. El computador básico sólo puede entregar y recibir datos de 8 bits (una cadena de bits).

La cinta magnética tiene guardada una lista de números de punto flotante de 16 bits que se corresponden al tipo de dato binary16 de la convención IEEE754. ¿El formato? Lo decides tú.

Luego, el computador básico va a ir leyendo el contenido de la cinta como dispositivo I/O y eventualmente, le va a pasar números de la cinta al coprocesador matemático que tiene que terminar reconstruyendo los floats de 16 bits que estaban en la cinta y operar con ellos según le diga el computador básico. También tiene que poder pasarle estos números al computador básico. ¿El formato? Lo decides tú.

https://en.wikipedia.org/wiki/Half-precision_floating-point_format#IEEE_754_half-precision_binary_floating-point_format:_binary16

![image](https://user-images.githubusercontent.com/37153467/96671693-cc342d80-1338-11eb-84fa-699d94b5e6d8.png)

Finalmente, tienes que poder usar todo eso para calcular el promedio de los números que están en la cinta. ¿Dónde lo guardas? Lo decides tú. ¿Necesitas guardar más cosas en la cinta? Es decisión tuya. ¿Esta cosa debería ser por puerto o mapeado a memoria? Lo decides tú. ¿Qué puertos/direcciones de memoria debería usar para mis I/O? Lo decides tú. Etc.

![image](https://user-images.githubusercontent.com/37153467/96671898-511f4700-1339-11eb-986e-487835f78603.png)


Mientras cumplas las restricciones del enunciado (y no uses código de internet que te resuelva la tarea), todo estará bien. Recuerda que se pide un readme donde especifiques este tipo de decisiones y expliques lo que hace tu programa.

<hr>

Puedes usar librerías para operar con los floats de 16 bits.

Espero que haya quedado claro ahora u.u
Saludos!

**Comment by VicenteMerino** [comment]
Buenísimo, me quedó mucho más claro. Gracias!!
