### ISSUE TITLE
T2 | P3 adress decoder

### ISSUE THREAD

**Issue by franciscobalmaceda** [IIC2343/Syllabus-2020-2#152]
Leyendo la documentacion del emulador veo que para construir un Adress Decoder, se nececitan 2 metodos, write_into(dir,valor) y read_from(dir)->int
lo que no me queda claro es como el emulador va a llamar a estos metodos, si por ejemplo tengo mapeadas las direcciones [0,1,2] con un dispositivo y en mi assembly tengo una instruccion mov a,(0) esto lo va a tomar el adress decoder y pasarlo por cual de los 2 metodos?? 
En lo que he probado, una instruccion mov a,(0) esta entrando al metodo read_from() pero no entiendo como entrar a write_into()

**Comment by jmwielandt** [comment]
hola, si estás leyendo una dirección de memoria (mov reg,(dir)), vas a pasar por el read_from. En cambio si intentas escribir en una dirección de memoria (mov (dir),reg), vas a pasar por el write_into.

Ojo que eso incluye todos los modos de direccionamiento: directo, indirecto y las operaciones que involucren al stack.

Saludos!

**Comment by Bneya** [comment]
Hola @jmwielandt, no entiendo bien como entra el adress decoder en todo el ejercicio en general. Por ejemplo en la letra **a**, cuando hay que hacer el coprocesador, piden que sea controlado a través de memory mapped IO y port IO, pero en el ejemplo de los números random, se usa únicamente port IO (creo). ¿Necesito hacer entonces que ese dispositivo funcione usando las 2 formas a la vez o que permita acceder a él con cualquiera de las 2 formas?

Y lo otro es que estoy medio perdido en qué hace exactamente un adress decoder. Si yo hago **mov a (0)**, ¿eso se comunica directamente con el dispositivo IO si lo dejé mapeado en su .RON o pasa por el adress decoder primero? ¿o este adress decoder es algo tipo "necesario cuando tengo varios dispositivos, pero no cuando tengo 1 solo" o "útil, pero no necesario"?
Si necesito el adress decoder para la parte del **a** de que funciones con memory mapped IO, ¿entonces no puedo hacer esa parte antes de hacer el adress decoder de la c? 

Estoy muy perdido, agradecería mucho si me pudieras orientas con esas dudas. Muchas gracias

**Comment by VicenteMerino** [comment]
Estoy medio parecido a @Bneya así que sería ideal un poco de orientación sobre esto.

**Comment by franciscobalmaceda** [comment]
> hola, si estás leyendo una dirección de memoria (mov reg,(dir)), vas a pasar por el read_from. En cambio si intentas escribir en una dirección de memoria (mov (dir),reg), vas a pasar por el write_into.
> 
> Ojo que eso incluye todos los modos de direccionamiento: directo, indirecto y las operaciones que involucren al stack.
> 
> Saludos!

Ya entiendo, era como lo esperaba. resulta que cuando llamo (mov (dir), reg) entiendo que deberia entonces ejecutarse write_into(dir, reg)?? especificamente, tengo la direccion 2 mapeada, y cuando hago (mov(2),a) no esta entrando al write_into() (puse unos prints para determinar si entraba o no, corriendo el emulador apretando enter)

**Comment by jmwielandt** [comment]
@Bneya (y @VicenteMerino )

Letra A: creas una clase "coprocesador matemático" que simule ese componente. Tiene que comunicarse por puertos y por memory mapped.

Letra B: creas la clase "cinta magnética", que simule ese componente. Tiene que comunicarse por  memory mapped.

Letra C: creas la clase "address decoder" que tenga la interfaz que sale en los apuntes y la wiki. Tiene que tener los métodos "read_from" y "write_into". También recomiendo tener un método para pasarle dispositivos ya instanciados, porque si uno tiene los dos tipos de comunicación, tienes que pasarle la misma instancia de la clase a tu address decoder y a mi emulador (como "callback" en el `load_isa_from_file`).

Letra D: escribes el código en assembly que haga todo lo pedido.

Tienes que cumplir con las cosas que pide el enunciado. Por ejemplo, la cinta tiene capacidad para 1024 bytes y el coprocesador debe tener los dos tipos de comunicación.

<hr>

Si intentas leer o escribir una dirección de memoria a la que está mapeado un I/O, eso va a llegar al address decoder y tú tienes que determinar a qué dispositivo corresponde y usar los atributos o métodos que definas y creas convenientes.

En un hardware real, el address decoder va a ser además el que decida a partir de una dirección de memoria dada, si tiene que ir a la memoria principal o a un I/O, a cuál y a qué parte de ese.

<hr>

¿Cómo hacer andar el emulador?

Está compilado como una librería de python, así que lo primero que tienes que hacer es importarlo e instanciar las cosas que vayas a usar (mira la guía de uso de la wiki).

Sin ISA, no funciona, así que le tienes que pasar la ISA. Esto tiene que ser ANTES de pasarle el programa o no te va a reconocer ninguna instrucción.

Sobre los .ron, estos le dan la info al emulador de qué dispositivo mapea qué direcciones y usa qué puertos. En el caso de los puertos, le dice también a qué método tiene que llamar. Si tiene comunicación por puertos, adicionalmente tienes que pasarle a la función la instancia de tu dispositivo I/O que implemente los métodos que le prometiste en el .ron.

También tienes que pasarle el address decoder al emulador en caso de que uses memory mapped (declarado en algún .ron de algún dispositivo) o no va a funcionar.

Etc. Mira el ejemplo subido, la wiki y el nuevo ejemplo que subí (ejemplo dummy). Ahí están los dos tipos de comunicación en un mismo dispositivo, pero 

<hr>

@franciscobalmaceda mira el nuevo ejemplo que subí. Ahí puedes ver que sí entra en los dos casos al address decoder.

**Comment by Bneya** [comment]
Gracias, creo que ahora entendí bastante más lo que tengo que hacer.
