### ISSUE TITLE
T2 |  P2 b CALL o DEF sin argumentos

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#153]
Hola. En la convención x86++ no se especifica qué hacer en caso de que la función no lleve argumentos. será de la forma ```DEF func()``` o de la forma ```DEF func```? Idem para ```CALL```

**Comment by jmwielandt** [comment]
Hola, eso lo comentó el profe en la clase del martes cuando se lo preguntaron.
Saludos!

**Comment by JJJGGGG** [comment]
Hola, no pude ir a la clase del martes, y he estado estudiando de los apuntes. Si no es mucha molestia, qué es lo que dijo el profe en la clase?

**Comment by halobel** [comment]
Hola, mencioné hartas cosas al respecto en clases, así que por favor revisa el video para que te hagas una mejor idea.
Saludos!

**Comment by Bneya** [comment]
Hola, una instrucción del tipo RET 0 tiene sentido o es algo ilegal en x86?

**Comment by jmwielandt** [comment]
Hola, en x86 ret no tiene parámetros
saludos
@Bneya 
aquí tienen la isa completa por cierto, en el apunte de i/o sale el link de la página https://jbwyatt.com/253/emu/8086_instruction_set.html

**Comment by Bneya** [comment]
Hola, @jmwielandt, me refería a este ret del x86 del ejemplo del enunciado. El 2 no es un "parámetro" o recibe otro nombre?
![image](https://user-images.githubusercontent.com/30673797/97362220-73f0b480-187f-11eb-8c7f-20b52e37d304.png)

**Comment by jmwielandt** [comment]
@Bneya hola de nuevo, sorry, leí mal
Ret puede recibir un número par como parámetro, que le dice cuántas palabras debe sacar del stack al retornar. Tiene que ver con stdcall
Saludos!
