### ISSUE TITLE
T2 | P2b Stdcall-arreglos

### ISSUE THREAD

**Issue by vchadwick** [IIC2343/Syllabus-2020-2#154]
Hola, si nos dan como dato un arreglo arr:
arr  dw  2, 3, 4, 5, 6

¿La instruccion PUSH arr  agregará al stack todo el arreglo, o solamente el primer dato?

**Comment by aaguilarg** [comment]
La variable arr guardaría solo el primer dato, por lo que solo ese se agregaría al stack luego del PUSH

**Comment by vchadwick** [comment]
@aaguilarg perfecto!
Ahora bien, cuando trabajamos con stdcall y estamos en presencia de un arreglo! ¿Podemos asumir que siempre se almacenará como parámetro la direccion de memoria del arreglo (LEA) en vez de cada uno de los elementos (PUSH)?

**Comment by aaguilarg** [comment]
No puedes asumir eso, ya que uno es para pasar argumentos por valor y otros por referencia, entonces cada caso es distinto dependiendo de lo que se quiera hacer.

Saludos y éxito!
