### ISSUE TITLE
T2 | Cantidad de números de la cinta magnética

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#159]
Hola, la máxima cantidad de números en la cinta magnética es 512, y se pide especificar la cantidad de números en el programa, por el enunciado, pero en assembly no se pude guardar un número tan grande, por lo que no podría especificar directamente en el programa cuantos tengo que tomar en cuenta, se tiene que hacer de otra forma?

**Comment by aaguilarg** [comment]
Hola @mc-cari !
Parte de lo que se busca es que ustedes puedan determinar cómo hacer eso pese a las limitaciones que tienen.

**Comment by mc-cari** [comment]
Dale, gracias
