### ISSUE TITLE
T1 P1 b Duda sobre tipo guardado en espacio o cantidad de bits.

### ISSUE THREAD

**Issue by sjkinast** [IIC2343/Syllabus-2020-2#16]
Hola! podrían dar más información de que es lo que se guarda en cada espacio de memoria, por ejemplo cuantos bits hay en cada espacio o en que representación se guarda el numero en memoria ( binario, hexadecimal, etc).

**Comment by Arcoirisky** [comment]
Sobre la cantidad de bits siempre se debe asumir 8bits a menos que se diga lo contrario. 
¿Podrías explicarme un poco más sobre a qué te refieres con "qué se guarda en cada espacio de memoria"? No entiendo a qué va esa pregunta.
