### ISSUE TITLE
T2 | Supuesto P3 -> Suma valores cinta magnética

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#160]
~~Hola, puedo asumir que la suma simple de los valores de la cinta no superará los 16 bits (no habrá overflow?). Esto dado, que de otra forma no podría entregar el promedio solo con los componentes que tengo. Gracias~~

Creo que me di cuenta que este supuesto no es necesario, pero si debo suponer que los valores no contendrán a la representación de 16 bits de +-Infinito y de NaN?

**Comment by VicenteMerino** [comment]
Además que pasa si tengo overflow de dos números flotantes? Por ejemplo al sumar las representaciones de 16 bits de -4200.0 y de -62750.0 se genera -inf. Aquí ya entra en juego un poco la pregunta tachada, puedo asumir que me darán o generar en la cinta magnética alguna combinación de números, que yo sepa a priori que su suma no causará problemas?

**Comment by aaguilarg** [comment]
Hola,
Tienes que ser capaz de manejar estos casos. Las decisiones de diseño quedan por tu cuenta siempre y cuando esten justificadas

**Comment by VicenteMerino** [comment]
@aaguilarg pregunté lo mismo al profe hoy y me dijo que era un supuesto válido. Podrías confirmar esto para despejar dudas?

**Comment by aaguilarg** [comment]
Tienes toda la razón, mis disculpas. Hablé con el profesor y efectivamente es un supuesto válido.
