### ISSUE TITLE
T2 | El emulador se comporta extraño cuando hago IN

### ISSUE THREAD

**Issue by sehe4** [IIC2343/Syllabus-2020-2#161]
Al querer guardar en memoria el valor 176 haciendo primero IN el emulador me lo carga y guarda como -80, y me gustaría saber porque me pasa eso, ya que el 176 si tiene representación binaria de 8 bits. Además de que con otros valores si funciona bien, por ej cuando cargo el valor 88 o otros menores en los registros para guardarlos en memoria funciona perfecto.
De hecho al activar la opción para debuggear imprimo en pantalla RETORNANDO RESULTADO DESDE AL: 176, pero en memoria se guarda -80 no así con los otros valores que mencioné, donde se guarda el valor que me aparece en el mensaje de debuggeo.

**Comment by jmwielandt** [comment]
Hola, mira la [wiki](https://github.com/IIC2343/Syllabus-2020-2/wiki/Antes-de-empezar#manejo-interno-de-los-datos) pls.
