### ISSUE TITLE
Bug Emulador Wiki

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2343/Syllabus-2020-2#163]
Hola, en la [descripción](https://github.com/IIC2343/Syllabus-2020-2/wiki/Gu%C3%ADa-de-uso) de la clase ```Config``` , más precisamente en la Tabla de opciones de configuración, creo el tipo de dato de ```limit_number_of_ticks``` y ```limit_of_ticks``` están intercambiados. Aprovecho de preguntar ¿qué tipo de dato es ```u64```?
Saludos y muchas gracias de antemano.

**Comment by VicenteMerino** [comment]
No soy ayudante pero u64 = unsigned int de 64 bits (creo), sobre lo otro no sabría decirte, pero a mi me funcionó siguiendo el ejemplo.

**Comment by jmwielandt** [comment]
Ya está corregido. Estaban intercambiados los valores de la columna de ejemplos, no los tipos de datos.
Como dice Vicente, u64 -> unsigned int de 64 bits. Me parece mucho más cómoda la nomenclatura de rust que la de C, donde sería unsigned long int o uint64_t.

https://doc.rust-lang.org/std/primitive.u64.html

**Comment by DiegoEmilio01** [comment]
Graciass a ambos. Veré que onda, la verdad no conozco RUST y no he dado ramos en los que se trabaje con C :sweat:

**Comment by jmwielandt** [comment]
@DiegoEmilio01 tranqui, sólo ten presente que los valores posibles van de 0 a 2^64 - 1, si necesitas más ticks creo que se puede asegurar que es porque estás haciendo algo mal u.u
