### ISSUE TITLE
Bug Emulador | Programa se cae si el puerto no retorna nada

### ISSUE THREAD

**Issue by Oisangui** [IIC2343/Syllabus-2020-2#164]
**Descripción del bug**
El programa se cae cuando el puerto especificado no retorna nada.

```
thread '<unnamed>' panicked at 'TypeError: 'NoneType' object cannot be interpreted as an integer', src/lib.rs:97:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "emu_example.py", line 21, in <module>
    c.run()
pyo3_runtime.PanicException: TypeError: 'NoneType' object cannot be interpreted as an integer
```

**¿Cómo reproducirlo?**

 ```python
def status_port(self):
    print('I am provoking an unhandled exception')
```

```javascript
(
    name: "Bug Generator",
    ports: {
        1: "status_port",         // sólo in
    }
)
```

```nasm
bug:
IN 1
```

**Comportamiento esperado**
Que no ocurra nada, o que el emulador termine sin errores indicando que el puerto indicado está retornando algo que no es un entero.

**Sistema operativo, versión del emulador y otros**
- Ubuntu 18.04 LTS
- Emulador 2.0.4

**Comment by jmwielandt** [comment]
Hola, eso es normal que pase. Las excepciones internas están manejadas, pero paniquea cuando uds hacen algo mal.
Saludos!
