### ISSUE TITLE
T2 | P3 delays

### ISSUE THREAD

**Issue by sjdiaz1** [IIC2343/Syllabus-2020-2#165]
En el enuciado cuando piden simular un delay aleatorio por cada llamada, ¿se espera que programemos un delay simple (es decir, que el computador quede "congelado" esperando al dispositivo) o un delay interno dentro del dispositivo que permita al computador ejecutar otros comandos mientras el dispositivo se "demora" en lo que está haciendo (es decir, que el computador no quede "congelado" esperando)?
Gracias :)

**Comment by jmwielandt** [comment]
Lo segundo, tal como en el ejemplo del rng.

**Comment by sjdiaz1** [comment]
Perfecto, gracias

**Comment by DiegoEmilio01** [comment]
Hola, ¿que tipo de instrucciones deben tener un delay? En el caso de la calculadora, tenemos cálculos, leer y escribir.
Saludos y gracias de antemano.
