### ISSUE TITLE
T2 | P3 Uso de librerías de threading

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#166]
Hola. Para lograr una mejor simulación de los componentes de IO, quería saber si podía usar las siguientes librerías:
* [threading](https://docs.python.org/3/library/threading.html) (Thread, Lock, Timer, Event) para que los componentes funcionen asíncronamente
* [queue](https://docs.python.org/3/library/queue.html) (Queue) para facilitar la comunicación entre los threads

Se que no es necesario, pero me pareció interesante y estoy dispuesto a hacer algo más de trabajo para lograrlo.

EDIT: agregué la clase Event a mi petición

**Comment by jmwielandt** [comment]
Hmmmmmm ten en mente que los componentes (cina y coprocesador) no se comunican directamente entre sí, sino que ambos son consumidos por el emulador.
Ten cuidado con los data races, dead locks y esas cosas, pero si cumples con que haya el delay está bien.
Fíjate en como en los ejemplos actualizo los estados en los comandos apenas me llaman, pero luego dejo programadas las nuevas actualizaciones de cosas, incluyendo futuros estados (¿por qué?).

**Comment by JJJGGGG** [comment]
Sobre los deadlocks etc, no te preocupes, lo tengo todo bajo control (ya lo testeé y funciona)
Sobre la actualización de estado: justamente la idea que tenía era que se actualizara el estado automáticamente y no cada vez que se hiciera una request. Es un pequeño cambio pero me parece que es más cercano al IO en la vida real (o no?)
