### ISSUE TITLE
Comportamiento de IO en la vida real

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#167]
Hola! Me preguntaba si un IO de la vida real puede recibir instrucciones mientras está ocupado resolviendo algo (dejandolo en una cola de instrucciones) o si simplemente las ignora. O depende de qué IO estemos hablando?

Gracias!

**Comment by jmwielandt** [comment]
Depende del controlador del I/O. Habrá quienes te ignoren y otros que simplemente fallen catastróficamente (desde tu punto de vista) porque les cambiaste los datos que estaban usando entonces en vez de meter X en el disco, meten la mitad de X y la mitad de Y (por ejemplo).
