### ISSUE TITLE
T2 | P3 Modularización, varios archivos .py

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#168]
Hola, está permitido hacer varios archivos .py? Es sólo para que sea más fácil de leer el código, si no va a ser más dificil de corregir. Además, al estar en un .zip se puede estructurar más organizadamente todos los archivos.

Por ejemplo, podría poner clases compartidas en distintos archivos .py, el Address Decoder en otro, y las respuestas cada una en su archivo .py

Gracias!

**Comment by Arcoirisky** [comment]
No debería de haber problemas mientras tengas lo que se pide en el enunciado y expliques cómo funciona en el Readme 

![5110D513-90E3-4BDB-AC82-7D2F4E710B79](https://user-images.githubusercontent.com/26121402/97043302-a3828280-1548-11eb-8d45-e6bab671754e.jpeg)

**Comment by JJJGGGG** [comment]
Perfecto, me traía dudas porque justamente dice "1 archivo por IO" y no se especifica más
