### ISSUE TITLE
T2 | P3 AddressDecoder agregar_io

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#169]
Hola. En la interfaz de AdressDecoder hay un método que se llama ```agregar_io```. Cito:
```py
    def agregar_io(self, io, info):
        """ 
            Dado que un mismo I/O se puede comunicar por puertos y mapeo de
            memoria "a la vez", entonces necesitamos una forma de instanciarlos
            fuera del address decoder y pasarlo luego a este, mientras luego le
            pasamos la referencia al AppCB del mismo objeto que representa nuestro
            dispositivo I/O y así el estado queda compartido
            
            ¿no son maravillosos los punteros? ;D
        """
        pass

```
Mi problema es que no se especifica de qué tipo son o qué contienen ```io``` e ```info```, si alguien pudiera aclararmelo estaría muy agradecido. Me complica porque necesito poder acceder a qué puertos tengo para después poder mapearlos a las funciones determinadas de los dispositivos determinados, y no sé de donde acceder a ellos.

Otra cosa es: debo registrar los dispositivos directamente en el AddressDecoder, o de eso se encarga el emulador?

Gracias

**Comment by jmwielandt** [comment]
io debería ser el objeto de tu dispositivo. Le tienes que pasar la misma instancia al emulador.
info es cualquier cosa extra que necesites para hacer el mapeo.

Tú se los tienes que agregar.

Saludos

**Comment by Bneya** [comment]
Hola, es estrictamente necesario que exista un método para cargar los dispositivos IO de esta forma o puedo, por ejemplo, pasárselos al constructor del AdrressDecoder?
