### ISSUE TITLE
T1 | Complejidad / Tiempo de ejecución

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#17]
Hola, hay algún tiempo de ejecución límite con el cual se probará los programas?

**Comment by Arcoirisky** [comment]
Mientras estén en un rango razonable de tiempo no debería de haber problemas. 
Por ejemplo, si tu programa tarda minutos en un problema, algo no puede estar andando bien u-u

**Comment by VicenteMerino** [comment]
Hola, esto es válido también para la 3? Ya que la velocidad de ejecución es súper lenta por default, le cambié la velocidad de 1000 a 10 ms, ya que tomaba 721 ticks en terminar. Supongo que esta cantidad es normal para un programa.

**Comment by Sebarraza** [comment]
Estaba viendo el codigo del emulador Y en el parche 1.01 el maximo the ticks que considera es 30000 ticks
Yo tomaria esto como maximo de complejidad (no soy ayudante)
Literalmente dice `MAX_TICKS: int = 30_000  # no debería demorarse más... creo`

**Comment by jmwielandt** [comment]
Hola,

Sería realmente raro que se demoren más de 30k ticks, pero por si acaso el límite del emulador es de 65_535, ya que el contador es un u16.
Respecto al tiempo de ejecución de las preguntas de assembly no se preocupen, tenemos mecanismos para correr todas las tareas en lote y aplicarles los tests minentras cumplan el formato que les detallo en la issue #32 . Gracias al límite de ticks no es necesario que le pongamos un timeout.

**Comment by rihanuch** [comment]
Hola @jmwielandt !

Creo que deberían considerar modificar el número máximo de `ticks` máximos (dentro de lo posible), ya que hay soluciones que son de tipo O(n^3) (no diré el nombre del algoritmo en específico por motivos de integridad académica)

Lo anterior es un problema, ya que si por ejemplo consideramos el caso límite de una matriz de 12 elementos, serían (12*12)^3 iteraciones y eso son un total de 2.985.984 iteraciones **solo parar recorrer todos los elementos** de la matriz acorde al algoritmo, es decir, no se considera ninguna otra operación en esa matriz

Saludos!

**Comment by jmwielandt** [comment]
Hola, si no me equivoco ese método toma n = número de nodos, no n = número de valores en la matriz.
Entonces sería 12^3 = 1728 "pasos".

**Comment by rihanuch** [comment]
De igual manera, sigue en pie lo que comento de que no se habla de eficiencia o número máximo de ticks :eyes:

**Comment by jmwielandt** [comment]
@rihanuch 
_Cambiado en la release 1.0.2, ahora tiene capacidad de un u64._
