### ISSUE TITLE
T2 | P2.b forma de funciones (uso de ':')

### ISSUE THREAD

**Issue by StroveLight** [IIC2343/Syllabus-2020-2#171]
Hola!

en el enunciado se dice que las funciones son de la siguiente sintaxis:
![image](https://user-images.githubusercontent.com/48263952/97097685-407d1280-1652-11eb-8281-83a4567e4634.png)

Sin embargo, en el ejemplo viene de la forma
![image](https://user-images.githubusercontent.com/48263952/97097688-4f63c500-1652-11eb-9b32-d5261f86483f.png)
Por lo que está esta diferencia de ':'

Cual de las dos formas es la que se usará en la evaluación?
Asumo que el ejemplo tiene el ':' de más?

**Comment by jmwielandt** [comment]
Hola, es un typo. Los ":" no van.
Saludos!~
