### ISSUE TITLE
T2 | EMULADOR: print de ticks

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#172]
Hola! Hay alguna forma de "desactivar" la impresión de ticks del emulador? Son demasiados y es super dificil debuggear con ellos, ya que no alcanzo a ver el valor de las variables. Muchas gracias!

**Comment by jmwielandt** [comment]
A qué te refieres con la impresión de ticks del emulador? .-.

**Comment by jfuentesg26** [comment]
Me refería a la impresión de logs, pero ya descubrí como sacarlos! gracias iguaaal
