### ISSUE TITLE
T2 | P3d Uso de delay

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2343/Syllabus-2020-2#173]
Hola! A mis dispositivos les puse la opción de tener o no incorporado el delay. ¿Puedo hacer el código de la parte d asumiendo que tengo que tener desactivado el delay en los dispositivos?
Además de que la ejecución del programa tardaría bastante el manejo de los estados aumentaría los ticks y la complejidad del código.

**Comment by Tomasalvarez15** [comment]
Para cambiarlo solo debo cambiar el self.delay a False en la clase de la cinta y del procesador.

**Comment by jmwielandt** [comment]
> ¿Puedo hacer el código de la parte d asumiendo que tengo que tener desactivado el delay en los dispositivos?
No, tienes que tenerlo considerado y manejarlo.
Saludos
