### ISSUE TITLE
Para el coprocesador se debe tener acceso a cada lugar de almacenamiento por port y memory mapped?

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2343/Syllabus-2020-2#174]
Hola
Para el coprocesador, se dice que debe poder ser usado a través de memory mapped y port, eso significa que cada puerto debe tener acceso a través de memory mapped también y viceversa?
O algunos a través de memory mapped y otros a través de port?

Se que el profe dijo algo en clases pero no me quedó muy claro

**Comment by Arcoirisky** [comment]
Hola! 
Me avisan que es una decisión libre. Como te resulte más cómodo estará bien mientras estés usando memory mapped y/o puertos 

Puedes repetir en el sentido de usar ambas conexiones, etc
