### ISSUE TITLE
T2 | Como tener 1 solo archivo RON

### ISSUE THREAD

**Issue by Brocoleta** [IIC2343/Syllabus-2020-2#175]
Hola, segun las especificaciones de la tarea hay que entregar 1 solo archivo ron, no he podido poner los dos ron (1 de cada IO) en un solo archivo, en la guia de uso tampoco se especifica como funciona muy bien load_io_from_file(), tengo entendido que tengo que entregar el parametro del nombre ademas de la ruta pero no he podido hacerlo por si me podrian especificar mas como recibe los specs load_io_from_file()

**Comment by jmwielandt** [comment]
Hola,

```
 1 archivo .ron con la especificación del dispositivo desde el punto de vista de IO.
```

Significa que es 1 .ron por dispositivo. No le he implementado el soporte para múltiples I/O en un archivo.
Saludos!

**Comment by Brocoleta** [comment]
Gracias
