### ISSUE TITLE
T2 | Funcionamiento memory mapped

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#176]
Hola, quería saber si tiene sentido usar el mapeo de memoria como un port. Esto, en el sentido de que cuando se escriba en cierto address que este mapeado, mi address decoder no solo cambie la información asociada a algún atributo de mi I/O, sino que además ejecute alguna función. Por ejemplo, podemos tener un puerto comando en el caso de port I/O y en este caso sería hacer lo mismo pero que al escribir en cierta dirección sea como haber mandado un comando. Se que se puede hacer en el caso del emulador pero no se si es algo que se haga en la vida real y por lo tanto, que es algo que esperan que hagamos o que evitemos para la tarea.

**Comment by movalle4** [comment]
Hola

Existe bastante libertad en la manera que puedes implementar tu solución a esta pregunta. Si quieres puedes usar las direcciones de memoria de memory mapped como un "puerto", en donde hay direcciones que sirven específicamente para mandar comandos a los dispositivos I/O.

Saludos
