### ISSUE TITLE
T2 | 2.b input

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2343/Syllabus-2020-2#177]
hola, ¿puedo hacer que mi función reciba un .txt de input y el output sea un .txt?

**Comment by movalle4** [comment]
Hola

En la pregunta 2b, a idea es crear una función que reciba una lista de strings y que retorne una lista de strings  Esto es explicado con más detalle en la issue #103.

Saludos

**Comment by JoseAvanzada2019** [comment]
ok! gracias
