### ISSUE TITLE
T2 | Emulador main_rng.py Máximo de Ticks

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2343/Syllabus-2020-2#179]
Hola,

Estoy teniendo muchos problemas entendiendo el funcionamiento del emulador, si corro `main_dummy.py` tengo un output terminado de memoria de datos donde puedo controlar los clocks con ENTER y luego me aparecen los Logs. Pero cuando hago lo mismo en  `main_rng.py` me sale una vez la memoria de datos y luego un log que dice:

_[tick n° 20000] Máximo de ticks alcanzado. Finalizando la ejecución del programa._

No se si esto esta correcto, pero este es el código exacto del repositorio de material complementario y no se si el output de ese ejemplo debería ser exactamente igual al de `main_dummy.py`. Feliz de recibir explicaciones extra que estoy entendiendo muy poco el emulador (ports, read, write, buffer) después de estar viéndolo sus buenas horas.

Muchas gracias

**Comment by jmwielandt** [comment]
> [tick n° 20000] Máximo de ticks alcanzado. Finalizando la ejecución del programa.

Quizás tu computador es demasiado potente y por eso llegas al máximo de ticks, intenta cambiarlo en la línea 145 del .py

Justo esta semana la tengo más cargada T_T ¿Viste la clase en la que expliqué más menos cómo usar el emulador?

**Comment by jmwielandt** [comment]
En otra issue expliqué con peras y manzanas lo que tienen que hacer, también en esa clase. No sé si lo que voy a decir a continuación te ayude, pero bueno:

El emulador aplica directamente la materia que vieron en clases de I/O, no es algo "nuevo" más allá de cómo usarlo propiamente tal. Pueden tener un I/O conectado por puertos o por mapeo de memoria a su computador (el que usas para leer esto) y en esencia es lo mismo que se ve en las clases y los apuntes.

El emulador simula eso. Si intentas acceder a una dirección de memoria que está mapeada, va a enviar esa interacción al Address Decoder quien tiene que decidir qué hacer al respecto. Si estamos leyendo esa dirección, tiene que entregar *algo* de vuelta. Si intentas acceder a un puerto, el dispositivo que esté conectado al otro lado va a hacer lo que tiene que hacer con esa interacción. Quizás estás leyendo el reloj del sistema y ese es justo el puerto de los minutos, entonces va a mandar la cantidad de minutos al registro que diga la especificación del computador.

Para hacer todo eso, tienen que programar los dispositivos y el address decoder en python, darle al emulador las especificaciones de los I/O a través de archivos `.ron`, cargar la ISA (en la versión 2 hice que se pueda manejar como un archivo de texto plano, en formato ron), etc. El emulador no corre como programa independiente sino que lo compilé como una librería de python y está contenido en la clase `AppCB`, la misma que ya usaba la interfaz gráfica que les hice en la tarea 1.

Sobre el tema del delay, que parece que a muchos les ha causado confusión, es simplemente una forma de simular el comportamiento real de un dispositivo. Imagina que le pides a tu disco duro que te copie 1 GB de la RAM al disco, entero. Obviamente se va a demorar su buen tiempo y pase durante todo ese rato con un estado "ocupado", durante el cual no le puedas pedir más cosas y tengas que esperar a que se desocupe. Eso mismo tienen que simular ustedes.
