### ISSUE TITLE
T1 | P1 c - Número igual a su complemento

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#18]
Hola, tengo una duda, no me queda muy claro cuando preguntan cuantos números son iguales a su complemento? Esto yo lo interpreto como cuantos números en su representación sin complemento son iguales a su representación con complemento. Por ejemplo para base 2:

si tenemos un int sin signo:

1 = 0001
2 = 0010

Pero si vemos su representación en complemento 2, tenemos que es exactamente los mismo

1 = 0001
2 = 0010

No se si entendí bien la pregunta y se refiere a esto u otra cosa?

**Comment by felipearellanom** [comment]
Tienes que tomar el numero como una cadena de símbolos (n_1), y el complemento a N como una funcion sobre esta cadena que resulta en otra cadena de simbolos (n_2).
Se te pregunta si dado un K y un N cualquieras, cuantos numeros enteros de K cifras son iguales despues de aplicar complemento a N, es decir n_1=n_2.
Cuando mencionamos numeros enteros es porque tienen signo, mientrass que los naturales no tienen signo.

**Comment by RonaldoSosa** [comment]
@felipearellanom esto significa de puede existir el complemento a 3 , o a 4 ,etc o solo existen el complemento a 1 y a 2?

**Comment by jerrymendoza** [comment]
@RonaldoSosa el profe mostró realizo un ejercicio con complemento a 16, pero con esa base, quizás la pregunta es si existe complemento a 3, 4.. dentro de binario?

**Comment by RonaldoSosa** [comment]
@jerrymendoza nono si no me había fijado del ejemplo que hizo el profe , error mío :( graciasssss!

-
