### ISSUE TITLE
T3 | 1a: norma de matriz

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#180]
Hola!

Quiero confirmar si según lo que me acuerdo de álgebra lineal (y de lo que entendí del enunciado) la norma de la matriz sería la siguiente
<a href="https://www.codecogs.com/eqnedit.php?latex=l_p&space;=&space;\|A\|&space;=&space;(\sum_{i=1}^{m}\sum_{j=1}^{n}&space;|a_{ij}|^2&space;)^{\frac{1}{p}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?l_p&space;=&space;\|A\|&space;=&space;(\sum_{i=1}^{m}\sum_{j=1}^{n}&space;|a_{ij}|^2&space;)^{\frac{1}{p}}" title="l_p = \|A\| = (\sum_{i=1}^{m}\sum_{j=1}^{n} |a_{ij}|^2 )^{\frac{1}{p}}" /></a>
Con p = 1

Gracias!

**Comment by VicenteMerino** [comment]
Tengo la misma duda, una matriz tiene distintas normas (Frobenius, espectral, etc.).

**Comment by nachocontreras** [comment]
Creo que debería ser así, pero me uno a la duda.

![imagen](https://user-images.githubusercontent.com/26395249/97821891-c1f82480-1c92-11eb-95f6-9e67877a29cb.png)

**Comment by Arcoirisky** [comment]
Holi!

Es el que dice @nachocontreras, la suma de los valores absolutos de todos los elementos contenidos en la matriz
