### ISSUE TITLE
Batería en un computador

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#181]
Hola, no se si tiene que ver mucho con las clases, pero me surgió la duda de a qué corresponde la batería en un computador ¿es un dispositivo I/O? o de qué forma interactúa con el computador para que funcione.

**Comment by CristobalHV** [comment]
Hola! La batería es vista como un I/O más ya que esta intercambia información con el computador (porcentaje de carga, comportamiento de esta según si estás enchufado a corriente o no, etc).
