### ISSUE TITLE
Solucion Pregunta 3 Tarea 2

### ISSUE THREAD

**Issue by andrescf** [IIC2343/Syllabus-2020-2#182]
Hola! Queria saber si es posible que hagan una explicacion de la pregunta 3 de la tarea 2, ya que no pude responderla porque no sabia como (y aunque lei los ejemplos dados y mas no fui capaz de completarla) y siento que si no la entiendo me quedare atras para las siguientes tareas y materia del curso, siempre que se pueda.

**Comment by jmwielandt** [comment]
Hola, qué cosas no te quedaron claras?

**Comment by andrescf** [comment]
@jmwielandt Respecto a la materia y teoria tengo casi todo claro pero me complica la parte de aplicacion, el como interacciona el address decoder con los IO, a la vez que con los diferentes tipos de llamada (memory mapped o port IO) y que esto se lleve luego al assembly. No se si se entiende?

**Comment by jmwielandt** [comment]
Hola, sorry la demora, pero de momento no podemos dar la solución. Cuando se publique la pauta te puedo responder lo que quieras.

De todos modos, no hay muchas dependencias entre las preguntas de programación de la tarea 2 con las de esta tarea, más allá de simplemente programar en assembly. La interacción con la caché está completamente desacoplada del emulador, así que con saber abrir un json y usar diccionarios te basta.

Dinos en todo caso si hay cosas que te complican. Saludos! :D

**Comment by andrescf** [comment]
@jmwielandt Ya! muchas gracias
