### ISSUE TITLE
T3 | P1 Descripción matriz

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#183]
Para la pregunta 1, la matriz que formato debe tener? Puede ser como la pregunta tres, en donde las dimensiones de la matriz están definidos en variables, al igual que la matriz se considera un arreglo?

**Comment by aaguilarg** [comment]
La pregunta apunta a que ustedes vean como manejar el problema que se les propone, por lo que esperamos que tomes tus decisiones de diseño
