### ISSUE TITLE
T3 | emu.exe no funciona

### ISSUE THREAD

**Issue by michimalonko** [IIC2343/Syllabus-2020-2#184]
Hola he estado tratando de abrir el emulador nuevo pero no hay forma de hacerlo andar, cuando lo apreto se abre una ventana por como 0,1 segundos y se cierra. Estoy en windows y quisiera saber si tengo que tener algo configurado, lo tengo en una carpeta junto al archivo ISA y config.toml

**Comment by jmwielandt** [comment]
Lo tienes que correr en la consola

**Comment by michimalonko** [comment]
graciasss
