### ISSUE TITLE
T3 | Problema para inicializar emulador o posible Bug

### ISSUE THREAD

**Issue by manarea** [IIC2343/Syllabus-2020-2#186]
Hola!
Estaba tratando de hacer funcionar el emulador pero me lanza errores al tratar de correrlo. Tengo entendido que se pide un archivo de entrada que es en formato json, pero al entregarlo me lanza un error en el que se incluye un path absoluto, por lo que creo que, ¿podría ser un bug? En caso de no ser así, ¿cómo hago funcionar el emulador?
![Duda emulador](https://user-images.githubusercontent.com/48288027/98294895-6f1eb580-1f8f-11eb-93b9-3f0378812d00.png)

**Comment by aaguilarg** [comment]
Hola @manarea ,
El archivo JSON que provees es el nombre que deseas que tenga la salida JSON. 
Para ejecutar el emulador, siempre tienes que proveer un archivo de entrada, que son las instrucciones a ejecutar, es decir, deberías ejecutar algo asi:
```
emu-cli-win.exe instrucciones.txt --accesos hola.json --config config.toml --isa ISA.ron
``` 
donde ```instrucciones.txt``` es el programa que escribes tu.

Avísame si esto te funciona.

**Comment by manarea** [comment]
Ahí sí me funcionó, muchas gracias!
