### ISSUE TITLE
T3 | Formato json

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#187]
Hola, quería saber que son las tuplas que se generan en el json. Mi intuición me dice que son pares de la forma (dirección, valor), pero quiero confirmar esto. 

Gracias

**Comment by aaguilarg** [comment]
Hola @VicenteMerino ,

el JSON generado será de la forma:
```
 {
    "accesos_ram":[tupla_1, tupla_2, ..., tupla_n],
    "accesos_rom":[tupla_1, tupla_2,..., tupla_n]
}
```
en donde cada tupla, es tambien una lista de la siguiente forma: ``` [ n° ciclo , dirección accedida ] ```

Espero que esto sea de tu ayuda, saludos.

**Comment by VicenteMerino** [comment]
Gracias! Y otra cosa, puedo asumir que cada acceso viene ordenado por n° ciclo?

**Comment by andrescf** [comment]
@aaguilarg Otra pregunta sobre lo mismo, no entiendo bien lo del numero del ciclo, se refiere al numero del clock? y el de rom y ram se ejecutan de forma paralela o primero ram y luego rom?

**Comment by jmwielandt** [comment]
@VicenteMerino debería venir ordenado pero no te recomiendo asumir eso, igual es una línea por cada lista en cuanto al código:

```py
diccionario["accesos_ram"].sort(lambda x: x[0])
diccionario["accesos_rom"].sort(lambda x: x[0])
```

@andrescf  sí, el número de ciclo es el número de clock
Imagina que el código es:
```
MOV A,(5)
MOV B,(6)
ADD (7)
MOV A,3
```
- En el ciclo 1 tendrías un acceso a la ROM (dir: 0) y uno a la RAM (dir: 5).
- En el ciclo 2 tendrías un acceso a la ROM (dir: 1) y uno a la RAM (dir: 6).
- En el ciclo 3 tendrías un acceso a la ROM (dir: 2) y uno a la RAM (dir: 7).
- En el ciclo 4 tendrías sólo un acceso a la ROM (dir: 3) y nada más.

No sé si eso es lo que entiendes por "paralelo" o no, es la ejecución del código no más.

**Comment by andrescf** [comment]
@jmwielandt perfecto, gracias!
