### ISSUE TITLE
T3 | Tamaño memoria principal computador

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#188]
Hola, podemos asumir que el tamaño de la memoria de principal del computador es la misma que el computador básico?

**Comment by felipearellanom** [comment]
Si con el computador te refieres al emulador, Sí. Ante cualquier otra duda de este tipo recuerda que:

> "A menos que se diga lo contrario, el comportamiento esperado es el mismo que tendría el computador básico del curso. Registros, palabras de la memoria de instrucciones y espacio de direccionamiento de 8 bits, trabajo con complemento a 2, etc."

[Wiki del emulador](https://github.com/IIC2343/Syllabus-2020-2/wiki#cu%C3%A1l-es-el-comportamiento-esperado)
