### ISSUE TITLE
Error apuntes

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#189]
Hola, creo que la P10 de los apuntes de memoria cache hay un error:

![Screenshot from 2020-11-05 21-43-02](https://user-images.githubusercontent.com/47841749/98312271-1a3f6700-1fb0-11eb-9b92-f20431ed5426.png)

Si no me equivoco en esa tabla y las siguiente deberia decir:

Mem[12]
Mem[13]

Ya que se copia todo el bloque.

**Comment by gnacrur** [comment]
Agregar que un poco más abajo (y en varias partes más) dicen: dirección 13 = 01100 en vez de 01101.

**Comment by felipearellanom** [comment]
Efectivamente es tal y como dices, debería decir:
`mem[12]`
`mem[13]`
y cada vez que se menciona el valor binario de 13 debería ser 01101
