### ISSUE TITLE
Apuntes - IEEE754

### ISSUE THREAD

**Issue by isavega** [IIC2343/Syllabus-2020-2#19]
Hola! Tengo una duda de la materia sobre el estándar IEEE754. Por qué se reserva un bit para el signo del significado si el hecho de desfasar el exponente hace que solo se guarden valores positivos? (Duda existencial) Gracias 😄

**Comment by felipearellanom** [comment]
Se reserva un bit para el signo del significante. no del exponente, así permitiendo que la totalidad del numero guardado sea negativo o positivo.
El desfaz del exponente permite que se guarden numeros cuyo valor absoluto este entre 2^127 y 2^-126 sin tener que complicar mucho los calculos.
por lo que el numero en IEEE754: 01000000010000000000000000000000 representa 3
mientras que 11000000010000000000000000000000 respresenta -3
Cualquier otra duda pregunta no más.
