### ISSUE TITLE
T3 | 1b) Tamaño direcciones

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#190]
Hola, quería preguntar si podemos asumir que en una palabra van a caber las direcciones de datos tanto como las de instrucciones. Además, quería saber si estas tienen el mismo tamaño y cuantos bits ocupan . 
Gracias!

**Comment by jmwielandt** [comment]
No se dice nada así que (como el profe ha dicho muchas veces en clases desde hace mucho tiempo) son palabras de 8 bits.

Saludos y sorry la demora :c
