### ISSUE TITLE
Duda unified caché

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#191]
Hola tengo una duda sobre la unified caché. Creo que no tiene mucho sentido utilizar una caché de este tipo en nuestro caso, ya que por el tipo de arquitectura que tenemos en el computador básico (Harvard), tenemos que son memorias distintas para datos e instrucciones, por lo que si accedo a una instrucción por ejemplo en la dirección 3, guardo esto en la caché y luego quiero acceder a un dato en la dirección 3 (lo cual es posible ya que estamos con la arquitectura de Harvard), voy a ver que si está en la caché unified y voy a obtener ese valor, pero el valor almacenado era de la instrucción, no del dato, por lo cual será inconsistente. Para efectos de la tarea debo ignorar esa inconsistencia? Al menos para el ejemplo de los apuntes (y creo que el de clases) se asume arquitectura de Von Neumann para este tipo de caché, por lo que no hay inconsistencia, pero dado que nosotros tenemos Harvard si puede existir direcciones iguales en amboas memorias, por lo que no se si tengo que tratar de cierta forma este caso o sencillamente ignorarlo?

Como se puede ver:
![Screenshot from 2020-11-06 10-37-56](https://user-images.githubusercontent.com/47841749/98372223-30830c80-201c-11eb-93b9-fd6931aa364d.png)
Aquí se asumen direcciones distintas, pero el json en algunos casos repite direcciones en ambas memorias, en un principio pensé que era un bug, pero creo que si puede pasar por el tipo de arquitectura.

**Comment by halobel** [comment]
Hola, no hay inconsistencia, es parte de lo que queremos que evaluen en el ejercicio, por lo que debe decidir cómo manejas estos casos.
Saludos

**Comment by JJJGGGG** [comment]
Entonces podemos asumir que las memorias están "pegadas", es decir que una empieza en el indice siguiente al en el cual termina la otra?

**Comment by jmwielandt** [comment]
> Entonces podemos asumir que las memorias están "pegadas", es decir que una empieza en el indice siguiente al en el cual termina la otra?

No puedes. Dado que tienes punteros de 8 bits, no puedes direccionar a más de 256 bytes y con lo que dices estarías direccionando a 512 bytes.
