### ISSUE TITLE
Bug Emulador | RUST_BACKTRACE = 1

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#192]
**Descripción del bug**
Al compilar mi programa me arroja un error:
![Screenshot from 2020-11-06 13-03-34](https://user-images.githubusercontent.com/47841749/98387718-83ff5580-2030-11eb-920d-cacef3b13850.png)
![Screenshot from 2020-11-06 13-03-15](https://user-images.githubusercontent.com/47841749/98387723-8661af80-2030-11eb-86b5-add00ea095ff.png)

**¿Cómo reproducirlo?**
DATA:
    M 6 ;las filas de la matriz
    N 4 ;las columnas de la matriz
    Matrix 9 -4 34 -22 33 -43 34 66 56 -44 33 99 121 89 90 33 -61 45 0 12 -21 32 9 -10
    res 0

CODE:
    MOV B, (Matrix)

Practicamente solo con los datos no me deja compilar, lo cual es raro porque lo probé con la solución de mi tarea 1 y funcionó bien.

**Comportamiento esperado**
Imprimir logs en consola y crear el json.

**Sistema operativo, versión del emulador y otros**
- Ubuntu 20.04
- 2.1

**Comment by jmwielandt** [comment]
> `Matrix 9 -4 34 -22 33 -43 34 66 56 -44 33 99 121 89 90 33 -61 45 0 12 -21 32 9 -10`

Tienes que separar los valores con comas (`,`). Eso lo explico [aquí](https://github.com/IIC2343/Syllabus-2020-2/wiki/Secci%C3%B3n-DATA#declaraci%C3%B3n-de-variables)

**Comment by VicenteMerino** [comment]
Muchas gracias!
