### ISSUE TITLE
[No-Bug] | Problemas al ejecutar el emulador

### ISSUE THREAD

**Issue by josejimenezp** [IIC2343/Syllabus-2020-2#193]
Hola tengo este problema al intentar echar a andar el emulador.
![image](https://user-images.githubusercontent.com/48298035/98390541-47355d80-2034-11eb-85b4-ad32414b7f97.png)
(El comando ".\emu-cli-win.exe -h" si funciona como debería)

Están todos los archivos en la misma carpeta. Adjunto foto.
![image](https://user-images.githubusercontent.com/48298035/98390832-a85d3100-2034-11eb-801e-06b0b3a149ff.png)

Ayuda por favor 😢

**Comment by jmwielandt** [comment]
¿Tienes la terminal abierta en ese directorio? Prueba quitar las comillas simples al nombre del .asm por si acaso y ejecuta solo:
```
./emu-cli-win.exe ./prueba.asm
```

**Comment by josejimenezp** [comment]
> ¿Tienes la terminal abierta en ese directorio? Prueba quitar las comillas simples al nombre del .asm por si acaso y ejecuta solo:
> 
> ```
> ./emu-cli-win.exe ./prueba.asm
> ```

Sí, está en el mismo directorio. Esto me sale con el input anterior:
![image](https://user-images.githubusercontent.com/48298035/98411693-4bbe3e00-2055-11eb-9e11-4244c6bb43ec.png)

Y esto tiene el archivo asm por si las dudas:
![image](https://user-images.githubusercontent.com/48298035/98411743-5ed10e00-2055-11eb-8dec-6743d0be1ca6.png)

**Comment by josejimenezp** [comment]
Tenía un problema en cómo estaba escrito el archivo asm 😬

**Comment by jmwielandt** [comment]
Ahh dale, ¿ahora te funciona bien, no?

**Comment by josejimenezp** [comment]
> Ahh dale, ¿ahora te funciona bien, no?

Sii, sorry no había cachado que me habías preguntado. Gracias!
