### ISSUE TITLE
T3 | Restricciones P1.3

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#194]
Hola, no entiendo bien que es lo que se espera en esta pregunta? Mi programa nuevo debe empeorar el algoritmo que estoy utilizando (tomando más pasos por ejemplo) o es perfectamente implementar código que no aporte en nada al funcionamiento del algoritmo (dummy) pero que se de antemano que va a empeorar el hit rate?

**Comment by bmurtagh01** [comment]
Tengo la misma duda

**Comment by aaguilarg** [comment]
Hola, les recomiendo mirar la issue #203 que habla de esto, ojalá les sea de ayuda.
