### ISSUE TITLE
T3 | P1.a valores de la matriz

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2343/Syllabus-2020-2#195]
Hola!

Tenía una duda sobre los números que la matriz tiene. Al leer un número muy grande (superior a 127) de la memoria, en el registro se guarda su valor en complemento a 2. Ej: MOV A, 130 -> A:-126. Como podemos diferenciar un número que es negativo con uno que es muy grande? O podemos Asumir que el rango de los números de la matriz son entre -127 y 127?

**Comment by felipearellanom** [comment]
El rango de números de la matriz son enteros entre -128 y 127. Pero la norma a calcular es un numero natural sin signo.

**Comment by felipearellanom** [comment]
Me corrijo, los valores pueden llegar hasta -127 para que no haya problema al calcular el valor absoluto
