### ISSUE TITLE
T3 | P2 Traducción inicial página-marco

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#196]
Debemos asumir que esta traducción inicial existe? O debemos inicializar dicho mapeo vacío y que se vaya alocando a medida que se requiera acceder a la memoria de datos y ver que no está la traducción?

**Comment by VicenteMerino** [comment]
Adicionalmente a esto, podemos asumir nosotros el tamaño que tendrá el espacio físico? Asumiendo que será razonablemente grande para efectos del programa?

**Comment by VicenteMerino** [comment]
Y por último puedo asumir que la TLB inicialmente también va a partir vacía, al igual que una caché?

**Comment by jmwielandt** [comment]
> Debemos asumir que esta traducción inicial existe? O debemos inicializar dicho mapeo vacío y que se vaya alocando a medida que se requiera acceder a la memoria de datos y ver que no está la traducción?

A medida que se vaya necesitando memoria la tienes que ir asignando. No te preocupes por la inicialización de la ROM del computador básico. Esa es información que no tienes.

> Adicionalmente a esto, podemos asumir nosotros el tamaño que tendrá el espacio virtual? Asumiendo que será razonablemente grande para efectos del programa?

El tamaño de la memoria virtual es igual al tamaño máximo direccionable. Pensando en que estamos con el computador básico, ¿cuál sería el tamaño de la memoria virtual?

> Y por último puedo asumir que la TLB inicialmente también va a partir vacía, al igual que una caché?

El profe comentó en clases que no necesitan simular la TLB.
