### ISSUE TITLE
¿Qué pasa si dos procesos tienen el mismo mapeo para alguna página?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#197]
Bueno, la pregunta es básicamente lo que dice el título. Busqué en google que pasaba en este caso y pillé el siguiente link:

https://stackoverflow.com/questions/54799119/can-two-process-share-same-physical-page

Y dice que si se puede, y que es mera responsabilidad del programador. Por ello lo que me dice mi intuición es que si desde un proceso A mapeo el 3 al 7, y luego desde un proceso B (teniendo esta misma asociacion) mapeo desde el 3 al 7, entonces se considera como un hit de la página en la TLB? (Puede que se corrompa pero sigue siendo válido)

Edit: si no es correcta la respuesta (creo que ahí consideraban threads, así que no se si sea correcta) de que forma el computador/SO manejan ese caso donde se mapean las mismas páginas a las mismas direcciones para no corromper la info.?

**Comment by jmwielandt** [comment]
Hola, lo que sale en esa pregunta de github hace referencia a la memoria compartida, que es algo especial que vas a ver en sistemas operativos. Básicamente es pedirle al sistema operativo que te asigne el mismo marco físico que a otro proceso.

En general, no vas a tener que dos procesos tienen un mismo marco físico a menos que hagas swaping, pero aún así uno estará en el disco y el otro en la memoria así que no hay confusión. Si quieres profundizar podrías buscar cómo se estructuran las swap files ;D

Saludos!
