### ISSUE TITLE
T3 | P1a. Truncar si la norma es mayor a 255

### ISSUE THREAD

**Issue by RositaMunoz** [IIC2343/Syllabus-2020-2#198]
Hola!
No me quedó claro del enunciado ni de la explicación que hizo el profe en clases ( clase 23 min 5:35), el tema de truncar la norma si era mayor a 255. Por lo que entendí al principio era que si la norma es mayor a 255, el valor final lo dejaba en 255. Pero también podría verse que si el número es mayor a 255 se debe truncar a 8bits, por ejemplo si al sumar 11111111 + 00000011 = 100000000, trunco los 8bits más significativos y me quedo con ese valor.

Espero se entienda la duda, gracias!

**Comment by halobel** [comment]
Hola, es lo primero que mencionaste. Si la norma es mayor a 255, el valor final es 255.
Saludos

**Comment by RositaMunoz** [comment]
Gracias!!
