### ISSUE TITLE
software necesario para el curso y compatibilidad.

### ISSUE THREAD

**Issue by tnmarin** [IIC2343/Syllabus-2020-2#2]
hola, me preguntaba si hay algun software especial necesario para este curso(ademas de python) y si es asi, si funcionan tanto en mac como windows?

gracias.

**Comment by halobel** [comment]
Hola, comenté sobre esto en clases. Es muy probable que usemos algo más que Python, pero cuidaremos que sea (casi) 100% compatible con todos los sistemas operativos que usen. En cualquier caso, es algo que avisaremos con el debido tiempo.
Saludos
