### ISSUE TITLE
T1 | P1.d - formato I/O

### ISSUE THREAD

**Issue by StroveLight** [IIC2343/Syllabus-2020-2#20]
Para la P1d, 
Como se recibe la lista E? puedo dejarla como parámetro? (E = [3,1,10,...], o E=input(); o algo distinto?)
Como se "retorna" la lista S? puedo dejarla como parámetro? (Se define una funcion que reciba el E, y retorne el S; o algo distinto?)

**Comment by Arcoirisky** [comment]
Me dicen por interno que lo dejes como una función que recibe a E como una lista de argumentos y que retorne S. 
@jmwielandt
