### ISSUE TITLE
T1 | Recorrección

### ISSUE THREAD

**Issue by Ajbarros1** [IIC2343/Syllabus-2020-2#200]
Hola! En el formulario de recorrección de la tarea 1, a que se refieren con errores de formato (en la 1d)? A error de formato de la respuesta o error de formato del archivo?

**Comment by jmwielandt** [comment]
Ambos!

Saludos

**Comment by Ajbarros1** [comment]
Y cuando dicen "sube tu código corregido", se refieren a que lo tenemos que arreglar y mandar el arreglado, o mandar el que ustedes corrigieron?

**Comment by jmwielandt** [comment]
Tienen que corregirlo y mandarlo arreglado.
