### ISSUE TITLE
T3 | Programas de ejemplo para pregunta 2.1

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#201]
Hola! Con respecto a los N programas que debemos correr en la 2.1 estos deben ser todos distintos, o podemos por ejemplo correr el programa desarrollado en la pregunta 1.a con distintas matrices? Gracias!

**Comment by VicenteMerino** [comment]
en clases dijeron que tenían que ser distintos

**Comment by felipearellanom** [comment]
Como dice Vicente, en clases se dijo que tenían que ser distintos. Lo importante es que el patrón de los accesos a memoria entre los programas sea distinto. Pero no te compliques con que programa usar, puedes tomarlos de las clases o los apuntes, la elección de programas en si no se evalúa.

**Comment by Brocoleta** [comment]
Podria por ejemplo ocupar el programa de un compañero de la Tarea 1, que los perdi?

**Comment by jerrymendoza** [comment]
@Brocoleta  Pregunté sobre compartir código (en esa pregunta) en una clase y se dijo que si. Dado que no es lo que se quiere evaluar.
