### ISSUE TITLE
T3 | Valor absoluto de -128

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#202]
Hola! 
Al calcular el valor absoluto de -128, qué debemos retornar? O debemos simplemente ignorar este caso?

Mi duda es porque -128 se lee ```10000000```, y al tomar el inverso aditivo con complemento en base 2 llegamos al mismo número.

Gracias.

**Comment by movalle4** [comment]
Hola

No debes preocuparte por ese caso. El rango de números es entre -127 y 127.
