### ISSUE TITLE
T3 | 1c ¿modificaciones deben tener sentido?

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2343/Syllabus-2020-2#203]
Hola,
Quería saber si en la 1c se pide que las modificaciones tengan sentido/lógica o si simplemente puedo "marear" el cache (pero que ese código siga funcionando según lo pedido en la 1a).

**Comment by CristobalHV** [comment]
Hola @bmurtagh01 !

Como dice el enunciado, las modificaciones que hagas **no deben alterar la lógica/funcionamiento del código**, pero deben **reducir en promedio el hit rate** de la caché.

Si las modificaciones que planeas para "marear" la caché cumplen con ambos requisitos, estás cumpliendo con lo pedido.

Saludos :)

**Comment by jmwielandt** [comment]
@bmurtagh01 
Complementando lo que dijo Cristóbal, hacer cosas "sin sentido" como intercalar accesos a memoria que no tengan ninguna utilidad, meter llamados a subrutinas dummy o similares no son "soluciones" válidas. El problema apunta más a cómo puedes escribir un código igual de válido que otro pero que uno se comporte mucho mejor (o peor) con la caché. A eso se refiere con "no deben alterar la lógica/funcionamiento del código".

Saludos!

**Comment by VicenteMerino** [comment]
@jmwielandt entonces es sumamente válido cambiar por ejemplo el orden en que leemos los datos de nuestra matriz por ejemplo? Ya que, pese a que en definitiva si estamos cambiando la lógica (el orden de lectura), en definitiva nuestro código sigue haciendo lo mismo?

**Comment by jmwielandt** [comment]
@VicenteMerino sí, eso sería válido
saludos
