### ISSUE TITLE
T3 | P2.a Memoria principal y tablas de páginas

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2343/Syllabus-2020-2#204]
Hola, dado que no tenemos TLB (o no debemos simularlo) creo que debemos asumir que las tablas de páginas se almacenan en memoria principal. En este sentido ¿asumimos que siempre vamos a poder almacenar en dicha memoria todas las tablas que necesitemos?

Gracias de antemano, saludos.

**Comment by CristobalHV** [comment]
Hola @DiegoEmilio01 !

Entiendo que el profesor mencionó esto en clases, no tienes que preocuparte del espacio en memoria utilizado por las tablas de páginas para el desarrollo de esta tarea. 

Espero haber aclarado tu duda, saludos!
