### ISSUE TITLE
T3 | Asignación inicial de marco se considera page fault?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#205]
Bueno, principalmente lo que dice el título, la asignación inicial de páginas a marcos se considera pagefault? Porque en los apuntes y la ayudantía no los consideramos como pagefault, pero en la sesion de dudas el profe dijo que si.

Edit: me fijé que en la ayudantía sale como que si se considera page fault, pero igual quiero confirmar que sea así, porque en el ejemplo de los apuntes no se considera.

**Comment by CristobalHV** [comment]
Hola @VicenteMerino !

Si tanto el profesor como la ayudantía dicen que se considera como Page Fault, puedes considerarlo como Page fault

Los apuntes del curso suelen tener algunos detalles desactualizados y en estos casos, prevalece lo que diga el profesor. 

Saludos :)
