### ISSUE TITLE
T3 | Cómo usar la capacidad de los registros para enteros positivos únicamente?

### ISSUE THREAD

**Issue by jonanortizvega** [IIC2343/Syllabus-2020-2#206]
Si la norma me diera 248 por ejemplo, cómo hago para que no se transforme en su versión negativa (en este caso -8)?

**Comment by jmwielandt** [comment]
En realidad... da lo mismo.

Por ejemplo, si tienes -8 (que en c2 es 248) + 13 (que en c2 se queda como 13), al operar en binario obtienes exactamente el mismo resultado interpretándolos con o sin complemento a 2. Si te fijas en el algoritmo de la suma cuando tienes una cantidad finita de bits, en ningún momento se tiene ninguna consideración si el número es positivo o negativo. En la resta, de hecho, se le calcula el complemento al sustraendo **siempre** y luego los dos valores se suman. Así que tranquilo, por mucho que veas un -8 puedes hacer el ejercicio mental de calcular el complemento y decir "no, esto es un 248" y ser feliz con tu vida.

Aquí depende completamente del programador (tú) decir "esta cadena de bits de aquí la voy a usar y *pensar* como un número con/sin signo".

Te pongo el ejemplo de los shifts lógicos (los que tiene el computador básico y los aritméticos (otros que tienen nuestros computadores de forma adicional). Si haces un shift lógico hacia la derecha de un número que podrías pensar como negativo, se transformará en positivo, pero si le haces un shift aritmético el signo se va a conservar. En wikipedia tienen dibujos bonitos de eso. En lenguajes de más alto nivel como C, el que decide cuál de los dos usar es el compilador o intérprete (en caso de que el lenguaje sea interpretado) basándose en los tipos de datos que le declares.
