### ISSUE TITLE
Bug Emulador | POP del stack se cuenta como acceso a memoria

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#207]
Hola! En esta y versiones anteriores del emulador, me ha aparecido en la memoria de datos las direcciones 254 y 255, que yo no he utilizado para mis datos.
```sh
Memoria de datos:
	 DIR | VALUE 
	-------------
	   0 |     3 
	   1 |     8 
	   2 |     1 
	   3 |     4 
	   4 |     2 
	   5 |     3 
	   6 |     4 
	   7 |     4 
	   8 |     3 
	   9 |     5 
	  10 |     4 
	  11 |     6 
	  12 |     6 
	  13 |     3 
	  14 |     5 
	  15 |     3 
	  16 |     3 
	  17 |     1 
	  18 |     2 
	  19 |     3 
	  20 |     4 
	  21 |     5 
	  22 |     7 
	  23 |     2 
	  24 |     6 
	  25 |     4 
	  26 |    90 
	  27 |     3 
	  28 |     8 
	 254 |    25 
	 255 |    57 
```
Pero finalmente hoy descubrí por qué: el stack se emula como almacenandose en la RAM. Esto es más claro aún al ver los accesos a la RAM que muestra el emulador:
```json
{"accesos_ram":[...,[21,255],[22,254],...,[72,254],[74,255],...,[102,255],[103,254],...]}
```
Y las instrucciones ejecutadas:
```sh
...
      21 |   35 | PUSH B          |    2 |    2 | 0000 |  255 | false
      22 |   36 | PUSH A          |    2 |    2 | 1000 |  254 | false
...
      72 |   52 | POP A           |   26 |   26 | 1000 |  254 | false
      74 |   54 | POP B           |    2 |   26 | 1000 |  255 | false
...
     102 |   35 | PUSH B          |    3 |    3 | 0000 |  255 | false
     103 |   36 | PUSH A          |    3 |    3 | 1000 |  254 | false
```
El mayor problema que me da esto es que me aumenta el hit rate (al cargar la línea que tiene el 255, carga la del 254), cuando yo me estaba ayudando de PUSH y de POP para justamente BAJAR el hit rate (de alguna forma que no especificaré aquí jajaja).

Gracias.

**Comment by jmwielandt** [comment]
Hola, eso no es un bug. Call, ret, push y pop hacen accesos a memoria entonces van a pasar por la caché.

**Comment by jmwielandt** [comment]
Ah, y te recomiendo pasarte por la issue #203 por si acaso lo que intentas no es válido
