### ISSUE TITLE
T3 | Semilla algoritmo random

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#208]
Hola, para ese algoritmo lo ideal sería poner una semilla para obtener los mismos resultados? O se espera que varíe el resultado entre ejecuciones?

**Comment by aaguilarg** [comment]
Hola. Me podrías explicar un poco más? Porque la verdad no logro ver bien la parte de la aleatoriedad. Gracias

**Comment by VicenteMerino** [comment]
@aaguilarg La verdad yo no entiendo perfectamente como funcionan las semillas, pero por lo que entiendo son números generados pseudoaleatorios para que independiente de la cantidad de ejecuciones que haga, se obtenga el mismo resultado, pero los números siguen una distribución de probabilidad, por eso (pseudoaleatorios). Creo que es bien usado en simulaciones por lo mismo para poder comparar efectos aleatorios sin que los resultados cambien todo el rato. Por ejemplo, en la base de I/O usaron una semilla para el generador de números aleatorios. En wikipedia hay más info al respecto: https://es.m.wikipedia.org/wiki/Semilla_aleatoria

De todas formas es para saber simplemente (se traduce en literal cambiar una línea en mi código si se setea o no una seed).

**Comment by aaguilarg** [comment]
Entiendo lo de la semilla en algortimos random, sin embargo, no logro entender bien en qué parte buscas usar un algoritmo random para resolver el problema, por eso te pido que me expliques sin dar respuestas por supuesto.
Por otra parte, si consideras que esto que planteas efectivamete aborda de buena manera el problema, adelante; respecto a la semilla, creo que setear una semilla es más recomendable en terminos de facilidad, así la persona que corrige puede ver mejor que pasa.

**Comment by VicenteMerino** [comment]
Ah disculpa, en la pregunta 1 -b -iv se pide hacer sustitución random.

**Comment by aaguilarg** [comment]
Perfecto, entonces si, en ese caso, setea una seed. Pero ten en cuenta de que nosotros en la corrección tambien podemos cambiar la seed. Te digo esto para que te fijes que tu solución funciona para algo general, y no para esa seed dada.

Éxito.
