### ISSUE TITLE
T3 | Peor hit rate - Solo RAM

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#209]
Hola, como hablamos en clases se dijo que bastaba romper la localidad para la RAM. Dado esto basta mostrar que el hitrate de los accesos RAM disminuye? Ya que en mi caso, esto ocurre, pero el hitrate de rom se mantiene parecido, pero como ahora (por la extensión del código) tengo muchos más accesos rom que antes, el resultado total de hit rates también se mantiene relativamente parecido. ¿Es esto válido? Yo creo que si, porque si no ya tendría que entrar a romper la localidad de las instrucciones y hoy dijimos que no era la idea.

Saludos

**Comment by aaguilarg** [comment]
Hola, para estos problemas se les da algo de libertad a ustedes para abordar el problema. Siempre y cuando este justificado y se cumplan las restricciones ya conversadas (como el código dummy). Entonces, si sientes que lo que planteas es válido y sirve para el problema, puedes usarlo.
