### ISSUE TITLE
T3 | Formato archivos a entregar

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2343/Syllabus-2020-2#210]
Me gustaría que aclarara un poco mejor qué hay que entregar. El form dice "Sube UN archivo .ZIP con lo que se pide en el enunciado.", pero el enunciado no dice mucho.

En el caso de:

- `1.a`, ¿un `.asm` o un `.txt`?
- `1.b`, ¿uno o varios archivos `.py`? ¿Un `Readme.md` explicatorio? (En mi caso la caché es un gran objeto dentro de un archivo que calcula hit-rate.)
- `1.c`, ¿un `.asm` o un `.txt`? ¿Un `Readme.md`  con la explicación de cómo logramos empeorar el hit-rate?
- `2.a`, ¿uno o varios archivos `.py`? ¿Un `Readme.md` explicatorio?  ¿Los assembly de los procesos que utilizamos o los `.json` con los accesos a memoria?

Muchas gracias de antemano y saludos!

**Comment by jmwielandt** [comment]
Hola

* p1
  * 1a un .txt con el código, hazlo fácil de corregir
  * 1b un .py con el código, hazlo fácil de corregir. Si quieres hacer varios .py, pon todo lo de esta pregunta ordenado en una carpeta aparte
  * 1c un .txt con el código, hazlo fácil de corregir
Adicionalmente, un readme explicando el funcionamiento del programa, decisiones de diseño, cómo correrlo y supuestos.

```
archivo.zip
|
|--- 1a.txt
|
|--- 1b/
|     |
|     |--- main.py
|     |--- ...
|
|--- 1c.txt
|
|--- readme.md
```

* p2
  * 2a un .py con el código, hazlo fácil de corregir. Si quieres puedes separarlo en varios .py
Adicionalmente, un readme explicando el funcionamiento del programa, decisiones de diseño, cómo correrlo y supuestos.


#### ¿Qué es "fácil de corregir"?
- Ordenado
- Buenos nombres de variables, funciones, clases y archivos
- No tener pedazos código repetido con cosas chicas cambiadas (esto es peligroso para ti también, puedes tener muchos bugs por culpa de esto) y otras malas prácticas
- Para cambiar cosas como la matriz de entrada o los json que recibe tu código hazlo lo más directo y que requiera la menor cantidad de pasos posibles (con una constante con el nombre del archivo para las preguntas de python, arriba del archivo que hay que correr, por ejemplo).

#### ¿Por qué pido que sea fácil de corregir?
Para evitar tener que llegar a la recorrección por cosas que no se debería. **Es principalmente por ustedes.**

**Comment by VicenteMerino** [comment]
@jmwielandt entonces no debemos subir los archivos .json o los programas de prueba de la p2?

**Comment by jfpena1** [comment]
Hola @jmwielandt , no es mejor que este en .asm que en .txt todo codigo assembly?

O lo cambiamos para que esté todo en .txt
Gracias!

**Comment by jmwielandt** [comment]
> @jmwielandt entonces no debemos subir los archivos .json o los programas de prueba de la p2?

hola, sí, entreguen los programas de prueba también. actualicé la respuesta.



> Hola @jmwielandt , no es mejor que este en .asm que en .txt todo codigo assembly?
> 
> O lo cambiamos para que esté todo en .txt
> Gracias!

preferimos .txt.

**Comment by JJJGGGG** [comment]
Hola, el 2.b se entrega aparte, o en el mismo zip?

**Comment by VicenteMerino** [comment]
En el form dice que aparte
