### ISSUE TITLE
T3 | Desempate Bélády

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2343/Syllabus-2020-2#211]
Hola!
Me surgió una duda de un caso muy extremo de Bélády donde todos los bloques de la cache no serán ocupadas por el resto del código, y por lo tanto, no hay ninguno que se utilizará más lejos en el futuro que el resto. Que técnica usamos en este caso? El último de la cache, random, FIFO (este no plis),...?
Muchas gracias!

**Comment by aaguilarg** [comment]
Hola, en general la tarea da libertad de decisiones de diseño para abordar los problemas (y como siempre, debe estar justificado y por supuesto solucionar lo pedido), y esta pregunta no es la excepción, entonces decide utilizar lo que creas más adecuado al caso. 

Éxito.
