### ISSUE TITLE
T3 | P2.a debe tener caché?

### ISSUE THREAD

**Issue by bmurtagh01** [IIC2343/Syllabus-2020-2#214]
Hola, 
Quería saber si en la pregunta 2.a se debe incluir un cache entre la memoria y la memoria virtual, ya que no esta especificado en el enunciado.

**Comment by VicenteMerino** [comment]
No se debe incluir por lo que han mencionado.

**Comment by Arcoirisky** [comment]
Confirmo que no debe de tener caché en la 2.a c:
