### ISSUE TITLE
Bug Emulador | Error en el tick del log de errores.

### ISSUE THREAD

**Issue by tocococa** [IIC2343/Syllabus-2020-2#215]
**Descripción del bug**
Ticks en el log de errores es siempre el mismo.

**¿Cómo reproducirlo?**
Este script tiene varias instrucciones que el emulador no soporta, y en el tick de errores siempre se indica que en el tick N 2 se encontró una instrucción no soportada.
```
DATA:
    var1    2
    var2    3
    i       15
CODE:
    start:
        MOV A, (var1)
        MOV B, (var2)
        DIV A, B
        ADD A, B
        CMP A, (i)
        JLE extra
        JMP start
        CAP A, B
    extra:
        ZZZ (i), A
        JMP end
end:
```
El output es el siguiente:
![image](https://user-images.githubusercontent.com/22779371/99133482-f0fa8880-25f8-11eb-8d65-325e93e41226.png)

**Comportamiento esperado**
Esperaría que al correr `.\emu-cli-win.exe .\bug.asm` indicara el tick en el que se intentó ejecutar la instrucción incorrecta/no soportada.

**Sistema operativo, versión del emulador y otros**
- Windows 10 Pro ver 20H2 build 19042.610.
- Emu ver 1.0.3
- Probablemente soy el peor programador de assembly del ramo, así que es muy probable que esté haciendo algo más mal y no sea un bug😭.

**Comment by jmwielandt** [comment]
> Probablemente soy el peor programador de assembly del ramo, así que es muy probable que esté haciendo algo más mal y no sea un bug😭.

Tranqui, assembly es algo realmente difícil de dominar, yo tampoco diría que lo domino al 100% de hecho pero... en realidad sí es un bug...  y también un feature request. Me explico:

Lo de "Instrucción {} no reconocida como válida." se añade al log al momento de preprocesar el código, no en la ejecución, entonces no debería decir el número de tick, y al mismo tiempo es raro que diga que parte en el tick 2. Esa sería la parte del bug.

Y por otro lado, también es cierto que sería útil que avise al momento de pasar por una instrucción no válida. Esa es la parte del feature request.

Dame tu correo porfa, lo voy a revisar.

**Comment by tocococa** [comment]
Okaoka, mi correo es tcontrerasc@uc.cl
