### ISSUE TITLE
Emulador | Error al correr emulador

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2343/Syllabus-2020-2#216]
**Descripción del bug**
Al hacer la última actualización de código me aparece:
thread 'main' panicked at 'No se pudo procesar el código correctamente.', /Users/F/arqui/core-emu/src/adminpc.rs:152:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

No tengo idea por qué aparece esto

**Comment by JoseAvanzada2019** [comment]
al final ya caché por qué era, pasó que deje una variable puntero sin valor por defecto, mil disculpas

**Comment by jfernandez7** [comment]
Hola, no se si es un bug pero el emulador es super sensible a los espacios, sobre todo al referirse a la sección del programa (DATA y CODE) y a los títulos para direccionar saltos, por si a alguien le sirve (arroja este mismo error: thread 'main' panicked at 'No se pudo procesar el código correctamente.'). Con DATA y CODE sin espacios logra avisar otros errores por espacio en los logs

**Comment by jmwielandt** [comment]
> al final ya caché por qué era, pasó que deje una variable puntero sin valor por defecto, mil disculpas. ¿debiese mostrar es error o tomar un valor por defecto?

Work as intended. No hay valores por defecto en memoria. Por ejemplo, si intentas leer una dirección de memoria virgen te va a retornar algún valor random (literalmente hago un random).



> Hola, no se si es un bug pero el emulador es super sensible a los espacios, sobre todo al referirse a la sección del programa (DATA y CODE) y a los títulos para direccionar saltos, por si a alguien le sirve (arroja este mismo error: thread 'main' panicked at 'No se pudo procesar el código correctamente.'). Con DATA y CODE sin espacios logra avisar otros errores por espacio en los logs

En efecto, los títulos de las secciones DATA y CODE tienen que estar bien escritos. Tampoco puedes tener un espacio entre el nombre de un label y los dos puntos cuando son direcciones a las que saltar. Pero por ejemplo puedes poner algo como `MOV   A ,         B      `  sin problemas. (Github no me deja poner bien todos los espacios que quiero).
