### ISSUE TITLE
T3 | P2a

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#217]
Hola, de los últimos minutos de la última clase entendí que solo tenemos que fijarnos y simular los accesos de memoria de datos para esta pregunta. En base a eso me surge la duda de como funciona el tema de los 10 ciclos para que se acabe el turno del programa en ejecución. Si el programa no accede a ningún dato por 10 ciclos entonces no simulamos ningún acceso y le pasamos el turno al siguiente programa? o consideramos que con 10 ciclos se refieren a 10 accesos a memoria (o sea 10 ciclos en los que si haya un acceso a la ram)? 
Gracias!

Edit: ahora ya lo hice considerando que sean 10 accesos efectivos antes de cambiar, por lo que, cambio mi consulta a preguntar si puedo hacer ese supuesto en el readme de la pregunta.
Aprovecho de preguntar si es válido usar random para el swapout.

**Comment by Arcoirisky** [comment]
Hola!

En realidad era de la otra forma pero en tu caso, mientras lo expliques bien no debería de haber problema.
