### ISSUE TITLE
T3 | P2a Uso de accesos de T1 de compañeros

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2343/Syllabus-2020-2#218]
Duda muy corta, para los que no hicimos la T1 P3 podemos pedirle a algún compañero sus programas de la parte a) y b) para los accesos de la T3 P2a)?

**Comment by Arcoirisky** [comment]
Hola!
En la #201 dicen que en clases permitieron se podría compartir código (en esa pregunta) entre la T1 y esta. 
Te sugiero mirar la issue ya que se menciona un detalle a la hora de desarrollar el patrón de accesos a memoria.
