### ISSUE TITLE
Días de Gracia

### ISSUE THREAD

**Issue by clementesepulveda** [IIC2343/Syllabus-2020-2#219]
Hola!

Quería saber si es que entrego la entrega final (valga la redundancia) a las 00:01 en vez de las 23:59 (2 minutos atrasados :,( ), eso cuenta como un día de gracia completo? Estoy suponiendo que si (y pueda cambiar algunas cosas de la entrega), pero tal vez sean un poquitito flexible (?)

Gracias!

**Comment by jmwielandt** [comment]
Hola, sí, cuenta como el día de gracia completo.
Ten en cuenta que nos quedamos con la primera entrega que hagas diciendo que es tu entrega final.
