### ISSUE TITLE
Días de gracias restantes - Bonus

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#220]
Hola! A principios de semestres creo que alguien preguntó si es que no se utilizaban los días de gracias en todo el semestre habría alguna bonificación a la nota del curso y el profe dijo que era algo que no tenían contemplado pero que de primera no descartaba. Por ello me gustaría saber si se hará efectivo algo de este estilo, ya que aun me quedan los 5 días de gracia y quería ver si puedo relajarme un poco con el plazo de la próxima tarea o hago un esfuerzo por entregar dentro del plazo establecido.

Saludos,

**Comment by halobel** [comment]
Hola Vicente, tal como al principio del semestre, no lo tenemos contemplado, y salvo algún evento muy inesperado, lo más probable es que no lo consideremos.
