### ISSUE TITLE
T3 | P2-a Llenar 3 veces memoria de datos

### ISSUE THREAD

**Issue by sgutgar** [IIC2343/Syllabus-2020-2#221]
Hola, encuentro bastante dificil que con mis codigos pueda llenar 3 veces la memoria de datos, estoy llegando como a 600 max y quería saber si esto es realmente necesario, pues con que funcione el codigo para cualquier magnitud de datos debiera estar todo ok o no? Muchas gracias

**Comment by jmwielandt** [comment]
Sale explícito que tienes que hacerlo. Puedes poner más de 5 programas que es la mínima cantidad pedida.

![image](https://user-images.githubusercontent.com/37153467/99406624-deb86d00-28cc-11eb-99da-c7728541bff3.png)

Porfa, considera antes de hacer este tipo de preguntas en estas fechas que la entrega oficial ya fue y muchos de tus compañeros ya entregaron cumpliendo con lo pedido.
