### ISSUE TITLE
T4 | P3:que se considera como "unidades de control de hazard"?

### ISSUE THREAD

**Issue by jfpena1** [IIC2343/Syllabus-2020-2#225]
Hola, la P3 dice que debemos reemplazar lo que haceN estas unidades, pero no me queda claro si esto incluye reemplazar el uso de las forwarding units, o solo las dos Hazard Control Units (la que está en la etapa ID y la que está en MEM.)

Muchas gracias!

**Comment by jfpena1** [comment]
Además, si es que se considera que debemos manejar los saltos, ¿podríamos utilizar 3 NOP por default para cumplir con el _stalling_ necesario? Esto dado que como no se pueden utilizar las Hazard Controlo Unit no tenemos forma de saber si hay o no cumplimiento del salto.

**Comment by felipearellanom** [comment]
Se consideran unidades de control de hazard todo lo que se le agrega al pipeline después de poner los registros entre etapas. Una manera de verlo es que el computador tiene que funcionar como existe en el apunte 11 pagina 10 Figura 14 evitando hazards con NOPs en posiciones apropiadas.
![photo_2020-11-24_18-22-54](https://user-images.githubusercontent.com/37161927/100152851-16ea1d80-2e82-11eb-82d9-c1939208c0e4.jpg)

**Comment by jfpena1** [comment]
gracias!

**Comment by Ajbarros1** [comment]
Solo para confirmar, se tienen que agregar los nops suficientes para que no haya necesidad de hacer forwarding?

**Comment by jmwielandt** [comment]
@Ajbarros1 mira la issue #237
