### ISSUE TITLE
T4 | Programas Assembly P2 y P3

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#226]
Hola para la pregunta 2, se pide escribir un código en assembly con pipeline. 
La duda es, escribimos el código normalmente como tareas anteriores (pero con las nuevas instrucciones de esta tarea) o debemos tener en cuenta e incluir los NOP en esta pregunta.

Para la pregunta 3, sacamos códigos assembly de tareas anteriores por ejemplo? 

La idea que se me ocurre es usar el codigo assembly de la 2 en la pregunta 3, pero tendría sentido solo si en la 2 no tomamos en cuenta los NOP.

**Comment by felipearellanom** [comment]
Todo programa assembly en ambas preguntas tiene que respetar la ISA del Computador Básico con Pipeline.
Para la pregunta 2 no hay que considerar NOP a menos que sean parte del código originalmente. Un computador con pipeline está equipado para "generar" esos NOP en su ejecución.
En la pregunta 3 no se pide explícitamente ningún programa de assembly, si tu código python puede tomar cualquier programa en assembly y agregar los NOP necesarios es suficiente.

**Comment by andresplass** [comment]
Perfecto, sobre la pregunta 2 comentaba los NOP para saber si tomamos en cuenta los hazards, o para saber si el objetivo de la pregunta es solo escribir instrucciones con la nueva ISA con pipeline.
De todas maneras, gracias por la respuesta!

**Comment by felipearellanom** [comment]
Ese es el objetivo de la pregunta, cualquier otra duda pregunta con confianza.

**Comment by andresplass** [comment]
Me quedó claro, muchas gracias @felipearellanom ! :)

**Comment by gnacrur** [comment]
Hola, no me quedó claro de donde sacamos esta ISA con pipeline, la debemos armar nosotros? 
Saludos!

**Comment by jmwielandt** [comment]
@gnacrur está en el apunte 11
