### ISSUE TITLE
T4 | P3 hazards considerados

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#228]
Hola quería saber qué hazards consideramos para esta pregunta.

Asumo que todos los hazards de datos pero sobre hazards de control, tomamos como que siempre saltará? como que nunca saltará? o no tomamos en cuenta éstos? ya que de eso dependerá el código de la solución. 

Asumimos también que el programa puede hacer fordwarding solo, o tenemos que agregar los NOP necesarios para que no sea necesario ésto? Ésto lo pregunta porque en la issue #225 no se muestran los forwarding units

gracias!

**Comment by jmwielandt** [comment]
Hola, son todos los hazards que se detallan en la materia y apliquen al computador básico con pipeline.

Para los hazards de control, toma que funcionan tal y como se detalla en los apuntes (mirando los diagramas te va a salir más fácil cachar).

No tienen las forwarding units.

Saludos~

**Comment by andresplass** [comment]
Muchas gracias por la aclaración :)

**Comment by niguzman** [comment]
> 
> Para los hazards de control, toma que funcionan tal y como se detalla en los apuntes (mirando los diagramas te va a salir más fácil cachar).
> 
Una consulta, para los hazards de control que dependen del código y del ciclo (JNE y JEQ), cómo se maneja el tema de los NOP, ya que esto irá variando constantemente y no he podido encontrar cómo controlar el tema de Flushing desde software

**Comment by jmwielandt** [comment]
@niguzman no te puedo responder porque eso lo tienen que resolver ustedes, es parte de la pregunta :/
mucho ánimo
