### ISSUE TITLE
T4 | P3: Formato del assembly recibido

### ISSUE THREAD

**Issue by catalina-ramirez** [IIC2343/Syllabus-2020-2#229]
Hola!
Para la pregunta 3 de la tarea, ¿nuestro código debe ser capaz de procesar cualquier código assembly o alguno específico que le demos nosotros? En caso de ser lo primero, ¿podemos asumir ciertas restricciones en el assembly de entrada? Por ejemplo, que las instrucciones vengan en mayúsculas, o que la forma en que se escribe una instrucción con sus respectivos parámetros sigue cierto formato que nos ayuda a procesar con mayor facilidad el código.

**Comment by jmwielandt** [comment]
Cualquier programa en assembly (mientras respete la isa del computador básico con pipeline).

Aplica lo mismo de las tareas pasadas, no vamos a intentar pillarlos pero hay algunas cosas que sí deberían validar algunas cosas básicas. No de malvados que vamos a buscar probar cosas raras sino porque simplemente se nos pueden pasar cosas.

Saludos~
