### ISSUE TITLE
T1 | 0 se considera igual a su complemento a N?

### ISSUE THREAD

**Issue by jfpena1** [IIC2343/Syllabus-2020-2#23]
Hola, respecto a la pregunta 1.c) tengo la duda si es que 0 puede ser considerado como igual a su complemento.
Entiendo que el complemento de 0 (para toda base) tiene un digito más que viene del carry. Mi pregunta es, puedo asumir que ese carry no se toma en cuenta, y que por lo tanto C_N(0) = 0?

Gracias!

**Comment by Arcoirisky** [comment]
Estás en lo correcto, el bit extra se muere~
