### ISSUE TITLE
Duda señal RegIn en computador básico con pipeline

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#230]
Hola, si la señal RegIn es 1, indica si se va a elegir Dout en el MuxReg?
![Captura](https://user-images.githubusercontent.com/42097398/100373976-5d5a8c00-2fea-11eb-9f76-b31fcf1ce5c1.PNG)

**Comment by jmwielandt** [comment]
No hay una convención más allá de "identifica claramente tus puertos de entrada. Puedes ponerlos como prefieras (intenta ser consistente eso sí) o simplemente usar el nombre de la entrada seleccionada como señal (intenta ser consistente eso sí).

Saludos

**Comment by mc-cari** [comment]
Ya, gracias.
