### ISSUE TITLE
T4 | P2: Caso de truncar si llega al máximo

### ISSUE THREAD

**Issue by vndiaz1** [IIC2343/Syllabus-2020-2#231]
Hola, estaba haciendo la pregunta 2, donde se pide que se trunque al máximo de los registros si el contador de elementos igual a 0 es mayor a 255. Me di cuenta que este caso no podría pasar nunca, ya que la matriz tendría que tener al menos 255 elementos iguales a 0, lo que es imposible almacenar en memoria por el tamaño de la RAM que tiene el computador básico si además se agregan otros datos necesarios como M, N y el contador.
Mi duda es si es necesario implementar esto de igual forma, o se puede dejar de lado, ya que nunca se podría llegar a ese caso.

Saludos!

**Comment by jmwielandt** [comment]
Hola, eso el profe lo explicó en clases cuando se lo preguntaron.
Saludos

**Comment by jonanortizvega** [comment]
@vndiaz1 encontraste la clase en la que lo dicen o la respuesta? no la encuentro... jaja

**Comment by vndiaz1** [comment]
La verdad no lo he buscado todavía, porque yo he ido a todas la clases y no me acuerdo cuando lo dijo.
Voy a esperar hasta el martes para verlo en clases.

**Comment by halobel** [comment]
Fue en una pregunta al terminar la clase, no estoy seguro si martes o jueves de la semana pasada. Como fue después de las 9:50 (lo siento), quizá tuviste que salir de la sesión y por eso no te acuerdas.
Saludos!

**Comment by bmurtagh01** [comment]
Hola! Alguien encontró la clase/tiempo donde el profesor aclara esta tema??

**Comment by bmurtagh01** [comment]
Esta en la Clase 30 en 1:16:10. Aún así no me queda claro por ejemplo si aún debemos hacer un catch de este error siendo que no lo podemos probar con nuestro código si es que lo hacemos correctamente o lo valores máximos de N y M. ¿Podemos asumir que la matriz no va tener más de 127 elementos dentro de ella por ejemplo?
Gracias

**Comment by jmwielandt** [comment]
@bmurtagh01 lo de si es necesario hacer el catch se lo preguntaron en la última clase. ¿127 de manera arbitraria o porque no te queda más espacio en la memoria? Si no te queda más espacio en la memoria porque necesitas muchas variables auxiliares por ejemplo no hay problema.

Adelantándome: los registros pueden ir de 0 a 255 o de -128 a 127 según cómo quieras verlo. Todas las operaciones funcionan indistintamente eso.
