### ISSUE TITLE
Borrar caché en dispositivos?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#232]
Hola, me surgió una duda respecto a la memoria caché. Muchos dispositivos, sobre todo los celulares tienen aplicaciones que nos permiten borrar la caché para mejorar la eficiencia, pero si el caché está precisamente para mejorar la rapidez a los accesos a memoria no sería una mala idea hacer esto? Pienso que quizás se deba a la multiprogramación y borrar la caché libera la memoria de otros procesos que ya no estoy usando, no se si se deba a eso o por qué razón liberar la caché mejoraría la eficiencia de un dispositivo?

**Comment by DiegoEmilio01** [comment]
Según yo tu intuición es correcta. No es más rápido el celular por borrar caché. De hecho, instagram me va muy rápido con 1.3 Gb de datos y muy lento cuando borro como 1 Gb de caché (creo que porque debe hacer todos los fetchs de historias, publicaciones recientes, etc.). Yo sólo borro la caché cuando quiero realizar descargas como actualizaciones de aplicaciones y el celular me alega que falta espacio.

**Comment by VicenteMerino** [comment]
Buena, gracias!!

**Comment by DiegoEmilio01** [comment]
Ahora que lo pienso, algunas veces cuando hay demasiada caché el sistema operativo empieza a funcionar lento. No se bien como funcionará pero me tinca que es caché pisando caché y F. Tal vez si el celular en general esta lento conviene borrar la caché, aunque en mi opinion reiniciarlo (o tal vez reiniciarlo y borrar la caché) sería lo más efectivo en ese caso.

**Comment by Arcoirisky** [comment]
Tenía entendido que reiniciar te borraba la caché :0c (al menos en computadores) pero siguiendo la lógica no siempre es malo borrar la caché. 

Es verdad que ayuda a eliminar mucho espacio aunque, supongo que incluso los dispositivos móviles utilizan virtualización, por lo que, se pasó, estarías eliminando la TLB. Entonces, al inicio será duro porque debes ir a memoria/descargar recursos de nuevo pero con una TLB más corta es más eficiente la consulta y por lo tanto el acceso es más rápido.

También depende mucho el Hit Rate actual y el protocolo que se utilice para llenar las cachés. Pero en principio podría estar pasando algo como lo que dije. 

Debe de haber algún paper o información en internet, lo que digo es de mi propia siembra así que no confiaría 100% en mi palabra sin antes investigar un poco, a ver si alguien más se entera pero es interesante la pregunta xD

**Comment by jmwielandt** [comment]
Holo @VicenteMerino @DiegoEmilio01 

No deben confundir la pieza de hardware memoria caché que es lo que estudiamos en este curso con la _cached data_ o la caché de los programas como archivos dentro de la unidad de almacenamiento de nuestro computador (un celular es un computador).

A lo que se están refiriendo es a eso segundo, archivos que crea el sistema operativo o las aplicaciones que guardan mucha información como resultados de operaciones pesadas, cosas que tienen que descargar de internet, miniaturas de cosas, etc. Esto se usa mucho en aplicaciones web, si ya te bajaste el css y el logo de un sitio web que va arriba a la izquierda, el favicon y unas cuantas cosas más que no van a cambiar pronto, ¿por qué deberías bajártelas las próximas 358,4 veces que simplemente hagas click en algún link y sigas navegando por el sitio? Todo eso aunque sean unos pocos KB son tiempo, datos móviles y demás que si los vas sumando eventualmente te quedaste sin internet a las 3 de la mañana después de un carrete y despertaste en la carretera en un bosque.

Esop, dejo algunos links con info que encontré al respecto:

- https://learn.g2.com/what-is-cached-data
- https://www.androidpolice.com/2020/05/26/clear-app-cache-data-android/

saludos! :D

**Comment by jmwielandt** [comment]
ah, el tema del rendimiento: si tienes que buscar uno de muchos archivos en una carpeta, dependiendo de como funcione el sistema de archivos te demoras más en encontrarlo que en descargarlo y en ese caso es buena idea limpiar la caché de los programas
o si te queda poco espacio y está de cierta forma fragmentado, se puede demorar en encontrar dónde guardar las cosas en el disco, depende de hartos factores que pueden variar bastante todo esto, sería interesante verlo en sistemas operativos, de hecho 🤔

**Comment by VicenteMerino** [comment]
@jmwielandt Muchas gracias buenísima respuesta, me quedó mucho más claro.
