### ISSUE TITLE
T4 | Formato archivos a entregar P1 y P4

### ISSUE THREAD

**Issue by nachocontreras** [IIC2343/Syllabus-2020-2#234]
¡Hola!

¿En qué formato debemos entregar la P1 y P4? Además, creo que al formulario de entrega le faltan los espacios para esas preguntas.

Saludos y muchas gracias!

**Comment by jmwielandt** [comment]
1 pdf con ambas
gracias por recordármelo
ya está agregada esa pregunta al form
saludso
