### ISSUE TITLE
T4 | Pregunta 3

### ISSUE THREAD

**Issue by josejimenezp** [IIC2343/Syllabus-2020-2#236]
Hola, me entró una duda de cómo hay que resolver la pregunta, ya que para solucionar los hazards de control con instrucciones NOP tendríamos que fijarnos en cada iteración de salto. Mi pregunta entonces es si tenemos que entregar un archivo con el set de las instrucciones completas, para así poder cubrir esa parte, o no es necesario cubrir esto y basta con los hazards de datos, creando un nuevo archivo txt/asm (que es lo que estoy haciendo) y dejarlo así funcionando básicamente como en la página 16, figura 24 del apunte 11. Muchas gracias de antemano!

**Comment by jmwielandt** [comment]
@josejimenezp contesto casi toda tu pregunta en la issue #228 
el qué nops poner, cuándo y dónde es parte de lo que ustedes deben resolver, así que no te lo puedo responder :c

En la pregunta se pide hacer un programa en python que reciba un programa en assembly y retorne una versión modificada del programa que cumpla ciertas propiedades/restricciones, no tienen que modificar la ISA ni nada parecido.

Saludos!

**Comment by josejimenezp** [comment]
> @josejimenezp contesto casi toda tu pregunta en la issue #228
> el qué nops poner, cuándo y dónde es parte de lo que ustedes deben resolver, así que no te lo puedo responder :c
> 
> En la pregunta se pide hacer un programa en python que reciba un programa en assembly y retorne una versión modificada del programa que cumpla ciertas propiedades/restricciones, no tienen que modificar la ISA ni nada parecido.
> 
> Saludos!

Pero es que incluso en la misma pregunta 4 dice "la predicción de saltos es un problema complejo que requiere componentes
especializados de hardware", entonces no sé cómo podríamos solucionar los hazards de control por software. Por eso preguntaba si nos piden entregar el listado completo de las instrucciones o un nuevo assembly.

**Comment by jmwielandt** [comment]
Las soluciones por hardware y las soluciones por software son en general intercambiables. En nuestros computadores se usan soluciones por hardware porque son más rápidas que las por software, pero podría hacerse de la otra manera.

Lo que dice el enunciado y citas es a modo de introducción. No tienen que modificar el asembly/isa, tienen que usar el del computador básico con pipeline que está en los apuntes. Sólo tiene que entregar el programa en python.
