### ISSUE TITLE
T4 | P3-forwarding units

### ISSUE THREAD

**Issue by sgutgar** [IIC2343/Syllabus-2020-2#237]
Hola, perdonen lo insistente, se que han hablado de que hazards hay que hacer en el código pero a pesar de haber leído cada issue no me queda claro si debemos evitar que el código haga que el emulador no tenga que hacer forwarding  o no. 
Muchas gracias.

**Comment by jmwielandt** [comment]
Hola, el emulador no hace forwarding, sólo le cambié un poco la arquitectura para los saltos pero...

- Tienen que "evitar" forwarding
- Tienen que "evitar" flushing
- Tienen que "evitar" stalling

Y adicionalmente:
- No pueden meter nops innecesarios
- El programa resultante tiene que generar el mismo output que el original

**Comment by sgutgar** [comment]
Gracias!
