### ISSUE TITLE
T4 | P3 | La lectura de labels cuenta como un ciclo del clock?

### ISSUE THREAD

**Issue by jfpena1** [IIC2343/Syllabus-2020-2#238]
Respecto a la inclusión de NOPs en el código, quería saber si debiesemos considerar la lectura de labels como algo que utiliza un ciclo, dado que esto afecta a las "burbujas" de tiempo que debamos insertar para evitar los hazards.

Recuerdo que en el emulador no se mostraban, pero nosé si esto es suficiente como para no considerarlos en el conteo de ciclos.

Gracias!

**Comment by jmwielandt** [comment]
Holi, no cuenta porque los labels no son parte del código ejecutable. Son una ayuda para el programador. El compilador (pensando no sólo en el caso particular de este curso sino lo que ocurre también el la práctica) eventualmente los quita y reemplaza sus menciones por direcciones de memoria en el resto del código.

Saludos
