### ISSUE TITLE
T4 | P1 formato data

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#239]
Hola, quería saber si habrá alguna manera en que debe estar ingresada la matriz en la sección de datos o esto depende de nosotros simplemente y podemos hacer lo que sea más cómodo como para la tarea anterior. Además, es válido hacer el supuesto de que habrá un dato almacenando el valor de M y otro el valor de N?
Gracias!

**Comment by movalle4** [comment]
Hola

No existe un formato específico de la matriz N x M de la pregunta 2. Puedes usar el que más te acomode.

Suerte
