### ISSUE TITLE
Administrativos y generales + guía de assembly

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#24]
Hola!
Quería pedir/hacer notar varias cosas, las cuales enumeraré 😬 

2) Quería pedir que se puede especificar cuál es la forma en que se escribe/lee el emulador debido a que lo que he encontrado ha sido principalmente para Assembly x86, por lo que entendí de clases, no es igual. En este sentido, tenemos mucho menos material de estudio para poder hacer las cosas
3) (por ejemplo la máquina de turing)

Gracias!

<details>
<summary>(Meme para hacerlo más ameno)</summary>

![Mucho_texto](https://user-images.githubusercontent.com/26392931/92472899-76545d80-f1b0-11ea-9a77-e09c3a8892a1.png)
</details>

**Comment by jmwielandt** [comment]
Hola,

En la template que llenaste se indica claramente: quejas y reclamos vía mail. Puede ser a `halobel@ing.puc.cl` o a `iic2343@ing.puc.cl`, pero las issues no son el lugar para hacerlo (se pueden perder entre las dudas). Ahora a las preguntas:

2. Si miras los apuntes que están en la carpeta "capítulo 2", se muestra como se va armando una arquitectura propia que tenemos en este curso llamada "computador básico". Este computador está basado en x86 pero no es lo mismo ni se programan exactamente igual.
Para programar tienes que crear un archivo de texto plano con tu editor de texto plano favorito (vscode, atom, sublime...) y escribir en él tu código. Luego, lo seleccionas con el botón "abrir" y luego haces click en "cargar / recargar".
Tienes la ISA en los apuntes del curso, cuando se suba el 5.5 aparecerá la tabla completa. De momento las que salen en los 4 y 5 tienen suficiente para partir, las que faltan no son obligatorias, pueden hacer toda la tarea sin ellas pero estas simplifican un poco hacer algunas cosas.

3. En la pregunta de la máquina de turing lo que se pide hacer es crear el diagrama de un computador que se comporte como una máquina de turing, su set de instrucciones y, dado lo que se pregunta en la C, pueden entender que lo que respondan en las letras anteriores no va a ser exactamente igual a una MT, donde deberán explicar esas diferencias y explicar por qué se producen.
Es imposible hacer un enunciado que sea completamente claro para todos, para eso están las issues.

Saludos!
PD: te metí el meme en un dropdown porque ocupaba demasiado espacio.
