### ISSUE TITLE
T4 | P3 Uso de lower para input y espacios en blanco

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2343/Syllabus-2020-2#241]
Dado que muchos archivos de Assembly son escritos con mayúsculas y minúsculas quería saber si puedo usar lower para dejar todo en minúsculas.
Otra duda que tengo es que, es común usar Tabs para los instrucciones dentro de subrutinas, puedo eliminar esos espacios en blanco que van al principio de la instrucción dado que no afecta al funcionamiento del código?
Ambos supuesto entregarían un código funcional pero con un formato distinto al ingresado, está permitido esto?

**Comment by jmwielandt** [comment]
Sobre el tema de las minúsculas, mira la issue #229 

Sí, puedes borrar la indentación (tabs o espacios) sin problemas. 

Saludos!
