### ISSUE TITLE
T4 | P1 Hazards permitidos

### ISSUE THREAD

**Issue by Juanvg213** [IIC2343/Syllabus-2020-2#242]
Hola, ¿Se pueden mencionar "_hazards_" que ocurran en "_piplines_" donde algunas instrucciones tengan más de **5 etapas**?

**Comment by jmwielandt** [comment]
Hola, la pregunta es sobre el pipeline del computador básico en concreto.

Aprovecho para decir algo que hemos respondido por correo a los que preguntaron:
> Si puedo agarrar el hazard que me dices y expresarlo en términos de los hazards que ya tengo, entonces está mal porque es un hazard que ya está considerado.

O en otras palabras:

> El hazard que nos digas no tiene que estar manejado por las unidades que actualmente existen.

Saludos~

**Comment by DiegoEmilio01** [comment]
Hola, debemos considerar que nuestro hazard no sea solucionado por stalling? Porque al final todo puede ser solucionado con burbujas.

Gracias de antemano por la respuesta!

**Comment by Bneya** [comment]
@jmwielandt me sumo a la pregunta de Diego, de hecho venía a preguntar exactamente lo mismo.

**Comment by DiegoEmilio01** [comment]
Por lo que mencionó el profe en la última clase. Si bien las burbujas pueden ser una solución a implementar, estas no lo están siendo para todos los casos debido a ciertas limitaciones que tienen la Data hazard unit. Te recomiendo revisar el diagrama de los apuntes.

**Comment by jmwielandt** [comment]
@DiegoEmilio01 @Bneya más allá de cómo se soluciona el hazard que propongan, lo que importa es que no sea un hazard ya resuelto por la arquitectura que tenemos. Luego sí tienen que ver cómo podría solucionarse y ahí no hay limitantes.
Mucho ánimo y sorry la demora, se me pasó esta issue :c
