### ISSUE TITLE
Ayudantía ILP

### ISSUE THREAD

**Issue by isavega** [IIC2343/Syllabus-2020-2#243]
Hola, tengo la siguiente duda con la ayudantía de ILP. Resulta que estaba probando el programa de la slide 28:

![image](https://user-images.githubusercontent.com/42187168/100952670-b72deb00-34ef-11eb-9559-c3e409e48b90.png)

En el emulador del computador con pipeline, me entrega lo siguiente:

![image](https://user-images.githubusercontent.com/42187168/100952760-e2183f00-34ef-11eb-8ed9-b47a0691bdba.png)

Mi consulta es, por qué no están los NOPS que se muestran en la ayudantía? La ayudantía está mal? Es un bug del emulador? Muchas gracias!

![image](https://user-images.githubusercontent.com/42187168/100952860-1986eb80-34f0-11eb-9449-2bca661c5930.png)

**Comment by jmwielandt** [comment]
@isavega la ayudantía está bien y no es un bug del emulador
lo que pasa es que la arquitectura que implementé en el emulador para esta tarea es la que no tiene ni siquiera los registros intermedios entre etapas, es simplemente para que puedan probar su código con la arquitectura modificada (figura 2, apunte 11), entonces como no tiene pipeline no tiene hazards y no necesita agregar esas cosas.

Saludos!

**Comment by isavega** [comment]
Perfecto, muchas gracias! Pensé que el emulador incluía la versión con pipeline 🤦

**Comment by isavega** [comment]
@jmwielandt ya sé porque me confundí. Resulta que en la pregunta 3 dice:

"Dado un programa escrito en el assembly del computador básico con pipeline..."

Entonces, pensé que el emulador venía con pipeline. Me puedes confirmar si en la pregunta 2 de la tarea la única condición del código assembly es manejar bien los saltos? (dadas las modificaciones de la figura 2, apunte 11). Gracias de nuevo 😄
