### ISSUE TITLE
T4 | P1 Hazard en computador básico original

### ISSUE THREAD

**Issue by dabalada** [IIC2343/Syllabus-2020-2#245]
Es valido mencionar algun hazard que se daria en el computador basico que vimos originalmente aunque dichas operacion no sea soportada por el nuevo computador basico dada la nueva arquitectura.

**Comment by jmwielandt** [comment]
Hola, no es válido. La pregunta apunta directamente al computador básico **con pipeline** así que el hazard nuevo tiene que ser en este computador. Además, el compu básico original no tiene pipeline así que tampoco tiene hazards.
