### ISSUE TITLE
T1 | P1.b Formato resultado final

### ISSUE THREAD

**Issue by cchauriye** [IIC2343/Syllabus-2020-2#25]
Hola!

No me queda claro que es lo que hay que entregar como resultado final de la pregunta 1.b. Una vez que hice la conversión a float, ¿dejo como respuesta el formato IEEE del float o además debo leer los bits del float como si fuese un número binario "normal"?

Gracias!

**Comment by movalle4** [comment]
Hola!

La idea es mostrar paso a paso cómo se llega al número float en decimal. Entonces tendrías que mostrar cómo llegaste al número binario (Ej: 1101...10) y luego interpretar este número como float (este número representa en decimal el 3275.237, por ejemplo).

**Comment by cchauriye** [comment]
Gracias por la respuesta, pero entre el cambio de endianess y el paso a float, lo lei como decimal o directamente el float es una lectura directa de lo que queda al cambiar el endianess?

**Comment by movalle4** [comment]
Luego de cambiar el endiannes de la secuencia de palabras, debes interpretralo como un float.
