### ISSUE TITLE
T1 | 1.b Almacenamiento de bits

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2343/Syllabus-2020-2#26]
Hola!Puedo asumir que la secuencia de bits del número que recibo parte almacenándose en la dirección 0x36 además dependiendo de esto, me refiero a colocar la secuencia de bits del número que recibo,debería de darle un endiannes en particular para que en el enunciado me haga sentido es decir la secuencia de bits me de el número 230 cuando yo lo quiera leer como número entero

**Comment by movalle4** [comment]
Sí puedes asumir que la secuencia de bits que te entregan parte en la dirección 0x36. Como son 4 palabras contiguas, la secuencia de strings va desde el 0x36 al 0x39. Debes elegir el endiannes original de la secuencia de bits e interpretar esta secuencia como el número entero 230. La solución va a ser la misma sin importar endiannes que elijas.

**Comment by RonaldoSosa** [comment]
Entendido!Muchas gracias!!! :)
