### ISSUE TITLE
T1 | 3.a número de columnas

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#27]
Hola!

Cómo sabremos cuántas columnas tendrá cada fila? Por otro lado, no se si podrían dar uno (o dos 😅) ejemplo(s) de cómo serán los valores entregados

Gracias!

**Comment by movalle4** [comment]
Las matrices de adyacencia son cuadradas, así que la cantidad de columnas será igual a la cantidad de nodos del grafo (N).  

Pronto van a subir código para que entiendan como va a ser el input.
