### ISSUE TITLE
T1 | 3.b supuestos y datos

### ISSUE THREAD

**Issue by rihanuch** [IIC2343/Syllabus-2020-2#28]
Hola!

En esta pregunta podemos asumir alguna de las siguientes cosas:
1. Que se entregará un número impar de datos (debido a que al calcular la mediana si se tiene un número par se debe dividir por 2 y eso sería un float de más de 1 byte)
2. Se entregará una lista ordenada
3. En caso de que no se entregue una lista ordenada, si la ordenamos, se puede retornar el indice de la mediana de la lista ordenada

Gracias!

**Comment by jmwielandt** [comment]
Hola

1. No puedes asumirlo. Ya está agregado en el enunciado: en caso de que el largo del arreglo sea par, puedes quedarte con cualquiera de los dos.

2. Tampoco puedes asumir que va a estar ordenada. No es necesario ordenarlo pero es una forma válida de hacerlo.

Saludos!

**Comment by rihanuch** [comment]
Gracias!

Me sigue quedando la duda con el punto 3. En caso de ordenar la lista, entrego el nuevo índice o el índice antiguo?

Saludos!

**Comment by aaguilarg** [comment]
Como no es necesario ordenar la lista para encontrar la mediana (pero es una forma válida de hacerlo), debes entregar el índice original
