### ISSUE TITLE
T1 | P2 objetivo

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#29]
Hola, no tego muy claro como abordar la pregunta 2 y quería ver si me podían ayudar aclarando algunas cosas. Quería preguntar si es que no necesitamos algo del computador que estamos viendo en clases es necesario que lo eliminemos o la idea es que este sea un computador normal que además sea Máquina de Turing? Lo mismo aplica para agregar componentes. No estoy seguro si intentar adaptar los componentes que tengo para que hagan instrucciones como las que haría una Máquina de Turing o si la idea es agregar componentes como en la ayudantía.  
Con respecto a lo de eliminar componentes, por ejemplo, no se si me va a servir de algo sumar para una Máquina de Turing ya que no es algo que la maquina pueda ejecutar directamente, pero no se si es que elimino la ALU sigo teniendo un computador o no. 
Gracias de antemano!

**Comment by jmwielandt** [comment]
En el enunciado describimos el resultado que queremos y tanto en clases como en los apuntes te damos herramientas que puedes o no usar en tu respuesta. El qué hagas pasa por ser decisiones de diseño y mientras las expliques y el resultado final cumpla los requerimientos del enunciado va a estar correcto. No puedo responderte las preguntas exactas que haces porque estaríamos spoileando las respuestas :c 

Mucho ánimo! :D
