### ISSUE TITLE
T1 | 3.a Porqué 1 byte por entrada?

### ISSUE THREAD

**Issue by jfpena1** [IIC2343/Syllabus-2020-2#31]
Hola, no entendí porque cada entrada de la matriz requiere de 1 byte (8 bits) siendo que la matriz de adyacencia
de un grafo no dirigido tiene entradas que son 0 o 1 (para lo cual solo se necesitaria 1 bit). Podrían detallar mas sobre eso porfa :sweat_smile:

![image](https://user-images.githubusercontent.com/39381457/92549432-9c6d1280-f22f-11ea-9928-0a4ae77d8e58.png)

Gracias!

**Comment by movalle4** [comment]
Si bien solo se necesita un bit para codificar la información, cada entrada de la matriz ocupa un byte entero (8 bits) porque las palabras del computador básico son de un byte. Cada entrada de la matriz se guarda en una palabra del computador para no tener que guardar múltiples entradas en la misma palabra, lo que haría que sea más complicado el problema.
