### ISSUE TITLE
T1 | Pregunta 1.a

### ISSUE THREAD

**Issue by bpeirano1** [IIC2343/Syllabus-2020-2#33]
En la pregunta 1a) cuando nos piden comparar numeros enteros con floats, el tipo float se toma cómo un numero de punto flotante o numero de punto fijo o incluye a ambos?

**Comment by CristobalHV** [comment]
se refiere a los floats de punto flotante (de ahí el nombre) de 32 bits descritos por la convención IEEE754, que son los vistos en clases

saludos :)

**Comment by vchadwick** [comment]
Hola, en esa misma pregunta, solo para confirmar entonces eso incluye que el exponente esté desfasado en 127?

**Comment by vchadwick** [comment]
Hola, en esa misma pregunta solo para confirmar, eso incluye que el exponente esté desfasado en 127?

**Comment by aaguilarg** [comment]
Hola! efectivamente el exponente se almacena desfasado en 127 (es parte del estándar), de todas maneras, ante cualquier duda respecto a este te invito a revisar los apuntes de las [representaciones numéricas de números irracionales](https://github.com/IIC2343/Syllabus-2020-2/blob/master/Apuntes/Cap%C3%ADtulo%201/02%20-%20Representaciones%20Num%C3%A9ricas%20Parte%202%20-%20N%C3%BAmeros%20Racionales.pdf)
