### ISSUE TITLE
Duda sobre data out de la Instruction Memory a la address de la misma Instruction Memory

### ISSUE THREAD

**Issue by ibaeza1** [IIC2343/Syllabus-2020-2#34]
Hola!
Tenia una duda sobre la data que sale de la Intruction Memory. Quería saber si era posible que uno de los datos que sale de la Intruction Memory se pueda devolver a la address de esta (algo asi como un loop (?) pero que no quede como un loop).
Mi pregunta al final es si puedo hacer que uno de los bits de mi Instruction Memory me redireccione a la proxima instruccion,
Gracias! :)

**Comment by frvalenzuela** [comment]
Hola @ibaeza ! 

Hacer ese loop no es posible así como lo describes, a nivel de circuito generas algo secuencial e inestable (que no permanece en un estado general).

Por ejemplo, si tenemos guardo el valor 4 en la dirección 0, lo que sale de la memoria es el valor 4. Sin embargo, como lo que está conectado al puerto address es la salida de la memoria, este último cambiará a la dirección 4. Si suponemos que lo que está Guardado en la dirección 4 es 0, entonces la memoria vuelve a apuntar a la dirección cero y así de forma alternada.

Notar que si la memoria estuviese con otros valores está solo podría seguir apuntando a direcciones lo que podría en algunos casos, y con algunas condiciones sobrecargar el circuito y quemarlo si no se trata bien ): 

Entonces estamos perdidos y nunca podré ocupar lo que está en una dirección como otra dirección distinta  ? No ! La solución la tenemos en los registros ! 

Si nosotros guardaremos la dirección en un registro, y luego ocupamos la salida de ese registro como el addres, entonces la salida de la memoria será siempre la misma (estable) ya que el valor del addres solo cambiará cuando carguemos otro valor al registro. 

Espero que eso solucione la duda, si algo no se entendido no dudes en comentar.

Saludos !

**Comment by ibaeza1** [comment]
Me quedo clarisimo! Muchas gracias!
