### ISSUE TITLE
T1 | Formato de respuesta de preguntas prácticas

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#35]
Hola. Para la T1, dado que se entrega via google forms:

1. Ponemos el código junto con las respuestas teóricas en el mismo LaTeX y enviamos el pdf?
2. Enviamos un zip con archivos .py para las preguntas en python, archivos .noseque para las preguntas de assembly y el archivo INTEGRIDAD.txt dentro?

Gracias

**Comment by jmwielandt** [comment]
Hola, te recomiendo mirar el form. Ahí están explicados los formatos en cada pregunta. Pero es:

- 1 .txt para el INTEGRIDAD.TXT
- 1 .PDF para las preguntas 1a, 1b y 1c
- 1 .py para la 1d
- 1 .PDF para las preguntas 2a, 2b y 2c
- 1 .txt para la 3a
- 1 .txt para la 3b

Mira también la issue #32 en la que explico el formato y la ejecución del emulador para la tarea.
