### ISSUE TITLE
T1 | Diagramas de componenetes

### ISSUE THREAD

**Issue by sehe4** [IIC2343/Syllabus-2020-2#36]
Hola! 👋 

Una duda respecto a latex aplicado al curso, sobre los diagramas con los distintos componentes, ¿existe alguna librería para hacerlos?

Muchas gracias!!

**Comment by frvalenzuela** [comment]
Hola @sehe4 ! 

No he encontrado ninguna que sea útil para los diagramas generales. Normalmente lo que he ocupado en mi tiempo como ayudante es draw.io y luego ingresarlo como imagen. 

Espero que te ayude, cualquier otra duda no dudes en comentar. 

Saludos !
