### ISSUE TITLE
T1 | Problema con instalacion de emulador

### ISSUE THREAD

**Issue by ibaeza1** [IIC2343/Syllabus-2020-2#37]
Hola! Estoy tratando de instalar el emulador con la guia y cuando trato de hacer pip install emu_lib-0.1.0-cp37-cp37m-manylinux1_x86_64.whl me sale esto:

![image](https://user-images.githubusercontent.com/37149485/92761911-8020c100-f368-11ea-884b-6720aa1c3fbd.png)

Estoy usando wsl con ubuntu 18.04. Quizas seria mejor ocupar windows directamente? En la guia solo sale como instalarlo con pip asi que no estoy segura de como hacerlo con sudo apt-get install .....
Gracias!

**Comment by jmwielandt** [comment]
@ibaeza1 lo pudiste solucionar?
Probablemente el pip te esté agarrando otra versión de python que no sea la 3.7. Te recomiendo asegurarte de eso.
Si lo solucionaste, te agradecería que indicaras lo que pasó para que le sirva a tus compañeros ya que puede ser un error bastante común.

Saludos!

**Comment by Bneya** [comment]
Hola, yo estoy teniendo el mismo problema al instalarlo directamente en windows.

```
> pip install emu_lib-0.1.0-cp37-none-win_amd64.whl
ERROR: emu_lib-0.1.0-cp37-none-win_amd64.whl is not a supported wheel on this platform.
```

Y al ver la versión de pip que tengo y para qué python está instalando, me aparece que sí lo está haciendo para el 3.7.x

```
> pip -V
pip 20.2.3 from c:\users\biriv\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
```

**Comment by ibaeza1** [comment]
al final me cambien completamente a windows e instale todo ahi y funciono perfect. No logre que funcionara con el wsl.
Instale todo con python -m pip install "cosa a instalar" y asi me tomo todo bien

**Comment by Bneya** [comment]
Respondo a mi propio comentario. El error ocurría porque por equivocación instalé la versión x32 de python en vez de la x64. Al instalar la versión correcta, funcionó.

**Comment by jptorres1** [comment]
Hola, yo estoy teniendo otro problema.
![image](https://user-images.githubusercontent.com/42180537/92797854-d30a7080-f388-11ea-93db-b0d143bb8f45.png)

Mi versión de pip sí está funcionando con respecto a la versión de python que estoy usando:
`pip 20.2.3 from c:\users\juanp\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)`

**Comment by jmwielandt** [comment]
@jptorres1 hola, estás seguro de que el archivo está en esa carpeta y escribiste el nombre correctamente?

**Comment by jptorres1** [comment]
> @jptorres1 hola, estás seguro de que el archivo está en esa carpeta y escribiste el nombre correctamente?

Aah cierto, no lo tenía guardado en la carpeta correcta. Gracias

**Comment by josejimenezp** [comment]
Hola tengo el mismo problema. ¿Cómo escojo la versión de pip a 3.7 (me está tomando la 3.8)? Gracias.

**Comment by jmwielandt** [comment]
> Hola tengo el mismo problema. ¿Cómo escojo la versión de pip a 3.7 (me está tomando la 3.8)? Gracias.

Si ya lo tienes instalado, debería funcionar usando pip3.7 o pip37.

**Comment by josejimenezp** [comment]
Me funcionó pero ahora cuando intento abrir el archivo main me dice: No module named 'emu_lib' 😢

**Comment by jmwielandt** [comment]
> Me funcionó pero ahora cuando intento abrir el archivo main me dice: No module named 'emu_lib' 😢

Estás ejecutando el main.pyw con python3.7?

**Comment by josejimenezp** [comment]
> > Me funcionó pero ahora cuando intento abrir el archivo main me dice: No module named 'emu_lib' 😢
> 
> Estás ejecutando el main.pyw con python3.7?

Eso era 🤦‍♂️  Gracias!
