### ISSUE TITLE
Dividir señal

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#38]
Holaa, de mi Data Memory (por ejemplo) obtengo un Data Out, ese Data Out, puedo dividirlo en distintos cables para hacer uso de esa información en distintos componentes? 
Muchas gracias!

**Comment by aaguilarg** [comment]
(asumiendo que es para la pregunta 2, de la máquina de turing) es válido que dividas el cable de data out para conectarlo a otros registros u otros componentes, pero debes justificar y explicar debidamente

**Comment by andresplass** [comment]
Perfecto muchas gracias!

**Comment by jmwielandt** [comment]
@andresplass no cierres las issues. Nosotros las cerraremos cuando toque.
