### ISSUE TITLE
T1 | 3b ¿qué indice entregar si el número que está en la mediana se repite más de 1 vez?

### ISSUE THREAD

**Issue by Bneya** [IIC2343/Syllabus-2020-2#39]
Por ejemplo, para el caso del array de archivo base_3b.txt, el array es 

**1, 2, 3, 2, 4, 5, 1, 8, 8, 7, 3**
Así, la mediana sería **3**. 

Sin embargo, el número 3 se repite 2 veces en el array, entonces ¿qué indice debo entregar? ¿índice 2 de la primera vez que aparece el 3 o índice 10 donde aparece por segunda vez o alguna otra cosa? (¿estoy entendiendo bien la pregunta?)

Muchas gracias

**Comment by aaguilarg** [comment]
Hola @Bneya !
Como sale en el enunciado
>En el caso que el tamañoo del arreglo sea par, puede elegir cualquiera de los dos elementos centrales como respuesta.

entonces, puedes elegir cualquiera de los dos :smile:

**Comment by Bneya** [comment]
Hola, gracias por la pronta respuesta, pero mi pregunta no iba a eso. No sé si estoy entendiendo mal lo que me piden, ¿debería entregar el índice donde está originalmente el número que corresponde a la mediana del conjunto no? En el ejemplo del array de arriba, ¿debería entregar el índice donde se encuentra el 3 no? Pero en ese mismo ejemplo, el 3 aparece dos veces en el array (independiente de si es cantidad par o impar de números).
¿Qué indice debo entregar el si 3 aparece en el índice 2 y en el 10 también?

Gracias

**Comment by aaguilarg** [comment]
Como no es necesario ordenar la lista para encontrar la mediana (pero es una forma válida de hacerlo), debes entregar el índice original, y si por ejemplo, el mismo número que es mediana aparece en 2 indices distintos, puedes elegir cual retornar, ambos estan correctos.

**Comment by Bneya** [comment]
Perfecto, gracias :)

**Comment by mpsubiabre** [comment]
Hola! si ordeno la lista puedo entregar el indice en la lista ordenada?

**Comment by Arcoirisky** [comment]
@mpsubiabre hola! no puedes hacer eso porque lo que se pide es el índice en el arreglo original, no en el ordenado!

**Comment by mpsubiabre** [comment]
Y el indice es pensando en que el primer elemento es 0 o no? o es el indice de memoria, es decir partiendo de un indice 2 en el caso de la tarea?gracias!

**Comment by Arcoirisky** [comment]
@mpsubiabre El indice del arreglo partiendo de cero
