### ISSUE TITLE
Lenguajes de programación a usar en el curso

### ISSUE THREAD

**Issue by Drpinto1** [IIC2343/Syllabus-2020-2#4]
¡Hola! :full_moon_with_face:

Sé que el profesor lo ha hablado en clases, pero no me acuerdo exactamente la respuesta.
¿Qué lenguajes de programación usaremos a lo largo del curso?

¡Saludos! :new_moon_with_face:

**Comment by Arcoirisky** [comment]
Te puedo asegurar que Python es uno de ellos. 

Aún estamos en el proceso de coordinación. Pensando en lo mejor para ustedes dado el cambio de profe, sus conocimientos previos y, obviamente, la situación.

A penas tengamos toda la información se les avisará but Python 100/10 uwu👌🏼
