### ISSUE TITLE
T1 | Duda pregunta 1c, se agrega un 0?

### ISSUE THREAD

**Issue by Arodriguez14** [IIC2343/Syllabus-2020-2#40]
Hola! 

Tengo una duda para la pregunta 1c, si estamos en base 10, para el siguiente ejemplo:

Opción 1: Tengo el numero 50, su complemento a 9 es 49, por lo tanto su complemento a 10 sería 50. 
Opción 2: Tengo el numero 50, le agrego un 0 a la izquierda quedando 050, su complemento a 9 sería 949, por lo tanto su complemento a 10 sería 950.

Cual de las opciones es correcta? Como se si debo agregar un 0 o no?

Gracias!

**Comment by aaguilarg** [comment]
Hola @Arodriguez14 ,

Lo que tu preguntas, depende del K. Por ejemplo:
si K = 2; tiene que sacarle el complemento al 50
si K = 3; tiene que sacarle el complemento al 050
...

Saludos! :smile:
