### ISSUE TITLE
T1 | Duda 2.b opcodes

### ISSUE THREAD

**Issue by andrescf** [IIC2343/Syllabus-2020-2#41]
Como la maquina pedida solo debe hacer una cantidad muy limitada de tareas, para mi diagrama de componentes no necesite usar una unidad de control (aun asi cumple con lo pedido), por lo que no tengo opcodes ¿esta bien si no lo uso o es requisito?

**Comment by aaguilarg** [comment]
Hola @andrescf,

Mientras cumplas con lo que se pide en la pregunta, este justificado y se entienda que cumple, esta perfecto. Entonces, es totalmente válida una respuesta que no use la unidad de control, siempre y cuando se cumpla lo pedido en el enunciado.
