### ISSUE TITLE
T1 | Duda sobre como ver la matriz de adyacencia pregunta 3a

### ISSUE THREAD

**Issue by ibaeza1** [IIC2343/Syllabus-2020-2#42]
Hola! Tenia una duda sobre como representar la matriz de adyacencia que me dan en el txt de base. 
Si me dicen que N es 3 la matriz seria de 3x3 (eso entendi yo) y para armar la matriz no cache bien si los primero 3 nodos son la primera fila, los segundos 3 nodos son la segunda fila y asi o va por columnas como que el primer nodo es el nodo de la primera fila y asi. 
No se si se entendio la pregunta :(
Gracias!

**Comment by aaguilarg** [comment]
Hola @ibaeza1 !
1. Se van entregando por fila, es decir (para N=3), los primeros 3 nodos son la primera fila, los segundos 3 nodos la segunda fila y los ultimos 3 la tercera fila.

2. Sin embargo, como dice el enunciado, es un grafo no dirigido, por lo tanto, las matrices de adyacencia siempre serán simétricas, por lo tanto tu fila i será igual a tu columna i. Esto último no importa mucho, si te confundí, quedate con lo primero.
