### ISSUE TITLE
Bug Emulador | Problema con MOV

### ISSUE THREAD

**Issue by catalina-ramirez** [IIC2343/Syllabus-2020-2#44]
**Descripción del bug**
Cuando se declara una instrucción del tipo "MOV A,(M)" se traduce en el emulador como "3OV A, (3)". Se confunde la M de MOV con su dirección.

**¿Cómo reproducirlo?**
MOV A, (M) se traduce en el emulador como 3OV A, (3)

**Comportamiento esperado**
Se debería traducir como MOV A, (3). Solo se soluciona cuando MOV se pone en minúscula.

**Sistema operativo, versión del emulador y otros**
- Windows 10
- emu_lib-0.1.0-cp37-none-win_amd64.whl

**Comment by jmwielandt** [comment]
@catalina-ramirez ya está corregido en la versión 1.0.1 (https://github.com/IIC2343/Syllabus-2020-2/releases/tag/1.0.1). La compilación para Mac debería llegar mañana durante el día (no tengo mac :c).

Dame tu mail uc pls.

**Comment by catalina-ramirez** [comment]
@jmwielandt mi mail es catalina.ramrez@uc.cl !

**Comment by catalina-ramirez** [comment]
(está bien escrito el mail)

**Comment by catalina-ramirez** [comment]
@jmwielandt tengo una duda chica, según la tabla de programabilidad, entiendo que no está implementado que se puede hacer "INC B", sin embargo, en el emulador funciona. Quería saber si es que es normal que se pueda, o no debería pasar?
