### ISSUE TITLE
T1 | Pregunta 2a duda maquina de turing

### ISSUE THREAD

**Issue by sjkinast** [IIC2343/Syllabus-2020-2#45]
Hola! La maquina de turing describe un comportamiento infinito en uno de sus componentes, en ese sentido, podría asumir que alguno de los componentes que yo estime que reemplaza a ese componente de la maquina de turing también tiene ese comportamiento infinito ?

**Comment by sjkinast** [comment]
También, seria bueno que se aclarara  que maquina de turing es la que hay que imitar, en el mismo enlace que entregan de wikipedia hay varias versiones.

**Comment by DiegoEmilio01** [comment]
Creo que con componente infinito se refiere a que en la definición de máquina de Turing la cinta es virtualmente infinita. Pero, el input debe ser finito para que la máquina pueda terminar. Entonces, ¿cómo debemos interpretar esta cinta? ¿Como un string finito?

O tal vez desde otro punto de vista, ¿un programador debe poder instanciar la máquina? esto es, modificar los estados y transiciones. O dada una máquina, ¿él le entrega inputs que se procesan? (estoy pensando en los opcodes ahí).

Por último (sry lo largo), ¿qué debe retornar la máquina? Se debe poder "leer" el estado final, o se debe poder lees un 1 o 0 dependiendo de si el input es aceptado. (O tal vez solo hay que simular un comportamiento y me estoy ahogando en un vaso de agua pero la verdad es que no he podido comprender bien la pregunta). De antemano, muchas gracias.
