### ISSUE TITLE
[Materia] Detener el ciclo del reloj

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#46]
Hola! Hay alguna forma de detener el ciclo del reloj (es decir, parar el computador)? Si es así, cómo se diagrama?

Gracias

**Comment by lothardp** [comment]
Hola! No estoy seguro a qué te refieres con detener el reloj, pero la respuesta corta es no. El reloj del computador es simplemente un componenete que envia pulsos con una frecuencia constante, que pueden ser recibidos por los demás componentes para poder funcionar sincronicamente. No hay forma de "detenerlo" más que apagar el computador. 

Quizás lo que quieres es que el computador simule estar detenido (o haciendo nada) lo cuál se puede lograr con la instrucción NOP (la cuál no computa nada ni escribe en ningun registro ni en memoria). Mientras el computador ejecuta instrucciones NOP no esta haciendo "nada", pero el reloj sigue funcionando.

Espero que esto conteste tu duda.

**Comment by JJJGGGG** [comment]
No era eso realmente, te explico:
Hay muchos componentes del computador conectados al reloj de onda cuadrada del computador. Mi idea sería detener la onda cuadrada y que se quede en un valor (0 o 1) para siempre a partir de ese momento.

Creo que ya lo solucioné en todo caso, porque se puede hacer un enabler con la salida del reloj, que si el bit de control es 1 sigue dando output y si el bit de control es 0 entonces se queda en 0.

**Comment by lothardp** [comment]
Buena, si eso podría simular que el reloj se detiene (aun cuando realmente no lo hace). Aun así, no entiendo por qué querrías detener la onda del reloj. Saludos!

**Comment by Arcoirisky** [comment]
Acompañando a lo que dice @lothardp, ten cuidado con eso, porque cuando le des la posibilidad al Enabler de cambiar su valor, puede que en ese momento el clock esté en cualquier ubicación, lo cual te puede descontrolar la sincronización de tu componente ó incluso peor, dejarte pegado para siempre :CC 

Lo estarías dejando a tu suerte ;-;
