### ISSUE TITLE
T1 | Como usar shl y shr

### ISSUE THREAD

**Issue by ibaeza1** [IIC2343/Syllabus-2020-2#47]
Hola! 
Estaba tratando de usar el comando shl a,(b) en el emulador y me dice que la instruccion no existe. No se su es un bug o la estoy usando mal. Si la estoy usando mal, como se escribe bien? lo hice como dice en la tabla que esta en los apuntes pero me sale que no existe esa instruccion.
Gracias!

PD: Los comandos que se pueden ocupar en el emulador son solo los que aparecen en los apuntes o hay mas que no estan escritos? de ser asi seria bacan si nos pudieran dar una lista de los comandos que podemos ocupar :)

**Comment by jmwielandt** [comment]
Hola, esa instrucción no está soportada.
Sólo existen:
- `SHL A,A`: A = A << 1
- `SHL B,A`: B = A << 1
- `SHL (dir)`: mem[dir] = A << 1
Y lo mismo pero con SHR.

En los pdfs 4 y 5 están casi todas las instrucciones que se soportan. Eventualmente se subirá el 5.5 con la isa completa. En la ISA no están todas las instrucciones que el computador potencialmente podría ejecutar.

**Comment by ibaeza1** [comment]
Gracias! Tengo otra pregunta, si yo tengo por ejemplo un arreglo que tiene su primer elemento en el indice 3 entonces hago mov a,arreglo mi a seria 3. Es posible acceder al elemento que guarda a? porque se que no se puede hacer (a).
Mi pregunta al final seria que a es un indice y yo quiero ver el valor que guarda ese indice, hay alguna manera de hacerlo?

**Comment by inmadariaga** [comment]
Hola!
Lamentablemente no te puedo responder, ya que esperamos que se enfrenten y resuelvan por su cuenta este tipo de complicaciones respecto ala programación en el assembly del curso. Te recomiendo asistir a la ayudantía del lunes.
