### ISSUE TITLE
T1 | Comandos pregunta 3

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#48]
Hola entre buscar en google, y en los apuntes, no logro hacerme una lista de comandos que podemos usar y me siento muy limitado en el caso del emulador para hacer la pregunta.
Por ejemplo me encantaría usar MUL para multiplicar pero no funciona en el emulador. 
En ese caso, **podría pedir una lista con los comandos que acepta el emulador?** Y es que a cada vez que se me ocurre una manera de solucionar el ejercicio, me doy cuenta que no existe ese comando en el emulador.
Muchas gracias!

**Comment by jmwielandt** [comment]
Hola, en google no te va a salir nada porque el computador básico es algo que se inventó para este curso.

Entre los capítulos 4 y 5 de los apuntes (dentro de la carpeta capítulo 2) están casi todas las instrucciones que están definidas para el computador y son las mismas que soportan. Pronto subiremos el capítulo 5.5 con la lista completa.

El computador básico no tiene MUL, pero si algo no está soportado por hardware le puedes dar soporte por software ;)
Te recomiendo que le des una vuelta a los apuntes y no te limites a las instrucciones que ofrece (puedes usar varias para hacer una sola cosa).

Saludos y mucho ánimo!

**Comment by andresplass** [comment]
Pero por lo mismo en los apuntes sale MUL y tambien salen arreglos del tipo arreglo[X] para obtener el arreglo en el indice X. Luego lo pruebo en el emulador y ninguno funciona :( Sí logré crear mi propio multiplicador, pero si en este caso no podemos indentar arreglos, como cambiamos un valor dentro de éste??
Ya que al usar una variable externa, de la forma (var) siempre llevará a esa variable y no a la direccion en un arreglo que quiero cambiar.

**Comment by jmwielandt** [comment]
En qué parte de los apuntes sale MUL? Y lo de arreglo[X]?

Entre las páginas 18 del archivo `4 - Programabilidad.pdf` y 8 del archivo `5 - Saltos y Subrutinas.pdf` están creo que todas las instrucciones del computador (que son las mismas del emulador).

**Comment by andresplass** [comment]
En la pagina 8 de subrutinas justo al final de la página :(

Justo después de `Existen tres elementos necesarios para poder implementar una subrutina: poder entregarle
parámetros, poder recibir un valor de retorno y poder hacer la llamada a la subrutina, es
decir poder saltar a la subrutina y volver luego de que termine a una dirección de retorno que
apunte a la siguiente instrucción del programa.` Está MULT y [0] que implica que puede indentar un arreglo.

Pero está bien, ya logré hacer una multiplicación pero no he logrado poder cambiar valores de un arreglo, solo acceder a ellos, tal como lo especifiqué antes :/

**Comment by jmwielandt** [comment]
Ese es un ejemplo que parte al inicio de la página 9 con un código en java que queremos transformar en assembly y recién se termina de desarrollar en la página 11. Ya avisé para ver si explicitan este hecho.

![image](https://user-images.githubusercontent.com/37153467/93003162-c9ad0f80-f512-11ea-9516-152c9755df51.png)

Eso es más menos lo que nos gustaría tener, pero el resultado final real está en las páginas 10 y 11.
