### ISSUE TITLE
Emulador | [No BUG] Velocidad de ejecución de instrucciones

### ISSUE THREAD

**Issue by vndiaz1** [IIC2343/Syllabus-2020-2#49]
Hola, al probar mis códigos en el emulador apretando el botón **Iniciar**, este va ejecutando las líneas de instrucciones de forma más lenta (~0.5-1s) que si le voy haciendo click en el botón de siguiente instrucción. Esto afecta cuando los códigos son iterativos, ya que se hace lento y poco automático la forma de ir probándolos. Mi duda es si hay alguna forma de ejecutar las líneas de forma más rápida o por ahora lo más rápido es hacerle click de forma manual.

**Sistema operativo, versión del emulador y otros**
- Windows 10
- EMU 1.0

Gracias de antemano y saludos!

**Comment by inmadariaga** [comment]
Hola!
De momento el emulador no cuenta con una forma de controlar la velocidad de ejecución, esperamos versiones futuras de este cuenten con esa funcionalidad.
Mucho ánimo en tu tarea.
