### ISSUE TITLE
Enteros negativos y resta

### ISSUE THREAD

**Issue by akrebs2** [IIC2343/Syllabus-2020-2#5]
Hola!

Estudiando la materia de enteros negativos y resta, me surge la duda del por qué no se puede implementar la resta en un computador como una operación distinta a la suma. Entiendo que la necesidad de ocupar el complemento a 1 y a 2 viene dada por querer satisfacer la ecuación A + (-A) = 0. Pero no entiendo por qué no simplemente tratar de manera diferenciada la resta, en donde los dígitos se restan (valga la redundancia) en vez de sumarse, tal como uno lo hace a mano:

![Captura de Pantalla 2020-08-28 a la(s) 13 55 05](https://user-images.githubusercontent.com/37155646/91600529-1949e380-e936-11ea-8bb3-d449df2fb0fc.png)

No sé si me explico. Al final estamos ocupando el complemento a 2 ya que queremos que, un número **sumado** con su complemento a 2, de 0, en vez de restarlo directamente (una operación que puede ser codificada como algo distinto a la suma).

Gracias!

**Comment by frvalenzuela** [comment]
Hola @akrebs2 !

Una gran ventaja que tiene el complemento 2 es su eficiencia en memoria y en hardware, la que nos permite representar el conjunto de los enteros en **un solo tipo de dato**, y re-utilizar componentes como lo son los Full Adders. 

El tener una operación resta contrae nuevas complicaciones, como ¿qué pasa en el caso de donde el valor de arriba es menor al valor de abajo? Probablemente deberíamos ocupar un valor de carry, que cuando sea ocupado negará los valores hacia la izquierda del primer número, lo que significaría un nuevo componente distintos para hacer la resta, que funcionaría de forma aparte, y no podríamos aprovechar componente ya hechos.

Además de lo anterior, significaría replantear nuevos tipos de datos, quizás un dato para los naturales, y otro por los negativos, o quizás terminariamos con una forma complementaria de ver el complemento 2 y la suma, donde en vez de hacer todo sumando, sería todo restando, lo que también sería menos intuitivo de entender y analizar. 

En resumen, el hacer otro componente de hardware solo para representar la resta como nosotros normalmente lo utilizamos, puede significa un mayor costo, una mayor complejidad, o en el mejor caso un cambio de paradigma que llegaría a ser menos intuitivo (pensar todo como una resta en vez de como una suma). Y por lo mismo el complemento 2 junto de la utilización de Full Adders y negaciones resulta tan util y eficiente para hacer los cálculos en nuestro computadores.

Espero que se haya entendido, si tienes alguna consulta no dudes en comentar en esta misma issue.

Saludos!

**Comment by akrebs2** [comment]
Perfecto, muchas gracias!
