### ISSUE TITLE
Emulador

### ISSUE THREAD

**Issue by dabalada** [IIC2343/Syllabus-2020-2#50]
Hola, el uso del registro B esta muy limitado, no puedo operar B mas que para hacer un mov de una costante.
No puedo hacer comandos como ADD B,1 - SUB B,1 INC B,1 - MOV B,(A), entre otros comandos. Sin embargo si puedo hacer todo eso con el registro A. No se si esto es por un error mio o por un bug del emulador. me pordrian ayudar con esto?

Saludos

**Comment by jmwielandt** [comment]
Hola, sí. Es a propósito. No es error tuyo ni bug del emulador, es una limitación de la arquitectura (puesta así de forma deliberada hace muchos años).

![image](https://user-images.githubusercontent.com/37153467/93001570-48e81680-f506-11ea-8fb0-9dfa2149668b.png)

Si miras el diagrama, la entrada B de la alu sólo puede recibir una de las 4 cosas (registro B, literal, dout y un 0). Si no se puede hacer en el computador, no se va a poder hacer en el emulador.
