### ISSUE TITLE
T1 | 3a Caracteristicas del grafo

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#51]
Hola, quería saber si deberiamos aplicar un algoritmo que se preocupe de los ciclos y encuentre la ruta más corta entre los nodos o si me estoy complicando más de la cuenta. Pregunto porque para el grafo que dan en el archivo base_3a nos dan un grafo de ejemplo que tiene solo una ruta entre los nodos y ningun ciclo, por lo que en ese caso en particular un algoritmo simple funcionaría. 
Saludos!

**Comment by jmwielandt** [comment]
Hola, los grafos no dirigidos por definición tienen ciclos. En el del ejemplo hay infinitos caminos entre 0 y 2: [0, 1, 2], [0, 1, 0, 1, 2], [0, 1, 0, 1, 0, 1, 2], etc. por lo mismo.

Y sí, ciclos además de esos también son posibles.

Saludos!

**Comment by jmwielandt** [comment]
@gnacrur hola, mira el edit en el comentario que puse, por si no quedó claro.

**Comment by jptorres1** [comment]
Entonces ¿es necesario implementar una recursión en el caso de que un nodo tome un camino que no lo conduzca a su destino y, por lo tanto, deba volver a sí mismo para buscar otros caminos posibles? 

Y otra duda, podemos asumir que el grafo es conexo?

**Comment by StroveLight** [comment]
El grafo es con pesos?

**Comment by aaguilarg** [comment]
@jptorres1 
> Entonces ¿es necesario implementar una recursión en el caso de que un nodo tome un camino que no lo conduzca a su destino y, por lo tanto, deba volver a sí mismo para buscar otros caminos posibles?

 tu decides el algoritmo a implementar para resolver el problema que se plantea. 

>  podemos asumir que el grafo es conexo?

No, es posible que el grafo no sea conexo, asi que no puedes asumirlo.

@StroveLight 

> El grafo es con pesos?

No, el grafo es sin pesos.
