### ISSUE TITLE
Problemas con instalar emulador

### ISSUE THREAD

**Issue by FaZorrilla** [IIC2343/Syllabus-2020-2#52]
Hola,

Llevo 2 horas tratando de instalar PyQt5 en Ubuntu 18.04, pero me continua tirando error de que no existe setup.py. Despues de buscar multiples soluciones en internet y probarlas, todavia no puedo hacer funcionar la instalacion de PyQt5. 
Ademas de eso, trate de usarlo en Windows, pero por problemas de permisos (como siempre con Windows), no funciona tampoco y despues de probar varias cosas tengo muchos problemas con eso.

No se que hacer ya, no puedo correr el codigo del emulador porque me falta PyQt5 en Linux, pero en Windows me tira errores de permisos, por lo que tampoco puedo correrlo.

Quiero saber si hay alguna alternativa, ya que despues de estar mas de 2-3 horas solo tratando de hacer que funcione el emulador ya no se que hacer.

**Comment by jmwielandt** [comment]
Hola, tu cuenta de windows es de administrador? me llama la atención lo que comentas de los permisos (jamás he tenido ese tipo de problemas)... Lo puedes ver en Configuración > Cuentas, justo debajo del nombre.

**Comment by FaZorrilla** [comment]
Si es de administrador, pero por alguna razon me esta quitando permisos de algunas cosas, como uso de python. He tratado de correrlo ya como 1 hora pero no me deja y solo me tira errores.

**Comment by jmwielandt** [comment]
En qué carpeta tienes instalado python? `C:\Program Files`

**Comment by FaZorrilla** [comment]
Funciono en Windows.
Despues de pegarme en la cabeza por una hora.
Desintale Python -> Instale Python denuevo -> Instale PyQt5 -> Cambie permisos y Path -> Instale el emu_lib -> Success
