### ISSUE TITLE
T1 | [Emulador] ADD B, 1

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#54]
Hola, duda corta.

Al parecer nuestro computador no soporta la instrucción ADD B, 1. Pero, esta instrucción es soportada por los lenguajes modernos de assembly?

Gracias!

**Comment by jmwielandt** [comment]
Hola,

En el computador básico esta instrucción no se soporta porque el segundo argumento cuando tienes una operación de la alu, un registro y luego un número se corresponde al literal que sale de la memoria de instrucciones. Como la entrada B de la ALU es compartida tanto por el registro B como por el literal (y también la salida de la memoria de datos), no hay forma de que la ALU opere con dos valores distintos por la misma entrada y "nada" en el otro. Pongo el "nada" entre comillas porque algo hay, siempre, pero puede no estar definido porque no nos interesa. Sin embargo, las instrucciones de incremento que aparecen en la ISA se aprovechan del 1 que entra por el mux A para poder hacer precisamente un B += 1 (`INC B`), mem[b] += 1 (`INC (B)`) y mem[lit] += 1 (`INC (lit)`).

Ahora bien, en los lenguajes de assembly más modernos (como ARMv8) la cosa cambia porque en general tienen más de dos registros. x86 tiene 4 de propósito general (A, B, C y D), MIPS tiene 32 registros de propósito general pero que se usan de formas distintas según la convención de la arquitectura y ARMv8 tiene 31 registros de propósito general. Pongo captura de la documentación de ARMv8.

![image](https://user-images.githubusercontent.com/37153467/93017721-44247080-f5a1-11ea-934c-c6ad78f20f5a.png)

Como puedes ver, en ARMv8 las instrucciones de operatoria usan 3 argumentos (destino, operarando 1 y operando 2) en lugar de 2 como usa el computador básico.

![image](https://user-images.githubusercontent.com/37153467/93017782-b2693300-f5a1-11ea-82dd-d12dcf6e3199.png)

Es por eso que la pregunta de si "esa instrucción es soportada en assemblies más modernos" no tiene tanto sentido porque cada assembly es un mundo y menos mal que hoy en día usamos sólo 2 de forma cotidiana o nuestras vidas tanto a nivel de usuarios como de desarrolladores serían un poco más cercanas a un infierno (imagina tener que compilar no solo para sistemas operativos distintos, sino también para arquitecturas distintas... y luego tener que ver por qué un bug sólo aparece en una de ellas).

Saludos y mucho ánimo con la tarea, me pareció interesante responder esta pregunta porque no es algo de lo que uno tenga demasiadas oportunidades de hablar en el curso :D

**Comment by JJJGGGG** [comment]
Pero, no es posible poner en la unidad de control una instruccion más que ponga un literal en A, lo sume con el valor de B y lo guarde en B? Me parece que serían algunos cables y algunas compuertas lógicas más solamente

**Comment by jmwielandt** [comment]
> Pero, no es posible poner en la unidad de control una instruccion más que ponga un literal en A, lo sume con el valor de B y lo guarde en B? Me parece que serían algunos cables y algunas compuertas lógicas más solamente

Sí, pero eso sería modificar el computador básico y cambiar la arquitectura.
