### ISSUE TITLE
Materia | (A) y (B)

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#55]
Hola.

Estuve revisando los apuntes, y se indica que no existe la operación (A), por ejemplo
```
MOV B, (A)
```

Sin embargo, esta operación sí existe con B, por ejemplo:
```
MOV A, (B)
```
Por qué esto es posible para B y no para A?
Gracias.

**Comment by jmwielandt** [comment]
Hola,

Si te fijas en el diagrama que puse en #50 verás que hay un cable que parte del registro B y llega al mux address, cuya salida entra en el address de la memoria de datos. Sin embargo, no hay forma de pasar el valor de A al address de la memoria de datos porque no hay cables ni componentes para ello y por eso no se puede acceder al contenido **apuntado** por A, pero sí al que **apunta** B.

Saludos~

**Comment by DiegoEmilio01** [comment]
Hola, estuve viendo el diagrama y tiene sentido que `MOV (address), B` funcione. Sin embargo, `MOV (address), 3` no me lo reconoce aún habiendo un bus entre el mux address y los literales. Gracias de antemano.
