### ISSUE TITLE
T1 | P3.1 Posibilidad de no encontrar solución

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2343/Syllabus-2020-2#56]
Hola. Es posible que no se encuentre una solución, o siempre habrá un camino de n1 a n2 en el grafo?
Gracias

**Comment by Arcoirisky** [comment]
Hola! Sí es posible de que no exista un camino entre dos nodos del grafo~

**Comment by VicenteMerino** [comment]
@Arcoirisky Como hay que retornar la solución en dicho caso?

**Comment by aaguilarg** [comment]
@VicenteMerino , en caso de que no haya solución, retorna -1

**Comment by gnacrur** [comment]
Hola, con retornar se refieren a que el valor de res termine en -1? o el numero de aristas en caso de encontrar camino

**Comment by aaguilarg** [comment]
La respuesta que se debe entregar es el número de aristas que tiene el camino, y si no hay camino, su respuesta debe ser -1
