### ISSUE TITLE
T1 | Error al instalar el EMULADOR

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2343/Syllabus-2020-2#58]
Hola! 
Tengo este error al tratar de instalar el emulador:
"ERROR: emu_lib-0.1.0-cp37-none-win_amd641.whl is not a supported wheel on this platform."

Tengo python 3.78 de 64 bits, probé instalando y desinstalando python 2 veces, y haciendole upgrade a pip, también pip3, nada de esto parece funcionar.
¿Cómo lo puedo arreglar? :(
Sistema Operativo: Windows 18362.1082

**Comment by jmwielandt** [comment]
Hola,

1. Salió la 1.0.1 hace unos días, descarga los archivos nuevos pls.
2. Usa el comando `pip --version` y dime qué te tira.
3. Asegúrate de que el archivo whl está en la carpeta en la que estás ejecutando el comando. Esto es que lo que está antes del ">" se corresponda con la ubicación del archivo.
![image](https://user-images.githubusercontent.com/37153467/93030115-ff2b2900-f5f6-11ea-980a-f097d4e5b2c1.png)

Quedo atento~

**Comment by jfuentesg26** [comment]
Gracias por responder! 
Estoy tratando de instalar el archivo que descargue hoy aun así no funciona, mi python es 64 bits y mi versión de pip es  20.2.3.

**Comment by Arodriguez14** [comment]
Hola! Pudiste solucionar esto? Tengo el mismo problema

**Comment by jmwielandt** [comment]
@jfuentesg26 @Arodriguez14 voy a necesitar que den información más exacta con capturas de pantallas para poder ayudarlos bien.

**Comment by Arodriguez14** [comment]
Yo ya lo pude solucionar. Gracias!

**Comment by jfuentesg26** [comment]
Yo me cambie de computador, asi que no se preocupen!

**Comment by jmwielandt** [comment]
@jfuentesg26 ojalá puedas explicar qué era por si le sirve a alguno de tus compañeros ;)

**Comment by Arodriguez14** [comment]
Mi error estaba resuelto en la issue 37!
