### ISSUE TITLE
T1 | Abrir emulador 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2343/Syllabus-2020-2#59]
Hola!Logré instalar el emulador que dejaron , sin embargo , al ejecutar main.pyw no me abre el emulador.
![Captura de pantalla (107)](https://user-images.githubusercontent.com/62029138/93030620-b4131500-f5fa-11ea-8752-b8dc13fe69a2.png)
![Captura de pantalla (108)](https://user-images.githubusercontent.com/62029138/93030621-b6756f00-f5fa-11ea-8310-46fd7870229b.png)
![Captura de pantalla (109)](https://user-images.githubusercontent.com/62029138/93030675-300d5d00-f5fb-11ea-8805-77c443a4de96.png)
Esto es debido a que intento ejecutar main.pyw desde la carpeta equivocada o algo así?Si es así desde que carpeta debería hacerlo?

**Comment by jmwielandt** [comment]
Hola, el comando es al revés:

```
python main.pyw
```

Saludos~

**Comment by tocococa** [comment]
hola, @jmwielandt tengo un problema parecido. Logré instalarlo usando `pip install` y se crearon los archivos en `Lib`, pero no encuentro el archivo `main.pyw` en ninguna parte 😿 .

**Comment by jmwielandt** [comment]
@tocococa está en el archivo emu.zip

![image](https://user-images.githubusercontent.com/37153467/93031249-baf05680-f5ff-11ea-8434-2dea057b4416.png)

Tienes que descargarlo y descomprimirlo, está todo adentro

**Comment by tocococa** [comment]
😅gracias.

**Comment by RonaldoSosa** [comment]
Sii error mío :(. Muchas gracias !!!!!
