### ISSUE TITLE
Día de gracia para el 18 de Septiembre.

### ISSUE THREAD

**Issue by bpeirano1** [IIC2343/Syllabus-2020-2#60]
Hola!
Quería saber si es que existía la posibilidad de que los días de gracia para la entrega de la tarea 1 empiecen a contar desde el 19 de septiembre y no desde el 18 de septiembre. Esto debido a que el 18 es feriado nacional y probablemente muchas personas (incluyéndome) quieran compartir con sus familias y no trabajando en la tarea.  Al final lo pregunto por un tema de salud mental y no por un tema de tener más tiempo para trabajar en la tarea. Además, entendiendo el contexto de que muchos ramos cargaron su entregas y pruebas para esta semana.

Saludos!

**Comment by smrebolledo** [comment]
F

**Comment by jmwielandt** [comment]
Hola, como comentó el profesor en la clase del martes y se puede leer ahora en el [readme](https://github.com/IIC2343/Syllabus-2020-2#entregas-atrasadas), la entrega oficial es la entrega oficial que se pone en días hábiles, mientras que los días de gracia son pensados principalmente para cubrir todo tipo de imprevistos (cosas que ustedes consideren imprevistos) que puedan tener.

Vean el video para la explicación completa.
