### ISSUE TITLE
Bug Emulador | No reconoce SHR A, (Dir)

### ISSUE THREAD

**Issue by pxparga** [IIC2343/Syllabus-2020-2#61]
Hola! estoy trabajando en la versión 1.0.1 y traté de usar la instrucción SHR A, (Dir) pero me sale que no existe. En la tabla de instrucciones que vimos en clases si está. 

PD: SHR (Dir) si me funciona

**Comment by jmwielandt** [comment]
Hola,

Lamentablemente (¿o afortunadamente?) ese no es un bug en el emulador, sino un error en los apuntes (serán corregidos pronto). La tabla de las slides viene de los apuntes y por eso también está el mismo error.

La lista completa de instrucciones que detectamos que están malas ya que no son soportadas por el computador básico es:

- `NOT A,Lit`
- `NOT A,(Dir)`
- `NOT A,(B)`
- `SHL A,Lit`
- `SHL A,(Dir)`
- `SHL A,(B)`
- `SHR A,Lit`
- `SHR A,(Dir)`
- `SHR A,(B)`

Los apuntes y las slides de las clases serán corregidas pronto.
Mucho ánimo por la tarea y muchas gracias!

**Comment by pxparga** [comment]
Oka, gracias por la aclaración!

**Comment by jfpena1** [comment]
Hola entonces no esta soportado SHR de niguna forma? 
Gracias

**Comment by aaguilarg** [comment]
@jfpena1 , 
Si se soporta esa instrucción de las siguientes formas (como se indica en los apuntes):
```
SHR A,A
SHR B,A
SHR (dir)
```
(puedes asumir instrucciones homólogas con ```SHL```, y esto también ocurre con ```NOT```)
