### ISSUE TITLE
Duda ejercicio compilado endiannes

### ISSUE THREAD

**Issue by DanielaCorral** [IIC2343/Syllabus-2020-2#62]
Hola! Estaba viendo el compilado subido en el syllabus de ies pasadas y la verdad tengo muchas dudas en este ejercicio. En primer lugar no se por qué se asume que hay que pasar el número a hexadecimal, en segundo lugar no entiendo cual es la importancia de que el numero se almacene en 2 palabras, y en tercer lugar no entiendo cómo llegan al número -256 :cry: Disculpen lo perdida.
![duda compilado](https://user-images.githubusercontent.com/48497669/93037426-c8660a80-f618-11ea-9d01-f097bfd8cab4.png)

**Comment by Arcoirisky** [comment]
Déjame ver si puedo aclararte un poco, de usa hexa en la solución porque es más simple para la vista que el binario, sobretodo considerando que son 16 bits. 

Es muy distinto ver 0x00FF a 0000000011111111 aunque signifiquen lo mismo.

El porqué es tan importante el que se almacenen entradas de 2 palabras en vez de 1 es que según el endian con que se almacene influye en su lectura y en la escritura. Como lo puedes ver en este [pantallazo](http://ocw.uc3m.es/cursos-archivados/arquitectura-de-ordenadores/lecturas/html/drm.html#:~:text=A%20estas%20dos%20formas%20de,el%20byte%20de%20mayor%20significaci%C3%B3n.) a continuación:

![image](https://user-images.githubusercontent.com/26121402/93039085-02d1a680-f61d-11ea-9177-05de34c23586.png)

Y, finalmente, llegan al -256 por lo mismo que se ve en la imagen de arriba, estás leyendo el número al revés de como se escribió.

Dime si te quedan más dudas c:

**Comment by DanielaCorral** [comment]
Hola! me quedó super claro todo excepto la parte del -256. Esto porque, si bien entiendo cómo llegamos al 0xFF00 cambiando el sentido de lectura, tengo dos dudas:
1. ¿Cómo sabías que había que leerlo como un negativo y no simplemente hacer la transformación típica a decimal multiplicando cada símbolo por la base 16 elevada a la posición (15 * 16³ + 15 * 16² = 65280)?
2. Entiendo que los números binarios anteponen un bit de signo para saber si un número es positivo o negativo. En otras bases, por ejemplo en la hexadecimal, ¿cómo se codifica eso? 

Gracias! :smile:

**Comment by Arcoirisky** [comment]
1) Porque al inicio de la pregunta dice que se guarda un número entero y el programador también prueba con un entero.

2) la hexadecimal funciona de la misma forma que el binario, es una de las gracias que sea potencia de 2. 

ahora, si me preguntas por otras bases, tipo 3, 5, 7, etc, no sabría decirte a ciencia cierta si se sigue la misma regla, no he investigado/probado más allá de sacar complemento en otras bases como para darte una respuesta 100/10 verídica. Seguramente habrán papers al respecto, es cosa de buscar un poco supongo.

**Comment by DanielaCorral** [comment]
Perfect entonces solo por el hecho de que se guarda un entero asumimos que viene con un bit de signo. Todo claro! Muchas gracias :smile:

**Comment by Arcoirisky** [comment]
Casi, no usamos bit de signo, usamos complemento de 2

**Comment by smrebolledo** [comment]
No afecta en nada que el número esté almacenado en la posicion 0x12?

**Comment by frvalenzuela** [comment]
Hola @smrebolledo !

No, no afecta, es dato de contexto.

Saludos!
