### ISSUE TITLE
T1 | 3a, mas de una forma de conectar los nodos

### ISSUE THREAD

**Issue by FelipeSrojas96** [IIC2343/Syllabus-2020-2#63]
Hola,

Que pasa si tengo por ejemplo este grafo
![image](https://user-images.githubusercontent.com/37755121/93052511-a8484280-f63c-11ea-91b2-80c37642b65c.png)

y me pidieran la distancia de B a D, en este caso podria ser 2 o 3, o para la tarea solo se consideran casos en los que hay una ruta unica para llegar? 

saludos

**Comment by jmwielandt** [comment]
@FelipeSrojas96 Hola, como comento en #51 cualquier grafo no dirigido por definición tiene ciclos y, además, la distancia entre dos nodos se define a partir de la ruta más corta.

Saludos!
