### ISSUE TITLE
T1 | Emulador

### ISSUE THREAD

**Issue by josejimenezp** [IIC2343/Syllabus-2020-2#64]
Hola, cuando pongo cargar el archivo de base me arroja un error en la consola y en el emulador no me muestra nada (no me salen mis instrucciones ni los datos en la memoria). Sin embargo sin el archivo base si me aparecen. Hay algo que deba modificar, además de los '#' que ya saqué? Gracias!

![image](https://user-images.githubusercontent.com/48298035/93088657-97b1bf80-f670-11ea-97fd-d2ce56b37c59.png)

**Comment by jmwielandt** [comment]
Hola, mira la issue #32 
No tienes que sacar las sentencias con # ya que son importantes para la corrección.
Avísame si te sigue dando error una vez sigas los pasos.

**Comment by JJJGGGG** [comment]
Hay algun manual de ejecucion del emulador que incluya el uso de los #? Tengo lista la 3.a pero no entiendo cómo debo entregar los archivos. De momento tengo 1 sólo .txt al que se le deben poner manualmente las matrices y datos iniciales

**Comment by VicenteMerino** [comment]
@jmwielandt No entiendo bien como es lo que hay que entregar, ya que en el ejemplo de la issue [32](https://github.com/IIC2343/Syllabus-2020-2/issues/32) si sacas la seccion #import-data y #import-code y lo reemplazas con la parte del código.

**Comment by VicenteMerino** [comment]
@jmwielandt  Olvídalo, creo que ya entendí, me faltó leer una parte.

**Comment by jmwielandt** [comment]
> Hay algun manual de ejecucion del emulador que incluya el uso de los #? Tengo lista la 3.a pero no entiendo cómo debo entregar los archivos. De momento tengo 1 sólo .txt al que se le deben poner manualmente las matrices y datos iniciales

Sí, en la issue #32 se explica con un ejemplo. Dime si tienes dudas al respecto.
