### ISSUE TITLE
T1 | Emulador en Mac no reconoce algunas instrucciones

### ISSUE THREAD

**Issue by sjkinast** [IIC2343/Syllabus-2020-2#65]
Hola! tengo la versión actualizada del emulador, sin embargo, todavía no me reconoce las  mismas instrucciones. Por ejemplo: INC A; MOV B, (A). Por ejemplo esta secuencia de código falla:
DATA:
    vector1  1, 3
    var1 0

CODE:
    MOV A,vector1
    ADD A,1  ; como no hay INC uso esto
    MOV B, (A); esto falla y se ejecuta de la misma forma en los apuntes
    MOV (var1), B

Adjunto foto de apuntes:
![image](https://user-images.githubusercontent.com/37150014/93101756-0e56b900-f681-11ea-8bc4-241265ead174.png)

**Comment by jmwielandt** [comment]
Hola, en los apuntes (foto que adjuntas) lo que está entre paréntesis es B, no A.
INC A y MOV B,(A) no existen (ver #50 #54 #55 )

No están soportadas por el computador básico así que no existen en el emulador.
