### ISSUE TITLE
T1 | P3 Modificar valores labels predeterminados

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#66]
Hola, no me queda muy claro la parte del enunciado que dice:

> Estos labels no pueden ser usados en sus respuestas finales, ya que serán de uso reservado para el corrector automático.

Esto quiere decir que no podemos modificar los valores almacenados en estos labels durante la ejecución de la sección CODE, o si se podría hacer?

**Comment by felipearellanom** [comment]
Esto significa que en la version final de tú código dentro de DATA: no puedes mencionar a label_reservada, pero si dentro de CODE: haces por ejemplo MOV A,(label_reservada) va a funcionar sin problema.
