### ISSUE TITLE
Posible Bug Emulador | MOV A,M no funciona correctamente 

### ISSUE THREAD

**Issue by SergioZarateG** [IIC2343/Syllabus-2020-2#68]
**Descripción del bug**
En la pregunta 3a al querer realizar la instrucción MOV guardando en el registro A la posición donde se encuentra indexado M, el emulador me dice que mi instrucción no existe, ya que transforma el MOV a 3OV. Esto ocurre solo con MOV A,M. Si cambio el M por m el emulador funciona correctamente. Según lo que pude ver, el M se remplaza por el indice donde se encuentra M en memoria.

**¿Cómo reproducirlo?**
DATA:
M 	0,1,0,1,0,1,0,1,0

CODE: 
MOV A,M

**Comportamiento esperado**
MOV A,M deberia guardarme en el registro a el indice donde esta indexado en memoria M, sin embargo lo tranforma a 3OV, arrojando el siguiente error: _"La instrucción 3OV A,0 no existe."_ 

**Sistema operativo, versión del emulador y otros**
- Indica tu sistema operativo: Windows
- Indica con qué versión del emulador estás trabajando: versión 1.0.1 (la que publicaron el viernes)

**Comment by JJJGGGG** [comment]
No soy ayudante, pero este bug está confirmado en la #44. Dicen que lo arreglaron en la 1.1 del emulador.

**Comment by Arcoirisky** [comment]
Ese problema fue arreglado según la issue #44, intenta descargando la nueva versión del emulador o:!
