### ISSUE TITLE
Acceso a Syllabus anteriores

### ISSUE THREAD

**Issue by Drpinto1** [IIC2343/Syllabus-2020-2#7]
¡Hola!

Estaba revisando el README del Syllabus y noté que tiene listados los Syllabus de semestres anteriores, sin embargo no tengo acceso a ellos :o

¿Es esto intencional o deberíamos poder entrar?

¡Saludos!

**Comment by jmwielandt** [comment]
Hola,

como comentó el profesor en clases, estamos revisando lo que está disponible en esos repositorios ya que no todo puede quedar público (links a planillas de notas, por ejemplo).

Eventualmente les informaremos qué pasará con ello y demás.

Saludos~
