### ISSUE TITLE
T1 | 3.a problemas con las instrucciones ADD A,var e INC A

### ISSUE THREAD

**Issue by bpeirano1** [IIC2343/Syllabus-2020-2#70]
Hola! 
Estaba probando cómo funciona el emulador para trabajar en la tarea y al poner:
mov A, M
add A, (N)
Me dice que la operación add A, (N) no exite, no entiendo por que no soporta esa operación.

También trate de hacer "INC A" , cuando en el emulador se tiene que A=3 y me  dice "La instrucción INC A no existe.", tampoco entiendo por qué no me deja hacerlo

Saludos

**Comment by Arcoirisky** [comment]
Antes que nada ¿tienes la última versión del emulador? Porque en #44 se habla del Mov A, (M) específicamente.

**Comment by bpeirano1** [comment]
Me descargue el emulador el viernes por lo que debería tener la última versión! Igual lo voy a revisar de nuevo. Cómo puedo saber que versión del emulador tengo descargado?
En todo caso no me ocurre el mismo output que el problema en la issue #44

**Comment by bpeirano1** [comment]
Hola! según lo que tengo descargado es la versión 1.0.1. 

Adjunto una foto de mi carpeta donde esta el emulador por cualquier duda.
![Captura](https://user-images.githubusercontent.com/48304247/93164844-f159ce80-f6f0-11ea-8199-e6718e001ffd.PNG)

**Comment by michimalonko** [comment]
INC A no esta soportado, si ves la tabla solo se puede INC B, INC (B) y INC (dir), lo de add, a mi me funciona bien, quizas estas juntando la palabra add con la A asi como: addA ,(N)

**Comment by jmwielandt** [comment]
@bpeirano1 es lo que dice michimalonko

INC A sería un ADD A,1 como dijo el profe en la clase y lo del add a,(dir) me parece extraño. Prueba este código y dime si no te funciona por algún motivo:

```
DATA:
    var 5
CODE:
    mov a,5
    add a,(var)
```
