### ISSUE TITLE
T1 | 3a límite excedido en los registros

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#71]
Hola, me he dado cuenta que los registros no superan el número ~127, y al intentar probar una matriz de adyacencia, nunca podía acceder a ella, ya que tiene tamaño 144 y el registro nunca va a llegar tan alto, hay otra forma de acceder a su dirección?

**Comment by mc-cari** [comment]
Una matriz de adyacencia de 12 nodos*

**Comment by movalle4** [comment]
Hola!

Esto no debería pasar. Si quieres puedes reportarlo cómo bug. Si tu reporte es correccto te pueden dar décimas extra. La issue #44 es un ejemplo de cómo reportar un bug.

**Comment by mc-cari** [comment]
Ok, gracias
