### ISSUE TITLE
Bug Emulador | Direcciones de memoria inalcanzables

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#72]
**Descripción del bug**
Los números guardados en los registros son con signo, por lo que llegan hasta el número ~127, pero la memoria es más grande, entonces no se puede acceder a una dirección mayor a es número
**¿Cómo reproducirlo?**
Al intentar MOV A,0 - ADD A,128 el resultado es -128, entonces si tengo una dirección de memoria DIR = 128, e intento MOV A,0 - ADD A,DIR - MOV B,A, MOV B,(B), ocurre el error "18446744073709551522 es una dirección de memoria virgen!"

**Comportamiento esperado**
El valor del registro debería tener el mismo rango que el de la memoria, así poder acceder a la totalidad de las direcciones de memoria

emu_lib-1.0.1-cp37-none-win_amd64.whl
- Windows 10
- EMU CB - 1.0.1

**Comment by jmwielandt** [comment]
Dame tu correo pls

**Comment by mc-cari** [comment]
Es mauricio.cari@uc.cl

**Comment by jmwielandt** [comment]
_Corregido en la 1.0.2_
