### ISSUE TITLE
T1 | P1 Asignacion de valor al "100b"

### ISSUE THREAD

**Issue by Clemente24** [IIC2343/Syllabus-2020-2#74]
Hola!

Tengo una duda respecto del valor que toma el 100 , en una representación en base 2 con, por ejemplo, 3 dígitos. Asumiendo que quiero representar enteros con signo:

El conjunto de números que tengo es: {000, 001, 010, 011, 100, 110, 101, 111}

Tendremos que:                             000 = 0,    001 = 1,  010 = 2,   011 = 3
Y sus respectivos complementos a 2 seran:   111 = -1, 110 = -2, 101 = -3

Ahora es cuando me entra la duda, con el complemento a 2 de 100. C_2(100) = 100. No entiendo qué valor se le de debe asignar a ese número, puesto que no tiene un complemento positivo. En primer lugar pensé que dado que tenía un "1" por delante, podría ser el "-0", pero entiendo que eso sería leer el primer bit como bit de signo y me parece que eso no es correcto. Luego en unos apuntes vi que se le asignaba el valor "-4", pero no veo por completo el por qué.

En resumen; ¿cómo saber qué valor debe tomar ese número? Y análogamente el 10, 1000, 10000...

Gracias!

**Comment by movalle4** [comment]
Hola!

En complemento a 2, el inverso aditivo B de un numero A cualquiera es tal que A + B = 0.

Entonces, para encontrar el inverso aditivo de "100b" debes restarle "1b". Esto te da "011b". Luego debes negar los bits. Con esto queda "100b". Por lo tanto el complemento de "100b" es "100b" en complemento a 2 para números de 3 bits ya que "100b" + "100b" = 0.

Ahora, ¿por qué es -4?

Por convención, si la palabra empieza con 1 significa que el número es negativo. Entonces "100b" sería el número -4.

En resumen, para palabras de 3 bits en complemento a 2, -4 es el inverso aditivo de -4.

**Comment by Clemente24** [comment]
Gracias, me queda más claro!
