### ISSUE TITLE
T1 | No encuentro la ultima versión del emulador (1.0.2)

### ISSUE THREAD

**Issue by gustavo-toro** [IIC2343/Syllabus-2020-2#75]
Hola, lo que me pasa es que en releases no me aparece un archivo emu.zip. Descargué un archivo comprimido y lo que contenía era el contenido del syllabus. No sé si estoy haciendo algo mal o tengo que descargar otro archivo.
Muchas gracias.

**Comment by jmwielandt** [comment]
@gustavo-toro ya está subido, gracias por avisar
