### ISSUE TITLE
Bug Emulador | JEQ

### ISSUE THREAD

**Issue by conikuschel** [IIC2343/Syllabus-2020-2#78]
**Descripción del bug**
Tengo un salto condicional JEQ, en donde el emulador me marca Z=1, pero no realiza el salto al label indicado.

**¿Cómo reproducirlo?**
No puedo poner el código completo, dado que son funciones dependientes, pero básicamente en un i = N, que va decreciendo en 1 por cada ciclo y cuando llega a 0 se levanta el Z=1 en el emulador pero no entra al label final
func1:
        MOV A,(i)
        ADD A,-1
        MOV (i),A
        JEQ final
        MOV A,(N)
        MOV (ind),A
final:

**Comportamiento esperado**
Que realizara el salto a final

**Sistema operativo, versión del emulador y otros**
- Windows
- 1.0.1

**Comment by jmwielandt** [comment]
![image](https://user-images.githubusercontent.com/37153467/93230957-a66ea400-f74e-11ea-8e33-f1c8d36521ce.png)

Acabo de probar esto y funciona bien. Dime si entendí algo mal.

**Comment by conikuschel** [comment]
Sii, es eso, pero después de pasar por JEQ final me tira hacia otra función y no termina. Aquí te muestro justo antes que entre a JEQ y después.
![image](https://user-images.githubusercontent.com/48297866/93233191-2dbd1700-f751-11ea-98aa-592bf32976a5.png)
![image](https://user-images.githubusercontent.com/48297866/93233262-3f9eba00-f751-11ea-8da3-ae2df7f9ddf1.png)

**Comment by jmwielandt** [comment]
Ehh... eso está bien.
Cuando entras al JEQ 4 Z es 1, por lo que va a saltar
y al avanzar al siguiente ciclo carga el nuevo valor del PC que es 4, tal como sale en JEQ 4

**Comment by conikuschel** [comment]
Pero al entrar a mi función "final" debería terminar, y lo que veo es que se va a otra función, de hecho esta entrando a la misma función que estaba, no se si estoy entendiendo algo mal, pero poniendo mi función final: vacía al terminar todo lo que hay en CODE: debería finalizar o no?

**Comment by jmwielandt** [comment]
los labels no son funciones, son marcadores para no anotar las direcciones de memoria a mano. Y el código en assembly no es sensible al contexto: les da igual si estás en una subrutina o no. En este caso, ve una instrucción que es `JEQ 4` y que `Z` vale 1, por lo que en el siguiente ciclo va a ejecutar la instrucción que está guardada en la dirección 4 de la memoria de instrucciones.

Por lo que veo en las capturas del emulador, el código que pusiste en la primera issue no se corresponde con el que tienes en el emulador. Lo que estás haciendo es:

```
nop  ; pongo "nop" porque no sé qué había, da lo mismo
nop
nop
nop
final:
mov a,(13)
add a,-1
mov (13),a
jeq 41
...
nop
mov a,(15)
add a,-1
mov (15),a
jeq final
```

**Comment by conikuschel** [comment]
Si, si entiendo lo de los marcadores, pero mi código como te había dicho es algo así, por lo que entrando a final no debería hacer nada, por lo que entiendo :(

![cod](https://user-images.githubusercontent.com/48297866/93244459-25200d00-f760-11ea-9459-3aaa9b01dcb2.png)

**Comment by movalle4** [comment]
Tu código no va al label "final" porque es necesario tener una instrucción después del label para tener una instrucción a la que saltar.

Para que te funcione el jump al label "final" puede hacer esto:

```
final:
    JMP final 
```

Ahora si en tu programas llegas a final se va a quedar en un loop infinito.

**Comment by movalle4** [comment]
Si no quieres que haya un loop infinito puedes poner:

```
final:
    NOP
```

Lo importante es poner alguna instrucción despúes del label. Todas las instrucciones tienen un número (el número que lleva la cuenta el Program Counter del computador). Los labels al no ser instrucciones no tienen un número y por eso no se puede saltar a ellas.

**Comment by conikuschel** [comment]
Perfecto, perdón lo insistente, muchas gracias!

**Comment by jmwielandt** [comment]
@conikuschel manda ese código al mail del curso porfa, quiero comprobar algo (iic2343@ing.puc.cl)
