### ISSUE TITLE
T1 | Límite de registro en emulador 1.02

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#79]
Hola, todavía el límite de los registros llega a 127 y no me deja acceder a indices de memoria mayores, tal vez se llega a un número más alto de otra forma o instale mal la nueva versión?

**Comment by movalle4** [comment]
Hola!

¿Seguro que no te funciona?

Probé con el siguiente código y sí me funcionó

```
DATA:

CODE:
    mov a,5
    mov b,144
    mov (b),a
```

**Comment by mc-cari** [comment]
Si funciona, entonces debe ser solo un bug en mi código, gracias.
