### ISSUE TITLE
T1 | 1)b) Orden interpretación de float y endiannes

### ISSUE THREAD

**Issue by jfpena1** [IIC2343/Syllabus-2020-2#8]
Hola, quería saber si es relevante para la 1b) el **orden en que se aplican** las instrucciones de : a) interpretar como float y b) cambiar el endiannes.

Muchas Gracias

**Comment by frvalenzuela** [comment]
Hola @jfpena1 !

El orden **si es relevante** ! Cuando se refiere al endiannes es la lectura del dato, para acceder a él, por lo que primeramente accedemos al dato, que sería lo que marcaste como **b)** y luego se interpreta el dato, lo que marcaste como **a)**. 

Entendemos la confusión que esto pudo brindar, cuando se agregue la pregunta 3 será redactado de mejor forma, pero escencialmente lo que escribí en el párrafo anterior es la forma de apróximarse al ejercicio.

Saludos!
