### ISSUE TITLE
T1 | 3.b Caso base

### ISSUE THREAD

**Issue by michimalonko** [IIC2343/Syllabus-2020-2#80]
En la pregunta 3.b se reciben inputs de tamaño [0, 50], en el caso de ser 0, que debo retornar? ya que no hay mediana

**Comment by movalle4** [comment]
Hola!

En caso de que el largo del arreglo sea 0, debes retornar -1

**Comment by VicenteMerino** [comment]
De que manera el largo del arreglo sería 0, no me hace sentido porque eso sería que el array no esté en data y arrojaría error,

**Comment by movalle4** [comment]
Buen punto.

El profesor dijo que en clases le preguntaron. Respondió que el largo de los arreglos va a ser entre [1, 50] para hacerlo más fácil para todos.

**Comment by VicenteMerino** [comment]
Gracias
