### ISSUE TITLE
T1 | P1.d Modo de ejecución

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#81]
Hola, sigo sin entender bien como es el modo de ejecución de la pregunta 1.d en python en cuanto a la validación del input.

Ustedes correran algo así python sucesor.py [1,5,8,3,14,45] y el segundo argumento (la lista que acabo de escribir) será el input del programa o simplemente lo modificarán internamente en el código que yo hago. No se si podrían explicar mejor esta parte.

**Comment by movalle4** [comment]
Hola!

La idea es que escribas una función en python llamada sucesor que reciba una lista de ints y retorne una lista de floats.

Algo así:

```
def sucesor(lista_ints):
   ...
   return lista_floats
```

No te preocupes por cómo se va a recibir el input. Los correctores van a probar la función. Solo debes preocuparte de hacer la función.

**Comment by Bneya** [comment]
Hola @movalle4, puede esta función llamar a otra función dentro de sí? Por ejemplo

```python
def sucesor(lista_E):
    hola = hacer_algo()
    return hola
```

Gracias

**Comment by movalle4** [comment]
Sí puede
