### ISSUE TITLE
Bug Emulador | Error al usar CMP con una dirección de memoria mayor a 127

### ISSUE THREAD

**Issue by mc-cari** [IIC2343/Syllabus-2020-2#82]
**Descripción del bug**
Al intentar comparar un registro con una dirección de memoria mayor a 127 falla e intenta acceder a una dirección errónea, ocurre el error:  "18446744073709551504 es una dirección de memoria virgen!"

**¿Cómo reproducirlo?**
DATA:

CODE:
    mov a,5
    mov b,144
    mov (b),a
    cmp a,(b)

**Comportamiento esperado**
Acceder a Mem[b] y comparar con a correctamente

**Sistema operativo, versión del emulador y otros**
Windows 10
emu_lib-1.0.2-cp37-none-win_amd64.whl

**Comment by jmwielandt** [comment]
corregido [1.0.3](https://github.com/IIC2343/Syllabus-2020-2/releases/tag/1.0.3)
