### ISSUE TITLE
Cantidad de memoria disponible

### ISSUE THREAD

**Issue by vjlira** [IIC2343/Syllabus-2020-2#83]
Hola! ¿Podrían dar más memoria para datos? o que prueben con matrices no tan grandes? 
O el desafío también va por el uso de memoria? 
Con matrices de hasta 8x8 no tengo problema, pero para más grandes se me acaba la memoria.
Gracias

**Comment by movalle4** [comment]
Hola!

Trata de buscar otra manera de resolver el problema. No se debería necesitar tanta memoria. Quizás te puede servir resolver el problema en python o en otro lenguaje y después traducirlo al assembly.

Suerte

**Comment by jmwielandt** [comment]
@vjlira revisa la 1.0.3, puede que tu problema de memoria haya sido por el bug que soluciona
