### ISSUE TITLE
Bug emulador | Comando SHL

### ISSUE THREAD

**Issue by vchadwick** [IIC2343/Syllabus-2020-2#84]
**Descripción del bug**
Cuando hago SHL del número 88: (01011000)b, retorna número -80 (11010000)b

**¿Cómo reproducirlo?**
mov a, 88
shl a, a

**Comportamiento esperado**
Debería retornar -48: (10110000)b

**Sistema operativo, versión del emulador y otros**
- Indica tu sistema operativo: Mac
- Indica con qué versión del emulador estás trabajando: 1.0.2
- Añade cualquier información que pueda ser de utilidad

**Comment by jmwielandt** [comment]
Creo que estás transformando mal a binario o aplicando mal los complementos. 1011_0000 b es -80.

![image](https://user-images.githubusercontent.com/37153467/93339649-391c4b00-f802-11ea-8588-03b8ca33d6f3.png)

Lo hice a mano para comprobarlo:
![image](https://user-images.githubusercontent.com/37153467/93339981-a0d29600-f802-11ea-9831-b23f717290f8.png)

**Comment by vchadwick** [comment]
Hola @jmwielandt tienes toda la razón! Estaba confundido con los contenidos.
Entonces cuando quiero pasar de un binario negativo a su decimal, siempre tengo que buscar primero su complemento a 2, luego obtener su valor en decimal y por ultimo anteponerle un (-) o no??
Gracias
