### ISSUE TITLE
T1 | 3.b Límite de ticks

### ISSUE THREAD

**Issue by josejimenezp** [IIC2343/Syllabus-2020-2#86]
Hola, que pasa si es que estoy seguro que mi código en teoría hace lo pedido pero no se puede ver porque supera el límite de ticks? 😞

**Comment by jmwielandt** [comment]
Hola,
Lo puedes cambiar en el my_back.py, pero me parece raro que estés superando los 30 mil ticks. Actualmente el límite puede llegar hasta 18.446.744.073.709.551.615 ciclos. No supongas que si se demorara más tiempo de eso funcione (a menos que lo demuestres correctamente estilo matemáticas discretas?). Probablemente hay algo que esté funcionando mal y no te hayas dado cuenta todavía :/ 

Mucho ánimo!

**Comment by nlecaros1** [comment]
Hola, 
¿Se puede aumentar la cantidad de ticks? En la 3.b con 50 elementos (el máximo) en el arreglo mi programa necesita cerca de 65.000 ciclos, pero llega a la respuesta. Para arreglos más chicos (alrededor de 17) demora 7.000.

**Comment by jmwielandt** [comment]
Hola @nlecaros1 
Como dije justo arriba, el límite ya puede ser aumentado. El profe habló un poco del formato de corrección de la p3 en la clase del martes.
Si tu solución llega a la respuesta correcta no deberías preocuparte. De todas formas te animo a revisar si puedes condensar dos instrucciones en una o similar.
Saludos!
