### ISSUE TITLE
T1 | Valor de "res" P3.b

### ISSUE THREAD

**Issue by andrescf** [IIC2343/Syllabus-2020-2#87]
Hola! Para la 3.b dice que hay que guardar en res el indice de la mediana, pero por ejemplo en el caso base (arr: 1, 2, 3, 2, 4, 5, 1, 8, 8, 7, 3) la mediana es el 3 pero hay dos indices con el valor 3 ¿importa cual indice retorne o tiene que ser el de indice mayor o menor?

**Comment by VicenteMerino** [comment]
en otra issue dijeron que podiai elegir, así que da lo mismo

**Comment by andrescf** [comment]
Dale gracias!

**Comment by felipearellanom** [comment]
Efectivamente se discutio en la issue #39
