### ISSUE TITLE
T1 | P2.a y 2.b

### ISSUE THREAD

**Issue by sgutgar** [IIC2343/Syllabus-2020-2#88]
Hola, no me queda claro el nivel de abstracción que debo tener en la 2.a, pues como dice en la descripción informal de la maquina de turing en el link dado, una maquina puede tener un alfabeto finito, en este caso si este fuera de 50 variables, tengo que explicar lo que por ejemplo haría mi "ALU" en cada caso para retornar lo deseado si por ejemplo le entrego el estado y mi cinta actual? 
Y para la 2.b tendría que acaso dejar especificado cada opcode o hacer un general.

O simplemente tengo que pensar en la maquina de turing con 0 y 1.

**Comment by jmwielandt** [comment]
Típicamente el alfabeto es { 0, 1, B }, donde B representa "Blanco", es decir, una celda que no ha sido escrita.

Con sólo eso es suficiente para simular cualquier máquina equivalente pero con un alfabeto más grande. En la clase se discutió un poco si se podía usar sólo 0 y 1 en el alfabeto y técnicamente se puede, pero los números te quedarían en base unaria (por ejemplo).

---

## Mini aclaración sobre las máquinas de turing

Una máquina de turing es el modelo de computador teórico que usamos hoy en día. No está pensado para ser un computador especialmente eficiente sino para representar el mismo poder de cómputo y en esta línea el principal uso es demostrar si un problema es o no decidible (aka. puede ser resuelto por un computador o no. Ver problema de la parada.).

Lo típico es que una TM (turing machine) determinista (lo que se pide) tenga: 1 cinta infinita hacia ambos lados (izquierda y derecha) donde se escriben símbolos, 1 lista de estados, 1 estado actual, 1 cabeza lectora, 1 alfabeto finito y 1 tabla de transiciones (o una función de transición, a efectos prácticos es lo mismo). La cabeza lectora lee, escribe y se mueve por la cinta.

No es una función que "retorne" cosas propiamente tal.

## Ahora respecto a la pregunta 2

Lo que tienen que hacer es el diagrama de un computador de la misma forma que diagramamos el computador básico y dar las especificaciones de su funcionamiento. Pueden tomar supuestos y tienen total libertad creativa más allá de cumplir con lo pedido. Pueden representar de forma más o menos directa los componentes, tener el comportamiento exacto o emularlo, etc. Lo que hagan es decisión de ustedes, lo que nosotros describimos en la pregunta es el resultado esperado, no el procedimiento que deben realizar.

Esto se habló en la clase del martes, por cierto.

Saludos y espero haber contestado tu pregunta :D
