### ISSUE TITLE
T1 | Libreria numpy

### ISSUE THREAD

**Issue by michimalonko** [IIC2343/Syllabus-2020-2#89]
Se puede usar numpy para responder la 1.d?

**Comment by jmwielandt** [comment]
Hola,

Si lo que vas a usar te resuelve la tarea, no puedes (lo comentó el profe en clases). De todas formas sería mejor que nos cuentes por iic2343@ing.puc.cl el uso que le quieres dar a la librería, ya que es extremadamente grande y a priori se puede hacer difícil responder.

Saludos!
