### ISSUE TITLE
Duda materia complemento

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#9]
Hola, tengo una duda respecto a como funciona los complementos. Me surgió la duda por la pregunta 1.c de la tarea pero es más de materia. 
Respecto al complemento a n, vimos que debíamos agregar un 0 a la izquierda como paso 1. Tengo claro que esto no es siempre necesario (a excepción del complemento a 2). Lo que no entiendo es si este 0 a la izquierda se le agrega al numero del cual busco el complemento o solo el complemento lleva ese 0. O alternativamente, si es que yo defino una cierta cantidad de bits y de todos los números que puedo generar con ellos la primera mitad sería positiva y la segunda negativa. Mi duda surge porque no se si siempre debiesen tener la misma cantidad de bits un numero y su complemento o no. Por ejemplo, puedo representar el 3 en base 2 como 11. Pero si no me equivoco, su complemento es  101. Entonces ¿el 3 lo debiese representar como 011 para que el computador lo entienda?
Se que mezclo muchos conceptos pero por mi confusión me esta costando expresarlo mejor. 
Gracias!

**Comment by Arcoirisky** [comment]
Hola~ Déjame ver si entendí bien tu pregunta

tanto 11, 011, 00..0011 son la representación de 3 en binario, la única diferencia está en la cantidad de "cifras" con las cuales se representan (2, 3, hasta N respectivamente). 

Un computador trabaja con una cantidad fija de bits ("bits" porque trabajamos en binario), en este caso digamos que 8. Entonces, si queremos representar el 3 en ese computador nosotros **por comodidad** usamos 11 pero el computador lo recibe e interpreta como 00000011. Es decir, asumimos que el computador se encarga de "rellenar con ceros" según sea necesario. Repito, sólo por comodidad nuestra nos ahorramos esos ceros pero estos existen, es por eso que no tienes que preocuparte por representar el 11 como 011, el computador ya lo hace. De hecho, el complemento de 11 el computador lo ve como 11111101, lo puedes comprobar sumando 11 + 101 y ver que te da 0:

0 0 0 0 0 0 1 1 + 1 1 1 1 1 1 0 1 = 1 0 0 0 0 0 0 0 0

Como puedes ver, el número resultante necesita 9 cifras para ser representado, pero el computador solo puede trabajar con 8, por lo tanto el último bit "muere" y quedas con 00000000 = 0'b = 0.

Oh, cuidado con lo que dices aquí:

> si es que yo defino una cierta cantidad de bits y de todos los números que puedo generar con ellos la primera mitad sería positiva y la segunda negativa.

En complemento a 2 no divides en mitades iguales la representación de negativos con positivos. Esto sólo ocurre con el complemento a 1. 

Si aún no te queda claro sobre cómo funciona el complemento a base 2 te sugiero revisar este --> [link](http://aprendeenlinea.udea.edu.co/boa/contenidos.php/8b077438024e1bddfbc83706da8049f2/138/1/contenido/contenido/s_numericos.html) <-- donde te lo explican con ejemplos bien buenos la verdad, incluyendo otras bases. 

Quedo atenta si te sirvió de algo mi respuesta o iba por otro lado tu pregunta xD

**Comment by gnacrur** [comment]
Muchas gracias por tu respuesta! Me aclaraste varios puntos y el link que mandaste esta muy bueno. La única duda que me iria quedando es en relación a esto que mencionas: 

> En complemento a 2 no divides en mitades iguales la representación de negativos con positivos. Esto sólo ocurre con el complemento a 1.

Si tengo 8 bits entonces tengo 2^8 posibles números. Pero como quiero tener representaciones positivas y negativas si tengo n positivos ( (2^8 /2)-1 ), entonces deben haber n negativos. A eso me refería con la mitad, no se si me estoy confundiendo.

**Comment by Arcoirisky** [comment]
Oh, entonces estás bien. Pensaba que te referías a la mitad de forma literal, porque de ser así tienes el problema del doble cero. Caso que se resuelve en complemento a dos. 

Pero lo que dices está bien :D si tienes 8-bits entonces en complemento base dos puedes representar (2^(8-1))-1 Positivos y (2^(8-1)) negativos.
