### ISSUE TITLE
T1 | Alerta Assembly memoria virgen

### ISSUE THREAD

**Issue by andresplass** [IIC2343/Syllabus-2020-2#92]
Hola, queria saber si afectaba en la nota el hecho de obtener el aviso "X es una dirección de memoria virgen". Al parecer no afecta en desempeño de código (ya que no lo corta) pero quería saber si importaba de todas maneras, al menos en el puntaje de la pregunta.
Gracias!

**Comment by aaguilarg** [comment]
Hola @andresplass, ese warning se levanta (como dice el mismo warning) al leer una dirección virgen. Este warning se levanta ya que, cuando lees una dirección virgen se te entrega un valor random, para que estes atento con eso. Pero no, no afecta ni al rendimiento ni al puntaje (siempre y cuando la respuesta sea la correcta)

**Comment by andresplass** [comment]
Sii, entiendo que entre a memoria random! me aproveché que es un emulador.
Muchas gracias
