### ISSUE TITLE
Duda Memoria

### ISSUE THREAD

**Issue by gnacrur** [IIC2343/Syllabus-2020-2#93]
Hola, quería simplemente preguntar si es factible retener un valor guardado en memoria de un registro entre más de un flanco de subida. Se me ocurre alimentar al registro con su mismo output y que tenga un mux para decidir si conserva ese valor o usa un dato nuevo. Me surge ademas la misma duda para la RAM, si puedo usar el data out del ciclo anterior para entregárselo como data in en el próximo ciclo. Gracias!

Edit: Creo que para esto podría usar la señal Load de los registros y en caso de querer quedarme con el resultado del ciclo anterior no actualizarlo.

**Comment by inmadariaga** [comment]
Hola!
Puede que esta issue te sea de ayuda, cualquier cosa comentanos:

[https://github.com/IIC2343/Syllabus-2020-2/issues/46](url)
