### ISSUE TITLE
T1 | 2.a Comparar simbolos

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2343/Syllabus-2020-2#94]
Hola!Tengo una duda respecto a la pregunta 2.a cuando quiero emular el funcionamiento de la maquina de turing en el computador que hice tengo que explicitar , es decir en el diagrama como arme el componente para que se verificará que efectivamente los simbolos que quiero comparar son iguales?

**Comment by aaguilarg** [comment]
Si, tienes que explicar eso

**Comment by RonaldoSosa** [comment]
Entendido!Gracias!
