### ISSUE TITLE
Bug Emulador | Problema con la visualización de valores de registros

### ISSUE THREAD

**Issue by lgolborne** [IIC2343/Syllabus-2020-2#96]
**Descripción del bug**
Al escribir un valor mayor a 127 en algún registro, este se muestra incorrectamente en el emulador en la sección de valores de estado. Esto no afecta el funcionamiento del código ya que efectivamente se guarda el numero original (como se muestra en la issue #79) , pero se muestra uno incorrecto y dificulta bastante el debugging.

**¿Cómo reproducirlo?**
MOV A, 148 muestra que se guardo el valor -108 en el registro A

**Comportamiento esperado**
Se debería mostrar que efectivamente se guardo el valor indicado

**Sistema operativo, versión del emulador y otros**
- Windows 10
- emu_lib-1.0.3-cp37-none-win_amd64.whl

**Comment by jmwielandt** [comment]
Hola, los registros se muestran como enteros con signo en complemento  a 2.
Así que... no es un bug, 148 en binario es `0b10010100`, que al pasarse a decimal considerando que está en complemento a 2 obtienes el -108.
Saludos
