### ISSUE TITLE
Problemas instalando emulador, aún despues de la T1

### ISSUE THREAD

**Issue by Clemente24** [IIC2343/Syllabus-2020-2#97]
Hola! Para la tarea 1 no logré instalar el emulador, y ahora estoy tratando de hacerlo nuevamente pero tengo problemas.

Uso Windows 10, python 3.7(64bits).  La primera vez que traté, tenía Anaconda instalado, después eliminé Anaconda e instalé python de nuevo, pero en ambas ocasiones el resultado fue el mismo.

Al descargar el archivo .whl, lo pongo en mi Escritorio y lo instalo con pip3.7 install "...".whl. 

![image](https://user-images.githubusercontent.com/19276556/94038227-0aaaec80-fd7b-11ea-9116-dbb677db5db1.png)

No sé por qué, pero no se me instaló en el mismo directorio, sino que se instaló en el directorio: C:\Users\cleme\AppData\Local\Programs\Python\Python37\Lib\site-packages, que es parte de la ubicación en donde está instalado python. 

Ahora, justo después de instalar, así se ve la carpeta \Lib\site-packages: 
![image](https://user-images.githubusercontent.com/19276556/94039280-5b6f1500-fd7c-11ea-8a2f-3e906f4cf476.png)
Ahí, se crearon ese archivo y esa carpeta que marqué.

Dentro de esa carpeta, no me aparece ningún archivo "main.py", sino que solo los siguientes: 

![image](https://user-images.githubusercontent.com/19276556/94039544-b6087100-fd7c-11ea-87b8-f3b390c4730d.png)

La verdad no sé qué es lo que pasa, pero cualquier ayuda es más que bienvenida, 

Gracias

**Comment by jerrymendoza** [comment]
@Clemente24 Hola!, después de instalar el whl debes abrir el main que se encuentra en el archivo emu-app.zip
  (mismo lugar de descarga) saludos!

**Comment by Clemente24** [comment]
> @Clemente24 Hola!, después de instalar el whl debes abrir el main que se encuentra en el archivo emu-app.zip
> (mismo lugar de descarga) saludos!

Hola! No me aparece ningún .zip en el lugar de descarga después de instalarlo...

**Comment by jmwielandt** [comment]
@Clemente24 
![image](https://user-images.githubusercontent.com/37153467/94425794-e5472580-0162-11eb-849b-1a6210bce940.png)

Ese es el .zip que debes descargar.

Al instalar con pip la librería del emulador, se instala como una librería más de python que puedes importar normalmente en tu código. El .pyd es un .dll renombrado que tiene los bindings necesarios para que se pueda usar desde python.

Saludos~
