### ISSUE TITLE
T2 | P1 ISA - Cómo escribirla

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#98]
Hola, al escribir la ISA de nuestra solución para la P1 solo es necesario indicar las nuevas instrucciones/opcodes? Podemos decir que el resto es tal como el computador básico si no es modificado?

PD: No hay label para la tarea 2

**Comment by aaguilarg** [comment]
Hola Vicente!
Efectivamente, lo que se pide en la pregunta 1 sólo modificar lo que consideres necesario, de manera justificada, para lograr los objetivos propúestos. En el caso de que no haya nada que modificar en alguna parte, pues se deja así el computador básico
