### ISSUE TITLE
T2 | P1 a 8 y 16 bits independientes

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2343/Syllabus-2020-2#99]
Hola, a que se refieren con tratar números de 8 y 16 bits de manera **independiente**, no se si podrían abordar un poco más este punto para ver las restricciones que debe tener mi solución?

**Comment by VicenteMerino** [comment]
Por ejemplo una duda que me surge con esto, es por qué no directamente aumentamos el tamaño de los buses como vimos en clases? Si al final si puedo soportar datos de 32 bits, puedo tener de 16 y 8 bits, pero supongo que esta independencia que se pide es la restricción sobre una solución de este estilo, así que si podrían explicar un poco más esto sería ideal.

**Comment by Arcoirisky** [comment]
Básicamente, lo que se te pide es que puedas hacer todas las operaciones del computador básico con números de 8 bits o de 16 bits. 

Lo nuevo es que debes poder manejar operaciones con 16 bits, ya que las de 8bits vienen por defecto en el cómo funciona el computador básico

El cómo lo quieras hacer, esta en tus manos uwu)

**Comment by VicenteMerino** [comment]
Puedo asumir que un número nativo de 8 bits solo lo podré operar con otro de 8 bits y lo mismo para los de 16 bits, o debo ser capaz de implementar compatibilidad?

**Comment by rihanuch** [comment]
Podría, por ejemplo tratar los 8 bits como 16? Al fin y al cabo los 8 estan contenidos dentro de los 16

**Comment by Arcoirisky** [comment]
@rihanuch si logras que funcione como se te pide sin que explote tu computador, ¡dale con todo! Recuerda que también tienes instrucciones que no quieres confundir con números 

@VicenteMerino ¿puedes explayarte un poco más?

**Comment by VicenteMerino** [comment]
@Arcoirisky Me refiero dentro de la ALU por ejemplo, que si quiero sumar dos número que son de 8 bits nativos, no debo dar soporte de sumarlo con uno de 16 bits.

**Comment by movalle4** [comment]
La idea es que los numero de 8 bits se puedan sumar con números de 8 bits y los de 16 bits con los de 16 bits. No es necesario agregar la opción de hacer operaciones entre 8 bits y 16 bits.

**Comment by VicenteMerino** [comment]
Mi solución debe ser capaz de hacer direccionamiento con 16 bits?

**Comment by VicenteMerino** [comment]
Y en particular poder por ejemplo hacer un CMP de números de 16 bits? O puedo asumir que este tipo de cosas solo se van a hacer con 8 bits (saltos, subrutinas, etc) y que con 16 bits solo me interesa poder leer/operar/escribir estos números?

**Comment by aaguilarg** [comment]
Hola @VicenteMerino,
en este pregunta se debe modificar <ins>todo lo necesario</ins> para que se soporten datos de 8 y 16 bits, es decir, debe poder funcionar como funciona el computador básico que conocen (todo) con datos de 8 y 16 bits, debe poder "adaptarse" a cualquiera. Ahí tu determinas como lo implementas, justificando por supuesto.

Espero que esto te ayude

**Comment by VicenteMerino** [comment]
Si pero por ejemplo, yo pensaba en que si quisiera dejar mi memoria como está, no tendría ningún sentido hacer direccionamiento con un literal de 16 bits (o eventualmente un registro), ya que no calza con el address. De que se puede implementar, modificando la arquitectura, se puede, pero por como está construida la arquitectura no tiene mucho sentido hacerlo ya que estaremos obligados a perder de cierta forma información del direccionamiento, no se si se entiende?

**Comment by aaguilarg** [comment]
Lo que se esta pidiendo es que se soporten tipos de datos de 8 y 16 bits de manera independiente, por lo que no se puede asumir que solo se haran cosas como saltos, subrutinas con datos de 8-bits. Por ello se pide que modifiquen la arquitectura para poder hacer estas cosas con esos datos también.

**Comment by sgutgar** [comment]
Hola @Arcoirisky, quiero preguntar por lo mismo que @rihanuch, puedo simplemente cambiar mi computador basico a uno que trabaje con 16 bits, dado que esto implica que pueda trabajar con numeros de 8 bits, o tengo más limitaciones que esta, por ejemplo que mi ram este limitada a palabras de maximo de 8 bits.

**Comment by rihanuch** [comment]
@sgutgar el profe dijo en clases que no habia problema en cambiarlo todo a 16 bits
